- .github/workflows/node.js.yml
- package.json
- packages/code-studio/src/test/eslint.test.js
- packages/components/src/test/eslint.test.js
- packages/jsapi-shim/src/test/eslint.test.js
- packages/log/src/test/eslint.test.js
- packages/react-hooks/src/test/eslint.test.js
- packages/utils/src/test/eslint.test.js
Cache all node_modules folders. If any package-lock changes the cache will miss and trigger `npm ci`. Most of the time this should let us skip `npm ci` which also calls `lerna bootstrap` saving ~2min per run.
Also cache the `.eslintcache` files generated in each package. Currently those will rarely miss, if ever, but cache for each branch will be preferred. This should greatly speed up the eslint Jest test we have in each package. Locally `npm run test:ci` took ~54s w/o eslintcache and ~30s w/ eslintcache on a rerun without changing files.
> Add caching of node_modules and eslintcache to Github Actions

- packages/utils/src/DbNameValidator.ts
> convert util DbNameValidator to TS

- packages/utils/src/DOMUtils.ts
As Matt pointed out we should probably be using `.closest()`. I will leave this PR here but this util may not be needed.
> convert util DOMUtils to TS

- packages/utils/src/TimeUtils.ts
Was wondering if we could do a custom type for time as `XX:XX:XX` but otherwise pretty straightforward.
> convert util TimeUtils to TS

- packages/code-studio/src/index.jsx
Fixes #42 
Not 100% sure why this fix works. Best guess is something to do with how CRA/webpack is deduping CSS imports. As far as I can tell they are deduped because adding the same sass import multiple times doesn't result in multiple copies of the rules showing up in dev tools
> Fix table options styling

- packages/utils/package.json
Types generation was missing from the utils package before. Now that we have most of it in TS we need to generate types on build for it
> Add types generation to utils build

- packages/chart/src/ChartUtils.js
Before we were just stringifying the enum, which is not safe as the enum is now a number instead of a string.
> Add proper translations for all chart source types

- packages/redux/package-lock.json
- packages/redux/package.json
- packages/redux/src/index.js
- packages/redux/src/reducerRegistry.ts
- packages/redux/src/reducers/index.js
- packages/redux/src/store.js
Allows modular code to register reducers
Blog post: http://nicolasgallagher.com/redux-modules-and-code-splitting/
> Implement react redux registry

- packages/code-studio/package.json
- packages/grid/src/Grid.jsx
- packages/grid/src/Grid.test.jsx
- packages/grid/src/GridModel.js
- packages/grid/src/GridRange.js
- packages/grid/src/KeyHandler.ts
- packages/grid/src/MockGridModel.js
- packages/grid/src/errors/PasteError.ts
- packages/grid/src/errors/index.ts
- packages/grid/src/index.ts
- packages/grid/src/key-handlers/PasteKeyHandler.test.tsx
- packages/grid/src/key-handlers/PasteKeyHandler.ts
- packages/grid/src/key-handlers/index.ts
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/IrisGridProxyModel.js
- packages/iris-grid/src/IrisGridTableModel.js
- packages/iris-grid/src/PendingDataBottomBar.tsx
- packages/iris-grid/src/TableUtils.js
- packages/iris-grid/src/ToastBottomBar.tsx
- packages/iris-grid/src/filters/FilterType.js
- Add new FilterType and getBaseType function to TableUtils
- Add basic paste functionality to an input grid
> enterprise update 3

- .github/workflows/node.js.yml
We're just using 14.x anyway, and it screwed up the Github checks
> Remove the testing matrix

- packages/iris-grid/src/TableUtils.js
Enterprise has a different class path for the DBDateTime class. Use both.
> Fix DBDateTime formatting on Enterprise side

- packages/components/src/context-actions/ContextMenu.tsx
Fixes #106 
Also skips unnecessary setStates when hovering over a menu item without a submenu
> Fix nested context menus at index 0

- packages/code-studio/src/dashboard/DashboardContainer.jsx
- packages/code-studio/src/dashboard/event-handlers/ConsoleEventHandler.js
- packages/code-studio/src/dashboard/event-handlers/LayoutEventHandler.js
- packages/code-studio/src/dashboard/panels/FileExplorerPanel.tsx
- packages/code-studio/src/dashboard/panels/NotebookPanel.jsx
- packages/code-studio/src/layout/LayoutUtils.js
- packages/code-studio/src/main/AppInit.jsx
- packages/code-studio/src/main/AppMainContainer.jsx
- packages/file-explorer/src/FileUtils.ts
- packages/file-explorer/src/WebdavFileStorage.ts
- Wire up dashboard changes to trigger saving to the workspace.
- The NotebookPanel soft saves to the layout whenever it's changed, which gets reloaded from the users workspace. Fixes #88.
- Prompt is shown when attempting to close a notebook that isn't saved.
- Copy functionality enabled from right clicking on the tab.
> Add dashboard layout/data saving to workspace, notebook copy

- packages/components/src/MaskedInput.tsx
- packages/components/src/context-actions/ContextActions.test.jsx
- Fix warning in MaskedInput about input not having an onChange handler - add a basic one, we just use handleKeyDown anyway
- Fix ContextMenu not resolving to an item
Fixes #99
> Fix up issues printed out when running tests

- packages/code-studio/src/dashboard/panels/ConsolePanel.jsx
- packages/console/src/Console.jsx
- packages/console/src/ConsoleStatusBar.jsx
- packages/console/src/command-history/index.jsx
- packages/console/src/console-history/index.jsx
- packages/console/src/index.js
- ContextActions can now be registered by the parent container instead of passed in
- Overflow actions are passed in and shown
- Pass in a node for displaying when console is disconnected unexpectedly
Fixes #112
> Properly register console actions and console disconnected messages

- package.json
- packages/components/scss/bootstrap_overrides.scss
- packages/components/scss/custom_webpack.scss
- packages/components/scss/new_variables.scss
- packages/components/src/BaseStyleSheet.scss
Actually fixes #102 I believe
Due to how npm works, it's not safe to directly import from node_modules in a package, which we were doing with `../node_modules/bootstrap` in `custom.scss`
Instead, this splits the custom variables a bit more so we can have the local import version for OSS components, and a version which uses ~ so Webpack will resolve to the module installed on the enterprise side.
Since bootstrap is a dependency of components now, when components is installed to enterprise, bootstrap may end up at the main `node_modules` folder and not inside of `node_modules/@deephaven/components/node_modules` where the original imports expected it to be.
We also don't need to nohoist bootstrap now since the relative path imports of bootstrap are only within OSS and we know the path where …
> Fix custom scss so it will work with enterprise node_modules

- packages/code-studio/src/dashboard/event-handlers/ConsoleEventHandler.js
- packages/code-studio/src/dashboard/events/ConsoleEvent.js
- packages/code-studio/src/dashboard/events/TabEvent.js
- packages/code-studio/src/main/AppMainContainer.jsx
- packages/console/src/Console.test.jsx
- Add onbeforeunload listener at the app level to prompt when closing the tab
- For testing, you need to have interacted with the page (click or keyboard) or else prompt will not show
- Removed unused disconnect/restart session wiring
Fixes #84
> Add prompt when closing tab

- packages/console/src/Console.jsx
- Was looking in state instead of props
> Fix disconnect status not resetting history items in Console

- packages/code-studio/src/dashboard/panels/ConsolePanel.jsx
Fixes #58
- The server does not support switching languages, remove that functionality
- Get the console types (languages) from the connection, use the first one as default
- Requires server changes https://github.com/deephaven/deephaven-core/pull/863
> Get console type from the API, don't allow switching language

- .github/workflows/publish-alpha.yml
workflow_dispatch action allows you to select the branch you want to execute the workflow from, however it doesn't let you select a PR that's currently in review if it's created from a fork.
By allowing a SHA to be input, we should be able to input the commit from the PR and it will publish from that.
> Update workflow_dispatch action to take a git SHA

- packages/code-studio/src/main/publish-nightly.yml
Right now it's publishing to GitHub packages. Once we've verified it's working there, then I'll update to publish to npmjs
> Create a publish nightly action

- .github/workflows/publish-nightly.yml
- Add a `check_date` step that ensures it only runs if there's been a commit in the last 24 hours
- Add the `canary` flag so it publishes a proper version (instead of bringing up a prompt)
> Fix the nightly publish action

- packages/components/src/BaseStyleSheet.scss
We were already supposed to be doing this, but we weren't hiding the right element so it was showing an empty box.
Update it to hide the correct element.
Fixes #144
> Hide the suggestion widget when it's showing a status message

- packages/code-studio/src/main/AppControlsMenu.jsx
- packages/code-studio/src/main/AppMainContainer.jsx
- packages/components/src/context-actions/GlobalContextAction.tsx
- packages/console/src/monaco/MonacoUtils.js
- packages/iris-grid/src/IrisGridShortcuts.ts
- packages/iris-grid/src/key-handlers/ClearFilterKeyHandler.ts
- packages/iris-grid/src/key-handlers/ReverseKeyHandler.ts
Fixes #142 (mostly). See #151 which will address remaining shortcut problems.
Removes the global shortcut handlers from being attached to the capture phase instead of bubble phase. This makes local shortcuts take precedence over global shortcuts. Also means linker won't trigger when inside of monaco, but monaco has its own shortcuts and Don said we should just leave monaco shortcuts alone instead of removing them so our shortcuts work globally (really it's only linker)
> Fix Some Shortcut Problems

- packages/console/src/Console.jsx
- packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
Before, it would collapse the error message often while you were trying to select text. A couple of fixes:
- Sets `isClicking` on mouse down to start the click. Prevents cases where you drag into the error message from outside collapsing the error message
- Don't register the click if the user is holding Shift - they could be trying to update the selection
Fixes #149
> Improve console error message handling

- packages/code-studio/.env.development
- packages/code-studio/package.json
- packages/code-studio/src/setupProxy.js
Alternative to Don's PR #172 . Needed to add the `ws: true` bit so websockets worked for the api as well.
> Using the http-proxy-middleware to proxy

- packages/components/src/BaseStyleSheet.scss
- packages/grid/src/GridRenderer.js
- packages/iris-grid/src/IrisGridTheme.js
- packages/iris-grid/src/IrisGridTheme.module.scss
This change updates scrollbars (monaco, grid, native) to all look _similar_. Since we can't control the monaco scrollbar styling, we instead match it. This style should look better for adding "selection-ticks to grid scrollbars" eventually anyways.
Monaco:
- Unchanged
Native:
- Changes native scroll bars in blink/webkit to be styled similar monaco scrollbars
- Adds a light scrollbar variant for areas in the app that use a light bg
- Remove explicitly setting colors in firefox, in favor of just 'auto'
Grid:
- Changes grid scroll bar styling to have just an inner casing, rather than both sides
- Makes scroll thumb square instead of rounded to match
- Make it slight wider by default
- Adjusts colors
(left: monaco, bottom-right: grid, top-right: native)
> Make scrollbar styling consistent

- packages/code-studio/.env
- packages/code-studio/src/dashboard/panels/NotebookPanel.jsx
- packages/console/src/monaco/MonacoUtils.js
- packages/console/src/monaco/lang/scala.js
- packages/console/src/notebook/ScriptEditorUtils.js
- packages/file-explorer/src/FileUtils.ts
Although this is not yet available via the DHC server, the change-set itself is valid and mergeable.
I did notice that the python implementation both is similar and dissimilar to the official monaco-languages python definition. We appear to be missing a handful of keywords. Also, I suspect that the python implementation needs to properly reference the original MIT license.
I wasn't sure of exactly how to make it clear the scala implementation was sourced from a piece of work under the MIT license. I took a first stab at it, but suspect it is inadequate.
I'd be happy to give a demo with or without notice. Looking forward to hearing how to proceed.
> Enable Scala syntax highlighting

- packages/code-studio/src/dashboard/LocalWorkspaceStorage.ts
- packages/iris-grid/src/Formatter.js
- packages/iris-grid/src/Formatter.test.js
- Default formatting rules were legacy from Enterprise days. Remove these rules, as they are unexpected in Community.
- Fixes #197
- Breaking Change: Formatter no longer has getDefaultFormattingRules
> Remove default formatting rules

- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
- Instead of publishing to GitHub packages, publish to the default registry (npmjs).
- Uses my deploy token as a secret.
- Add publish-packages action to publish release packages. Will be triggered manually.
> Update publish actions

- .github/workflows/create-release.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
Even though it defaults to registry.npmjs.org, it doesn't use auth unless you specify the registry: https://github.com/actions/setup-node/blob/25316bbc1f10ac9d8798711f44914b1cf3c4e954/src/main.ts#L46
Also updated a couple action names to be publish instead of build
Add a create-release action, that bumps the version and adds the release to GitHub. Note that the publish step still needs to be triggered after this.
> Add registry-url back, add release action

- .github/workflows/create-release.yml
By default, actions/checkout only checks out the latest HEAD. Need to get the full fetch depth to create the proper changelog
> Add fetch-depth to fetch changelog properly

- packages/components/src/context-actions/ContextActions.tsx
- packages/components/src/context-actions/ContextMenuRoot.tsx
- packages/console/src/Console.jsx
- packages/console/src/ConsoleInput.jsx
Fix the issue with an unusable Monaco context menu when Monaco is nested in a component having its own `ContextMenu` with a non-empty `actions` list.
> Don't show custom context menu on right-click in Monaco editor

- .github/workflows/publish-packages.yml
I forgot to include this flag. We have the version bump as a separate step, so this should publish whatever version is already commited.
> Add `from-package` flag to publish step

- packages/iris-grid/src/AdvancedFilterCreatorFilterItem.jsx
- packages/iris-grid/src/AdvancedFilterCreatorSelectValue.jsx
- packages/iris-grid/src/TableUtils.js
- packages/iris-grid/src/TableUtils.test.js
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Depends on https://github.com/deephaven/deephaven-core/pull/1516
- Cherry-pick https://gitlab.eng.illumon.com/illumon/iris/commit/31eba3cc797384aac1b7bb583e29367cd49f718b
- Cherry-pick https://gitlab.eng.illumon.com/illumon/iris/commit/7dc13172a1998a6ad093bdb850eb7b99e5ead938
- Add back the TODOs - they're still not working in Community
> Fix advanced char filters

- .github/scripts/label-check-one-of.sh
- .github/workflows/label-check-ci.yml
- Checks if one of the lerna-changelog tags is present
You can see a failed check here: https://github.com/deephaven/web-client-ui/runs/4081157392?check_suite_focus=true
I like how it tells you how to correct the problem:
> Error: Label check failed: required 1 of bug, enhancement, internal, documentation, but found 0.
We should consider adding that to `check-doc-labels.sh` in `deephaven-core` as well, as the current error "No documentation requirements found" and "Conflicting documentation requirements" is vague/requires prior knowledge of which labels satisfy that condition.
> Add a label check action

- packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
- packages/grid/src/Grid.test.jsx
- packages/grid/src/GridRenderer.js
- Fixed binary search loop - was checking `hi > lo` instead of `hi >= lo`
- Add a check to handle case where the text never fits
- Set lo to be lower just in case our estimate wasn't low enough
- Return empty string instead of null for consistent return type
- Fix mock iris grid to send an update (styleguide just kept showing the spinner since it was waiting for an update event)
> Fix text truncation at very narrow widths

- packages/iris-grid/src/IrisGridTheme.module.scss
There were a couple of theme values missing for input tables. Add them back.
Looks like these were the only values missing (checking the theme in a previous Enterprise branch)
> Fix theme for input tables

- packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
- packages/grid/src/GridMetricCalculator.js
- packages/grid/src/GridModel.js
- packages/grid/src/GridRenderer.js
- packages/grid/src/GridUtils.js
- packages/iris-grid/src/ColumnStatistics.jsx
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/IrisGridModel.js
- packages/iris-grid/src/IrisGridProxyModel.js
- packages/iris-grid/src/IrisGridTableModel.js
There is some possible refactoring optimization to be had in `drawColumnHeaders` but it looked quite ugly locally since the loops contents relied on too many scoped+calculated vars. Still open to suggestions in either case.
> DH-11632 handle LH frozen columns in the UI

- packages/iris-grid/src/ColumnStatistics.jsx
- packages/iris-grid/src/ColumnStatistics.scss
- packages/iris-grid/src/mousehandlers/IrisGridColumnTooltipMouseHandler.js
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
> This is a small annoyance, but I would love to have "copy header" on the header right click menu.I can get it from the copying a selection with headers, but it would be nice to just copy the header.Just one. I'm copying it and using it a text. Either pasting into some Javascript code or putting it in an Excel Spreadsheet.
fixes [DH-11843](https://deephaven.atlassian.net/browse/DH-11843)
Added to column menu and column tooltip.
> Ability to copy column header from ui

- packages/code-studio/src/main/WidgetUtils.ts
- packages/dashboard-core-plugins/src/events/ControlEvent.js
- packages/dashboard-core-plugins/src/events/index.js
- packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Two fixes:
- The "Close Panels on Disconnect" option wasn't working. This is because I was emitting the incorrect event (nothing listened to `ControlEvent.CLOSE` anymore)
- If the "Close Panels on Disconnect" option was not selected, the tables would not re-open on browser refresh. This is because I was passing the table name in the `id` field, instead of the `name` field.
Fixes #286
> Fix issue where tables would not reload after refreshing the page

- packages/console/src/common/ConsoleConstants.ts
- packages/log/src/DefaultLogger.js
Fixes #189 
Must use try/catch instead of `typeof process === 'undefined'` because CRA injects the values at build time. `process` will be undefined in a browser even w/ CRA.
Needed for docs plotting as docusaurus doesn't inject `process.env` variables like CRA does
> Fix log and console crashes if process is undefined

- packages/console/src/console-history/ConsoleHistoryItem.scss
- packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
fixes #192 
This was clearly intentionally allowed before but I agree the new behaviour is better.
> do not collapse console errors on mouseUp

- packages/iris-grid/src/IrisGridTableModel.js
Not sure if this is the ideal path but the event detail and copyTotalsData were doing the right thing yet the aggs table wasn't updating until a viewport change happened. Easy review though!
> DH-11661 refresh viewport on IrisGridTableMode.handleTotalsUpdate

- packages/grid/src/GridMetricCalculator.js
fixes #299 
This seems to work as expected now.
> account for number of floating bottom rows in lastTop

- packages/chart/src/ChartModelFactory.js
- packages/chart/src/ChartUtils.js
- packages/chart/src/ChartUtils.test.js
- packages/chart/src/FigureChartModel.js
- packages/chart/src/MockChartModel.js
- packages/chart/src/index.ts
- packages/chart/src/plotly/Plot.js
- packages/chart/src/plotly/Plotly.js
- packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx
Fixes some issues for charts in the docs snapshot tool. Mainly moving the theme out of ChartUtils so the snapshot tool (in Node) can import ChartUtils and not crash from being unable to handle the css import
> Chart fixes for docs snapshots

- jest.config.cjs
Started with a baseline threshold just below existing levels for the whole project.
However, since the coverage report only runs on existing changes, it will check your diff and fail if they fall below those levels.
Only using the 'text' type reporter as that will be output in our console or in CI log output and we can see the failures from there.
> Enable code coverage tests, add thresholds

- packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
- packages/components/src/popper/Popper.tsx
- packages/components/src/popper/Tooltip.tsx
- packages/iris-grid/package.json
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/mousehandlers/IrisGridColumnTooltipMouseHandler.js
When column tooltips are displayed above the table, instead of below (due to being to close to the bottom edge of the window) attempting to mouse into them was triggering them to close.
This was caused by IrisGridColumnTooltipMouseHandler triggering its own onLeave even when y < 0  that dismissed the tooltip.
This handler is actually unnecessary, as the popper has its on move handler on the window, that handles dismissing when the mouse moves outside the bounds of the popper OR **the parent** of the popper. And the parent in this case is a wrapper div that is temporarily created by iris gird, and is sized exactly to the column header.
Previously, this wrapper was used for positioning as well. However, this wrapper was being sized to the column width, which meant if the column was wider, …
> DH-11923: Fix column tooltip when above the table

- __mocks__/dh-core.js
- packages/chart/src/ChartUtils.js
- packages/iris-grid/src/Formatter.test.js
- packages/iris-grid/src/TableUtils.js
- packages/iris-grid/src/TableUtils.test.js
DBDateTime is moving due to an engine change, update to use the new name.
Engine PR: https://github.com/deephaven/deephaven-core/pull/1473
> Update DateTime reference to new package location

- packages/code-studio/src/log/LogExport.ts
- packages/code-studio/src/settings/SettingsMenu.jsx
Fixes #196 
Adds a file `metadata.json` to the support log zip which currently just contains `uiVersion`
> Add UI version to support log data

- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanel.jsx
- packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.jsx
Was setting `undefined` but checking against `null`. Instead check against `undefined`.
> Fix the isolated linker

- .github/workflows/node.js.yml
- README.md
- codecov.yml
- jest.config.cjs
- Create codecov.yml, with the carryforward flag for partial reports. Already uploaded the initial full report from current `main`
- Add badge to readme
- Enable only on pull requests
> Enable codecov support 

- packages/components/src/AutoResizeTextarea.tsx
- component used by enterprise extra args in console creator
- causes componed to "explode" when mousedown without a focus event, which only happens clicking and dragging the resize handler (which is the desired behaviour)
> DH-10112: Make AutoReszieTextarea explode on resize

- packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
Count now works as an aggregation for non-rollups. There are no longer any that are rollup exclusively. Leaving code to allow it in future in case any new rollup only aggregation method gets added.
> DH-11788: Enable count aggregations for non-rollups

- .github/workflows/node.js.yml
- packages/chart/src/ChartUtils.js
Codecov should be updated on push to main so diffs against main work properly. Also limits the action to search for coverage only in the coverage directory
> Fix codecov problems

- packages/iris-grid/src/CrossColumnSearch.jsx
Fix the issue with cross-column search where it doesn't properly restrict to selected columns. Tested manually, unit tests pass.
> Cross column search does not restrict to selected columns

- packages/console/src/ConsoleInput.jsx
> Remove cursor position marker in console input bar when scrollbar is hidden

- packages/dashboard-core-plugins/src/ChartPlugin.tsx
- packages/dashboard-core-plugins/src/ConsolePlugin.tsx
- packages/dashboard-core-plugins/src/FilterPlugin.tsx
- packages/dashboard-core-plugins/src/GridPlugin.tsx
- packages/dashboard-core-plugins/src/MarkdownPlugin.tsx
- packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
- packages/dashboard/src/DashboardLayout.tsx
- packages/dashboard/src/DashboardPlugin.ts
- packages/dashboard/src/PanelManager.test.ts
- packages/dashboard/src/PanelManager.ts
- Added `getLastUsedPanelOfTypes` to PanelManager (will be needed for Enterprise)
- Clean up some of the TypeScript types
> Fix Send to Active Notebook functionality

- packages/components/src/context-actions/ContextActions.test.tsx
- packages/dashboard/src/PanelManager.ts
- VSCode likes to default to importing from the local index.ts file, which causes a circular import. This in turn breaks some mocks that `requireActual`. Fix up the imports to import directly from the file rather than from the index.
> Fix a couple of imports

- packages/components/src/AutoResizeTextarea.tsx
Fixes difference in default size in FF, chrome was fine with either.
Firefox calculates scrollHeight differently then chrome with height auto. Setting height 0 instead makes them both behave the same. Component is setting height to 0, getting the scrollHeight, then setting component to that height.
Screenshot shows chrome left/firefox right. After this change they both behave like chrome screenshot.
> Fix autoresizetextarea default height in Firefox

- packages/components/src/Button.tsx
- packages/console/src/Console.jsx
- packages/console/src/csv/CsvOverlay.jsx
- You can select text and drag it in a browser (kind == "string"), this shouldn't trigger the csv overlay
- Fix Button component proptype error with "type" other than button requiring an onClick function ex. (csv overlay bar, type=submit)
- Multiple file error should return, as filetype error can replace it
> Don't trigger console csv upload overlay if dragging text

- packages/console/src/ConsoleInput.jsx
Fixes DH-10208
Up arrow only takes you to previous command if at top line. Keeps focus on top line
Down arrow takes to next command if at bottom line. Keeps focus on bottom line
Doesn't affect commands double clicked from history. Those are. viewed as edited commands and don't cycle through history
> Better console history handling of multi-line commands

- packages/code-studio/src/main/AppInit.jsx
- packages/code-studio/src/main/AppMainContainer.jsx
- packages/code-studio/src/main/AppMainContainer.test.jsx
- packages/dashboard-core-plugins/src/index.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
- packages/dashboard-core-plugins/src/prop-types/UIPropTypes.js
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
- packages/jsapi-shim/src/PropTypes.js
- packages/utils/src/TestUtils.ts
Plugin permissions were implemented in an old version, cherrypick to DHC
https://deephaven.atlassian.net/browse/DH-11752
https://gitlab.eng.illumon.com/illumon/iris/merge_requests/6181/diffs
Fixes #326
> Cherry-pick plugin permissions from Enterprise

- packages/jsapi-shim/src/dh.js
- packages/jsapi-shim/src/dh.ts
This is getting very annoying to work around in docs since SSR has no window object and can't be defined globally it seems due to module scope/whatever environment the SSR on docs runs in. The global workaround I've used for Node in other places doesn't work w/ the docs SSR.
This shouldn't affect anything for our app and just make the shim function in docs SSR. The API isn't actually used in SSR, but the utils import the shim which then errors out since window is undefined
> Make jsapi-shim more robust

- packages/code-studio/src/main/AppMainContainer.jsx
- packages/code-studio/src/main/AppMainContainer.test.jsx
- Export links and filterSets in addition to the layoutConfig
- Add a version to the exported layout
- Add support for importing legacy version of layout
- Fixes #314
> Export links and filterSets with layout

- packages/console/src/ConsoleInput.jsx
Fixes #374 
Sending an item from history to console (or notebook to console) should overwrite the new command. Executing a previous command will erase the new command just like all other edits
Example
1. Type something
2. Arrow up to last item in history
3. Double click a different item in history (the "something" from earlier is now gone)
4. Arrow up should go to last item in history again. Arrow down should go nowhere
> Maintain temporary edits to console history items until execution

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- README.md
- packages/code-studio/README.md
Adds the core settings for vscode that everyone should be using. Also added the extensions we all use as workspace recommended extensions. Now a new contributor just needs to open VSCode and install workspace recommended extensions to be setup in VSCode.
We should add debug configs to this in the future.
> Add vscode workspace shared settings

- packages/code-studio/.env
- packages/code-studio/.env.development
- packages/code-studio/package.json
- packages/code-studio/src/DownloadServiceWorkerUtils.js
- packages/code-studio/src/main/AppMainContainer.jsx
- packages/code-studio/src/main/AppRouter.jsx
- packages/dashboard/package.json
- packages/dashboard/src/Dashboard.tsx
- packages/dashboard/src/DashboardLayout.tsx
- packages/dashboard/src/layout/LayoutUtils.js
- tsconfig.json
Resolves #269 
Adds routes `/notebook/:notebookPath` which will open the provided notebook path if it is not open in the workspace and focus it within its stack if it is open in the workspace. The paths can contain slashes to denote directories so `/notebook/myFolder/myFile.py` would open `/myFolder/myFile.py` from the file explorer
If the file does not exist, it will open a panel which will then fail to load the file and give an error in the panel about the file not existing/unable to be loaded.
Tested locally setting `REACT_APP_ROUTER_BASE_NAME=/ide/` in my `.env.development.local`
> Deep linking notebooks

- packages/babel-preset/index.js
- packages/utils/src/EventTargetShimUtils.ts
This was causing an issue w/ redefined shortcuts in Monaco. Specifically in EventTargetShimUtils
The class which needs to declare to TS that fields will exist (because the event-target-shim Event type and CustomEvent don't play very nicely together) was having those fields initialized to undefined even though they will be defined by the super constructor.
```ts
class A {
field: string;
}
```
Previous to #370 the types would be stripped before babel got the file, but TS will likely change this behavior in the future to not remove fields like above. Instead you have to use `declare field: string` to have TS remove it.
Reference: https://github.com/babel/babel/issues/12128#issuecomment-702119272
> Fix babel public class fields plugin

- packages/code-studio/package.json
If you save w/ react hot reload/fast refresh then the React error iframe tries to pop up/initialize and fails. This freezes the page requiring a reload.
The fix is to specify a version of `react-error-overlay` according to the create react app ticket below. Should be fixed in CRA v5
https://github.com/facebook/create-react-app/issues/11773#issuecomment-995933869
> Fast refresh fix

- packages/file-explorer/src/FileExplorerToolbar.scss
- Size the toolbar to match the input including the padding
- Renamed CSS variables to make more sense
- Tested by opening page and activating the FileExplorer tab
Fixes #349
> Fix File Explorer causing scrollbars to appear

- packages/components/src/BaseStyleSheet.scss
- packages/embed-grid/package.json
After element has the focus ring, box-shadow should be removed on actual element
Fixes the inner focus circle showing up:
> Fix double box-shadow focus ring on iconOnly ghost buttons

- packages/components/src/popper/Popper.tsx
- packages/components/src/popper/Tooltip.tsx
- packages/iris-grid/src/IrisGrid.jsx
- Resolves Grid column tooltips don't work when mouse enters from above #412
- tooltips now have onExited callback, irisgrid updates it's internal state now tooltip exit
- Caused by fix for pr #306, introduced this new edge case
- Remove this.isExiting from popper, doesn't appear to ever have been used
> Fix irisgrid tooltip state tracking

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
- packages/grid/src/Grid.tsx
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/IrisGridUtils.js
- Persist isStuckToBottom state from grid
- Moved from a property on grid to the state
Tested with the following snippet:
```
from deephaven.TableTools import emptyTable
t = emptyTable(100).update("A=i")
```
Scrolled to the bottom and refreshed the page. Table stayed and was stuck to bottom.
> DH-10241: Persist grid isStuckToBottom state

- __mocks__/dh-core.js
- packages/iris-grid/src/IrisGrid.jsx
I'll explain the whole flow for reference.
From enterprise IrisGridPanel we are passed `canToggleSearch` which considers the boolean server config setting `ui.show.search`. Tables can have this overridden however via Layout Hints. This PR handles the override case where if a LH is found we simply ignore the server config and use the LH value.
The API support for this work is deployed on the BHS, `davor-searchbar-api` if you wish to test it in action.
> DH-12099 IrisGrid canToggleSearch should allow override by layoutHints

- __mocks__/dh-core.js
- packages/iris-grid/src/IrisGrid.jsx
The constants do not exist on DHC JS API, so we need to check if they exist first
Fixes bug from #404
> Fix uncaught error from #404

- packages/grid/src/GridColorUtils.ts
Lab precision was being rounded, so at depth 0 the hex -> lab -> hex round trip lost precision and modified the colours. Use full raw value to maintain color accuracy.
https://github.com/Qix-/color-convert#api
> Fix table row color darken for depth 0

- packages/iris-grid/src/IrisGridProxyModel.js
We don't want updates from the previous model when we're waiting for the new model to be set. Causes loader to stop prematurely.
> Remove listeners before setting next model

- packages/components/src/MaskedInput.tsx
- packages/components/src/TimeInput.test.tsx
- packages/components/src/TimeInput.tsx
Now MaskedInput allows a function to be passed to provide the preferred replacement string. Check the current selection and the replacement char to see if it falls in a specific case for TimeInput, and provide a different string if necessary
> DH-10082 Fix unexpected time input behaviour

- packages/console/src/Console.jsx
- packages/console/src/ConsoleInput.jsx
- packages/console/src/ConsoleInput.scss
- packages/console/src/console-history/ConsoleHistory.jsx
- packages/console/src/console-history/ConsoleHistoryItem.jsx
- packages/console/src/console-history/ConsoleHistoryResultInProgress.jsx
- packages/console/src/csv/CsvInputBar.jsx
- Instead of immediately adding all objects to disabled objects, just show them as disabled
- Connection could still come back, at which items should be enabled again
> DH-12087 Allow better handling when disconnected

- packages/grid/README.md
npmjs doesn't handle the `directory` spec in package.json when building links. I've made a separate PR to fix that, but I doubt it will ever be merged: https://github.com/npm/marky-markdown/pull/455
Workaround is to just use absolute links.
> Update readme links to absolute paths

- packages/dashboard/src/layout/LayoutUtils.js
The default config doesn't have some props defined for some components that don't need them
Fixes #477
> Use empty object for props if undefined

- packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingMenu.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
- Filter out unsupported columns in ConditionalFormatEditor
- Use more specific `isStringType` instead of `isTextType`
Fixes #483
> Disable formatting for array columns

- .github/workflows/node.js.yml
- .stylelintignore
- jest.config.cjs
- jest.config.lint.cjs
- jest.config.unit.cjs
- package.json
Fixes #394 
The Jest tests have been changed to run all unit tests and only lint changed files in CI. Local `npm test` still does changed only in watch mode.
Updated caching to utilize jest cache (helps schedule tests for faster runs) and webpack/terser caches. These are stored in `node_modules/.cache` so they need to be restored after `npm ci` which removes `node_modules` if it exists.
The cache for PRs should hit the previous tested commit in the PR or the latest target branch cache entry. On pushes to main, the cache should always hit the previous commit.
> Re-enable Codecov reporting

- packages/code-studio/src/main/AppInit.jsx
- packages/code-studio/src/settings/FormattingSectionContent.jsx
- packages/grid/src/GridModel.ts
- packages/grid/src/GridRenderer.ts
- packages/iris-grid/src/Formatter.ts
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/IrisGrid.test.jsx
- packages/iris-grid/src/IrisGridProxyModel.js
- packages/iris-grid/src/IrisGridRenderer.js
- packages/iris-grid/src/IrisGridTableModel.js
- packages/redux/src/selectors.ts
- packages/redux/src/store.ts
This adds the ability to truncate number columns with ### instead of cutting and adding an ellipsis at the end. There is a new setting in the settings panel to toggle the option.
Tested with this python snippet
```python
from deephaven.TableTools import newTable, intCol, doubleCol
table = newTable(
intCol("Int", 123456789, 234567890, 42, 8675309, 1),
doubleCol("Double", 123.456, 555555.5555, 1234567890.1234567890, 42.42, 1.0)
)
```
> DH-12166: Allow truncating number columns with pound symbol

- packages/grid/src/GridMetricCalculator.ts
- packages/iris-grid/src/IrisGridMetricCalculator.ts
We weren't re-caculating the size of the column if the user width was set when the grid was loaded.
Fixes #476
> Always populate the calculated item size maps

- package-lock.json
- packages/code-studio/src/main/AppMainContainer.scss
- packages/components/package.json
- packages/components/src/SocketedButton.scss
- packages/components/src/TimeSlider.scss
- packages/embed-grid/package.json
- packages/stylelint-config/index.js
- Update Bootstrap version to 4.6.1
- Use sass-migrator to migrate division used in TimeSlider.scss and AppMainContainer.scss
```
npx sass-migrator division packages/components/src/TimeSlider.scss
npx sass-migrator division packages/code-studio/src/main/AppMainContainer.scss
```
- Visual smoke test to ensure visual consistency
- Use scss aware at-rule-no-unknown
- Fixes #484
> Fix sass deprecation warnings

- packages/iris-grid/src/sidebar/ChartBuilder.jsx
- packages/iris-grid/src/sidebar/ChartBuilder.test.jsx
- rm enzyme: refactor ChartBuilder tests to use RTL
- Send an event on isLinked update - before we weren't sending it, which wasn't really an issue because we didn't have live previews, but it was inconsistent.
- Replaces #491
> Remove enzyme from ChartBuilder tests

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
- packages/dashboard-core-plugins/src/panels/Panel.jsx
- packages/dashboard-core-plugins/src/panels/Panel.test.jsx
- packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
- packages/golden-layout/src/js/controls/Tab.js
- packages/iris-grid/src/IrisGrid.jsx
- Resolves #416
- Moved tabclick event in golden-layout to always fire on click, and not just when tab first becomes active in stack (so if tab is clicked when already at top, it still focuses table)
- listen to existing onTabClicked in panel and widgetpanel
- irisgridpanel onTabClicked focus irisgrid (which focuses grid)
> Focus irisgrid on tab click

- packages/iris-grid/src/Formatter.ts
Remove warnings for `TableUtils.getNormalizedType(...) === null`.
This is a valid case for column types rendered with the default formatter, no warning needed.
> Fix 'Unknown columnType' warnings

- packages/iris-grid/src/FormatterUtils.test.ts
- packages/iris-grid/src/FormatterUtils.ts
- packages/iris-grid/src/IrisGridTableModel.js
- packages/iris-grid/src/sidebar/TableSaver.jsx
Pass cell format as override to `getFormatterString` if custom format for column is not defined.
> Fix CSV download formatting

- packages/iris-grid/src/IrisGridTableModel.js
- packages/iris-grid/src/sidebar/TableSaver.jsx
Fix wrong order of the args passed to `isCustomColumnFormatDefined` resulting in inability to override query formatting via the UI custom format menu.
> DH-12387 Unable to override query formatting via the custom format menu

- packages/file-explorer/src/FileExplorer.scss
- packages/file-explorer/src/FileExplorerToolbar.scss
- There was a vertical scroll bar shown when the FileExplorer tab was the full height of the dashboard
- Add height/width 100% so it fills the container
> Fix vertical scroll bar when FileExplorer tab shown

- packages/console/src/ConsoleInput.jsx
Fixes #537. This was discovered as part of DH-10208 testing which is tangentially related to where the bug was actually introduced.
Now at the top of history in the console input, pressing arrow up should not move up to other commands
I tried to write a test for this w/ RTL, but was hitting obstacles w/ Monaco so I just skipped it for now
> DH-10208 Fix arrow up at top of history loading empty history commands

- packages/iris-grid/src/IrisGrid.jsx
- When the column is resized, we were updating props but not calling tooltip.update() to update the existing tooltip
- Needed to bring the getBoundingClientRect method out of the in line definition - before, even after getting called again, it was just using the old values (what the values were when the function was created). Pulled the latest metrics from `this` and then it's good.
- Side note: Because of the order of mouse handlers, the tooltip mouse handler doesn't get an event on click; it's eaten by GridColumnSeparatorMouseHandler. We don't really want to change the order of those mouse handlers, as the tooltip should be a low priority thing (i.e. we don't want to tooltip appearing when hovering over the column separator), so did not adjust the ordering.
- Fixes #510
> Fix column tooltip not repositioning correctly when resizing columns

- packages/iris-grid/src/IrisGridRenderer.js
This fixes 2 small issues with the cell overflow button.
1. Cell overflow button was overlapping the horizontal scroll bar. Now it draws under the scroll bar. It should still show even if the scroll bar partially covers a row because you can have the row covered by 1-2 pixels and you will see all content in the cell still. The overflow not appearing because the border is overlapped by the scroll bar could be frustrating to a user.
2. Cells were not truncating properly when `IrisGridTheme.rowHeaderWidth` was non-zero. The header width was not accounted for
> Fix cell overflow button overlapping scroll bar and not truncating text with row header

- packages/grid/src/Grid.tsx
- packages/grid/src/GridMetricCalculator.ts
- packages/grid/src/GridMetrics.ts
- packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
- packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
Fixes #446 and related to DH-10111 test failure
This adds a horizontal scroll bar for any single column table which does not fit in the panel fully
Example Python to test with
```python
from deephaven.column import string_col
import random
import string
letters = string.printable
strings = [''.join(random.choice(letters) for i in range(random.randint(0, 1000))) for j in range(0, 100)]
table1 = new_table([string_col("Random", strings)])
```
Also tested with changing `IrisGridTheme.rowHeaderWidth` to be non-zero
> DH-10111 Fix missing horizontal scroll bar for single column tables

- packages/code-studio/src/main/AppMainContainer.jsx
- packages/code-studio/src/main/AppMainContainer.test.jsx
> remove enzyme code studio and replace with react-testing-library

- packages/embed-grid/src/App.tsx
Now you can embed grids from Groovy sessions as well
Fixes #573
> Use session type provided by the server instead of hardcoding python

- packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
Fixes Click to focus column is more annoying than useful #567
> Don't scroll columns into view on click

- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.test.ts
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
Applying custom columns with more than one row format column crashes the grid panel. Fixed by stacking all row formats into a single rule. Added unit test.
> Fix invalid format custom columns created from row formats based on different columns

- packages/components/src/ComboBox.test.tsx
- packages/components/src/ItemList.test.tsx
- packages/components/src/MaskedInput.test.tsx
- packages/components/src/RadioGroup.test.tsx
- packages/components/src/TimeInput.test.tsx
- packages/components/src/TimeSlider.test.tsx
- packages/components/src/context-actions/ContextMenuItem.test.tsx
- packages/components/src/context-actions/ContextMenuItem.tsx
- packages/components/src/navigation/MenuItem.test.tsx
- packages/components/src/navigation/Stack.test.tsx
> remove enzyme from components

- packages/iris-grid/src/IrisGridTableModel.js
When there is only one aggregation operation applied, it does not append the operation as a suffix to the column name in the totals table. Fix it up so it looks for the correct column name when there is only one operation.
This was noticed with the Count operation since the totals column format doesn't always match the source column format with Count, but happened with any type of operation.
Tested by running latest Jackson with `npm run start-community`, and with the `randomValuesWithNullNaN` table, applied one aggregation (`Count`), removed it, and then applied a bunch of different aggregations operations to test multiple aggregations.
> DH-11788 Fix aggregation formatting when only one aggregation is applied

- packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
- packages/iris-grid/src/IrisGrid.jsx
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridProxyModel.js
- packages/iris-grid/src/IrisGridTableModel.js
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx
Fixes #560. Also disables context menu freeze option on other locked columns (front/back). Added a check for columns listed in multiple layout hints which will display an error. 
Instead of modifying the model columns (which caused the initial issue), the model now defines a starting list of moved columns. The list is derived from the layout hints. If a user makes more changes, they are simply added to the moved columns list. The model column order is left untouched. The model base moved columns will be useful for column groups via layout hints
When a user unfreezes a column, it is moved to just after the remaining frozen columns + front locked columns. 
This may cause odd behavior in DHE PQs if the underlying table changes (but the original implementation would too). We should probably …
> Fix various layout hint issues

- packages/golden-layout/src/js/controls/Tab.js
- Should be listening for `click` instead (function is named `onTabClick`). This also ensures that the tab doesn't actually close until you lift your mouse, which allows you to cancel the action if necessary.
- `click` doesn't fire for middle mouse button, need to listen to `auxclick` as well: https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event
- Fixes #552
> Listen for click instead of mousedown on golden layout Tabs

- package-lock.json
- packages/chart/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/file-explorer/package.json
- packages/iris-grid/package.json
- packages/redux/package.json
- packages/storage/package.json
Just set them as regular dependencies. Peer dependencies need to be defined as explicit version numbers, and we're just using file:... notation for all dev/dependencies.
> Remove @deephaven peer dependencies

- packages/code-studio/src/styleguide/Grids.jsx
- packages/grid/src/Grid.scss
- packages/grid/src/Grid.tsx
Canvas renders a new line after the element (apparently). Set it to display: block so it doesn't.
See https://stackoverflow.com/questions/15807833/div-containing-canvas-have-got-a-strange-bottom-margin-of-5px
Fixes #602
> Fix grid resizing automatically when outer parent size not specified

- packages/iris-grid/src/IrisGridTableModel.js
- Wasn't matching the column name correctly
- Was identified when Distinct aggregations were not formatting correctly
- Just check if it's the only operation on a column
- See [core side for creating names](https://github.com/deephaven/deephaven-core/blob/fee2fa65b393d8dd2b9807e11ee8b5a1adcb9162/engine/table/src/main/java/io/deephaven/engine/util/TotalsTableBuilder.java#L621)
> DH-12627 Fix Aggregations formatting when only one operation on a column

- package-lock.json
- package.json
- Update lerna to v5.1.0
- npm audit fix
- Can try out the `useNx` flag: https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700
- Will require some configuration update. I tried to do it, but was getting an invalid project error.
> lerna 5.1.0

- packages/grid/src/GridMetrics.ts
- packages/grid/src/GridUtils.test.ts
- packages/grid/src/GridUtils.ts
This adds support for moving an entire range within a grid
The operation is to slice the range from the current grid, re-index the remaining columns as if the range was not there, and then insert with the first element in the range at the position specified
> Add support for moving ranges within grids

- packages/console/src/ConsoleInput.jsx
> Fix arrow keys not selecting next console suggestion

- packages/grid/src/GridMetricCalculator.ts
- packages/grid/src/GridMetrics.ts
- packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
- packages/grid/src/mouse-handlers/GridScrollBarCornerMouseHandler.ts
- packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
Fixes #619 
Also tested w/ setting a rowHeaderWidth in `IrisGridTheme` for horizontal scroll bar
> Fix grabbing scroll bar when filter bar is visible

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridRenderer.ts
- Was building the cached array of filters incorrectly, adding a nested array incorrectly. This caused the filters to error when being applied.
> Fix filters in IrisGrid

- packages/grid/src/Grid.tsx
- On resize, double check that the left/top values are still valid
- Fixes #542
> Fix issue with not showing all data and not showing scroll bar

- packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
We were dehydrating the filters from the `irisGridState` that were already dehydrated. This worked fine in most cases, but failed on timestamp column advanced filters.
> Fix filter set capture failing on timestamp column advanced filters, DH-12754

- packages/code-studio/src/main/AppMainContainer.jsx
- packages/grid/src/key-handlers/SelectionKeyHandler.ts
Resolves #663 by copying enterprise fix [DH-12258](https://gitlab.deephaven.io/illumon/iris/-/merge_requests/6443/diffs). Removes dead code. Also when #203 happened (split dashboard into package), it reverted #152 (fix ctrl-e shortcut)
Cleaned up h/j/k/l of unknown origin to be strict about no modifier, so that ctrl+L for linker also works again, as well as correctly support shift key.
> Fix broken ctrl+e to clear filters shortcut

- packages/grid/src/Grid.tsx
- packages/iris-grid/src/GotoRow.scss
- packages/iris-grid/src/GotoRow.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
I missed reviewing PR #638 before merge, here is some minor cleanup
- Simplified CSS using flex box, allowing for better wrapping and narrow panel sizes
- Use $spacer variables instead of fixed px sizes for spacing, ensures globally consistent paddings.
- Removed icon from context menu (per spec), and changed behaviour to toggle
- Focus on open, return focus on grid
Issue I need help with:
1. ctrl-g
2. type a row like 100
3. ctrl-g to close, which now correctly returns keyboard focus to grid
4. arrow down.
expected:
row is on 101
actual:
row jumps to row 2
So not sure what's being set incorrectly?
Assigning @SparkyFnay to fix the remaining issues:
Todo:
> Go to row UX cleanup

- packages/dashboard-core-plugins/src/panels/Panel.jsx
- packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.scss
Adds a context menu options when right clicking on a widget to "copy {widgettype} name". Think the order makes sense?
Adds a click to copy button to the tooltip for widget panels.
> Allow copying the widget name from tab context menu

- packages/iris-grid/src/IrisGridRenderer.ts
Fixes #678. Classic example of a falsy check bug. Matt has PR Enable TS strict boolean expressions linter rule #610 open that would have caught this.
> Fix model column [0] missing collapsed filter indicator

- packages/console/src/Console.tsx
Fixes #675 
Note that the `name` property on the object with type `VariableChange` is deprecated, the correct value should be stored in `title`. So instead of reverting `title` back to `name`, I added the object with a `title` property when it's created in `handleOpenCsvTable`
> fixed unable to open csv

- packages/components/src/context-actions/ContextActionUtils.ts
This potentially Fixes #660 
I was not able to reproduce the error, so I cannot verify that this resolved the issue. I tried reproducing using chrome/safari on `localhost:4000`, `localhost:10000/ide`, as well as the demo app on our website.
However, looking at the error stack trace, it seems that navigator.clipboard is returning undefined in some cases, thus when we call the writeText function, the error is thrown. 
I tried added a check for navigator.clipboard === undefined so that it goes straight to the fallback copy function.
> fixed copy cell unformatted not working in Long cells

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormatEditor.tsx
Allow rule to be undefined, as that is how an empty rule is initialized. Fixes #676.
> Fix broken conditional formatting sidebar

- packages/chart/src/ChartUtils.js
While investigating DH-9164 I found that DHE API returns `null` for empty axis labels, while DHC returns an empty string.
Passing `null` title text to Plotly results in incorrect axis position on twin Y charts.
We could fix it up on the API side, or just cast `null` titles to an empty string on the client side.
> DH-9164 Fix title overlap on twin Y charts in Enterprise

- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx
Wrapping was weird for long names, added no-wrap and alignment classes.
Before:
After:
> Improve copy button alignment in widget panel tooltip

- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Fixes #661, Typescript conversion messed up logic a bit due to null checks and asserts.
- refactored everything to allow an OR filter by menu, then tried it and realized it was pointless, anything that is already displayed would not make sense to be filtered with an OR.
- Booleans now have an OR menu (with all options in set), and a not null option, allowing you to create a false OR null filter.
- "And" menu is now nested under filter menu instead of separate root level menu, I think I like this better instead of being a separate option. Will see if anyone hates it.
- Fixed copy selection behaviour to be available outside rows/columns
- Fixed clear column to be available outside rows
- Fixed clear table filters to be disabled correctly (because I guess searchFilters is now undefined …
> Fixed missing boolean menu 

- packages/chart/src/ChartUtils.js
- packages/chart/src/FigureChartModel.js
- Automatically fill in labels with IDs if labels are blank
- Fix a possible null axis check
Tested with https://github.com/deephaven/deephaven-core/pull/2678
Was able to open and interact with Treemaps correctly
> Clean up treemap in web UI

- lerna.json
- package-lock.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-grid/package.json
- packages/file-explorer/package.json
- packages/iris-grid/package.json
- DH-9164 Fix title overlap on twin Y charts in Enterprise (#687)
- Version Bump v0.13.5
> Version Bump v0.13.5

- packages/iris-grid/src/AdvancedFilterCreator.tsx
- packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
- packages/iris-grid/src/AdvancedFilterCreatorSelectValue.tsx
- packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/jsapi-utils/src/TableUtils.ts
Broke from typescript migration. Fixes #648.
- Allow filterCondition to be null, it is used to clear filters and fix things that break due to that
- Make value list still show if table is not yet set, so that it reserves space rather than pop in.
> Fix broken advanced filter creator

- packages/dashboard/src/layout/LayoutUtils.ts
- packages/iris-grid/src/IrisGridProxyModel.ts
- Fix layout assertions for react components. Golden Layout switches the type in createContentItem and toConfig for some reason.
- Allow IrisGridProxyModel to pass through the table. This is necessary for FilterSetManager to work correctly
> Fix layout utils react config

- packages/iris-grid/src/mousehandlers/IrisGridColumnSelectMouseHandler.ts
To reproduce:
1. run this snippet of code:
```
t1 = empty_table(100).update_view('Col1 = ii')
t2 = t1.update_view('Col2 = Col1 * Col1').sum_by('Col1')
```
2. select the linker tool and select an exist column
3. now click any where that's not a column
Expected behaviour:
The link does not get set, and waits for selection of a column
Actual behaviour:
Program throws an assertNotNull error
The bug is fixed in this pr
> Fixed Linker throwing an error when clicking empty space with the linker active

- lerna.json
- package-lock.json
- packages/code-studio/package.json
- packages/dashboard-core-plugins/package.json
- packages/embed-grid/package.json
- packages/iris-grid/package.json
* `iris-grid`
* [#704](https://github.com/deephaven/web-client-ui/pull/704) Fixed Linker throwing an error when clicking empty space with the linker active ([@SparkyFnay](https://github.com/SparkyFnay))
- Tony Zhou ([@SparkyFnay](https://github.com/SparkyFnay))
> Version Bump v0.15.4

- packages/chart/src/ChartUtils.js
Fixes #708
Tested following the steps in the description.
> Provide the `outsidetextfont` for treemap charts

- README.md
- jest.config.cjs
Fixes #662 
`npm run test` locally will not collect coverage now. This is nicer because when you start the tests and then want to quit early to run a specific test, Jest does not calculate coverage for files
CI will still collect coverage as normal
> Only collect code coverage in CI

- packages/dashboard/src/layout/LayoutUtils.ts
- Golden layout sets the `type` to `component` in `createContentItem`, then changes it back in `toConfig`
- For our purposes, we just care what's in the `component` property itself, and `props`, so check both
> Check both componentName and component.type for react-component

- packages/grid/src/GridRenderer.ts
- Was checking column indices < 0 and >= columnCount for groups which is invalid
Tested with this snippet (added `table5` which doesn't have frozen columns):
```
from deephaven.column import string_col, char_col, int_col
groups = [
{'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
{'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'}
]
groups2 = [
{'name': 'MegaGroup', 'children': ['MyShorts', 'MyInts', 'Char5']},
{'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
{'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'}
]
groups3 = [
{'name': 'MegaGroup', 'children': ['MyShorts', 'MyInts', 'Char5']},
{'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
{'name': 'MyInts', 'children': ['Int2', …
```
> Don't check outside of min/max column bounds for groupings

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/format-context-menus/DateTimeFormatContextMenu.ts
- packages/iris-grid/src/format-context-menus/FormatContextMenuUtils.tsx
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/jsapi-utils/src/formatters/DateTimeColumnFormatter.ts
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
- packages/jsapi-utils/src/formatters/TableColumnFormatter.ts
Context menu Broken in PR #693. Handle context menu needs a ? before getMenu. 
Also fixes #647 remove assert not null, getColumnFormat can return null, accept null the jsdoc comments already say null is allowed.
> Fix broken contextmenu handler again.

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/dashboard-core-plugins/src/panels/PandasPanel.tsx
Fixes error with pandas panel not loading props from store
```
TypeError: Cannot read properties of undefined (reading 'permissions')
IrisGridPanel.render
src/panels/IrisGridPanel.tsx:1207
1204 | const childrenContent =
1205 |   children ??
1206 |   this.getPluginContent(Plugin, model, user, workspace, pluginState);
> 1207 | const { permissions } = user;
| ^  1208 | const { canCopy, canDownloadCsv } = permissions;
1209 | const formattedRowCount = model?.displayString(
1210 |   model?.rowCount ?? 0,
```
> Fix missing props in pandas panel by using correct import

- packages/iris-grid/src/AdvancedFilterCreator.tsx
- packages/iris-grid/src/AdvancedFilterCreatorFilterItem.scss
- packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/jsapi-utils/src/TableUtils.test.ts
- packages/jsapi-utils/src/TableUtils.ts
- Show validation error when error making quick filter (was broken)
- Allow `null` in Advanced Filters, ranged char filters
- Add validation error for advanced filter values
Tested with the null and random values table, testing both quick and advanced filters, valid and invalid values, and range filters on char columns from both quick and advanced filters:
```
from deephaven import empty_table, time_table
simple_ticking = time_table("00:00:01").update([
"MyString=new String(`a`+i)",
"MyInt=new Integer(i)",
"MyLong=new Long(i)",
"MyDouble=new Double(i+i/10)",
"MyFloat=new Float(i+i/10)",
"MyBoolean=new Boolean(i%2==0)",
"MyChar= new Character((char) ((i%26)+97))",
"MyShort=new Short(Integer.toString(i%32767))",
"MyByte= new java.lang.Byte(Integer.toString(i%127))"])
complex_ticking = …
```
> DH-13043 Filter validation fixes and nulls in Advanced Filters

- lerna.json
- package-lock.json
- packages/babel-preset/package.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
- packages/eslint-config/package.json
- packages/file-explorer/package.json
- packages/filters/package.json
- packages/golden-layout/package.json
- packages/grid/package.json
- packages/icons/package.json
- packages/iris-grid/package.json
- packages/jsapi-shim/package.json
- packages/jsapi-utils/package.json
- packages/log/package.json
- packages/mocks/package.json
- packages/prettier-config/package.json
- packages/react-hooks/package.json
- packages/redux/package.json
- packages/storage/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
- packages/utils/package.json
* `code-studio`, `dashboard-core-plugins`, `embed-chart`, `embed-grid`, `jsapi-shim`, `redux`
* [#743](https://github.com/deephaven/web-client-ui/pull/743) Support for no console in the web UI ([@mofojed](https://github.com/mofojed))
* `babel-preset`, `code-studio`, `components`, `console`, `dashboard-core-plugins`, `dashboard`, `embed-chart`, `embed-grid`, `file-explorer`, `icons`, `iris-grid`, `jsapi-shim`, `redux`, `utils`
* [#711](https://github.com/deephaven/web-client-ui/pull/711) Change build system to Vite ([@mattrunyon](https://github.com/mattrunyon))
* `components`
* [#753](https://github.com/deephaven/web-client-ui/pull/753) Cherry-pick #744 Editable Item List  ([@vbabich](https://github.com/vbabich))
* `file-explorer`
* …
> Version Bump v0.17.0

- package-lock.json
- packages/grid/package.json
- packages/grid/src/GridRenderer.ts
- packages/grid/src/GridTheme.ts
- packages/grid/tsconfig.json
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridTheme.module.scss
- packages/iris-grid/src/IrisGridTheme.ts
Fixes an issue where if a light colored background was used in a column header group, the text was white and not easily readable.
Grid doesn't rely on any deephaven packages (except utils now), so it has no concept of deephaven theme. Could switch to have a `white` and `black` values in the grid theme if that's preferred
Example Python snippet
```python
from deephaven.column import string_col, char_col, int_col
groups = [
{'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3'], 'color': 'yellow'},
{'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'}
]
table = new_table([
string_col("Short", ["A" , "B", "C", "D"]),
char_col("Char", "ABCD"),
int_col("Int", [123456789, 234567890, 42, 8675309]),
string_col("Short2", ["A" , "B", "C", "D"]), …
```
> Switch column header group text to dark if background is light

- package-lock.json
- Now the only audit warning is from jszip, which is a ticket #547
> Run `npm audit fix` to update package dependencies

- package-lock.json
- packages/components/package.json
Resolves issue with color adjust warning. Smoke tested style guide, and UI.
https://github.com/twbs/bootstrap/releases/tag/v4.6.2
> We've replaced the deprecated color-adjust with print-color-adjust in our Sass files as part of the Autoprefixer v10.4.6 issues. This should quiet the issues folks have seen from that dependency change. If you're using our distribution CSS files, like bootstrap.min.css, you may still see the warning.
> Upgrade to bootstrap 4.6.2

- package-lock.json
- packages/console/package.json
- packages/console/src/monaco/MonacoUtils.ts
- packages/iris-grid/package.json
- Fixes #773  being unable to escape the suggestion widget
- I don't know what change introduced the issue, as it's not reproducible in v0.34.0 playground and it's just in our code for some reason
I went down a rabbit hole debugging this...
The issue is that container is null when initializing the suggest widget contextview: https://github.com/microsoft/vscode/blob/0c22a33a9d670a84309447b36abdbd8c04ee6219/src/vs/base/browser/ui/contextview/contextview.ts#L162
Because it is null, this listener never gets registered: https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/contextview/contextview.ts#L183
Subsequently, this.hide() never gets called: https://github.com/microsoft/vscode/blob/0c22a33a9d670a84309447b36abdbd8c04ee6219/src/vs/base/browser/ui/contextview/contextview.ts#L …
> Downgrading monaco-editor to v0.31.1

- lerna.json
- package-lock.json
- packages/babel-preset/package.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
- packages/eslint-config/package.json
- packages/file-explorer/package.json
- packages/filters/package.json
- packages/golden-layout/package.json
- packages/grid/package.json
- packages/icons/package.json
- packages/iris-grid/package.json
- packages/jsapi-components/package.json
- packages/jsapi-shim/package.json
- packages/jsapi-utils/package.json
- packages/log/package.json
- packages/mocks/package.json
- packages/prettier-config/package.json
- packages/react-hooks/package.json
- packages/redux/package.json
- packages/storage/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
- packages/utils/package.json
* `code-studio`, `dashboard-core-plugins`, `file-explorer`
* [#782](https://github.com/deephaven/web-client-ui/pull/782) File explorer path and display initializes from focused dir/file instead of root ([@jason-wang24](https://github.com/jason-wang24))
* `collapseAll()` has been added as a method to `FileStorageTable` in `FileStorage.ts` so all implementations of `FileStorageTable` will need to be updated.
* `code-studio`, `dashboard-core-plugins`, `file-explorer`
* [#782](https://github.com/deephaven/web-client-ui/pull/782) File explorer path and display initializes from focused dir/file instead of root ([@jason-wang24](https://github.com/jason-wang24))
* `code-studio`, `file-explorer`, `jsapi-shim`
* [#787](https://github.com/deephaven/web-client-ui/pull/787) gRPC file storage …
> Version Bump v0.19.0

- codecov.yml
- Previously required each change to increase test code coverage, which is unrealistic for a lot of bug fixes
- Change the treshold to 1% so bug fixes can go in without needed to increase the threshold, but bigger features should still trigger it
> Allow up to 1% drop in code coverage per commit

- packages/dashboard-core-plugins/src/ConsolePlugin.tsx
- Properly add the notebooksUrl to hydrated NotebookPanels
- Fixes #800
Previously, NotebookPanel had a default prop being set for notebooksUrl. We removed that after changing build system to Vite (which was correct). However, we never added a hydrate function to properly add the `notebooksUrl` prop to `NotebookPanel`s when they were rehydrated. We passed it in correctly when `selectNotebook` or `createNotebook` was called, but not in `NotebookPanel` hydration (which just used the default hydration).
The only place `notebooksUrl` is used is in markdown notebooks that have links in them, so this problem did not manifest for regular notebooks.
> Add NotebookPanel hydration function

- packages/components/src/Button.tsx
Resolves #798
Re-uses tooltip as aria-label for iconOnly buttons that don't have a defined aria-label. If tooltip is a jsx element require a aria-label to be set with typescript.
> Set aria-label for icon only buttons

- .github/workflows/publish-nightly.yml
- set-output is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update to use new $GITHUB_OUTPUT instead of set-output

- packages/code-studio/src/main/AppInit.tsx
- Often we get a copy of the log or a screenshot of the log the rest of the Support Logs zip (which has this information in it)
- Sometimes the app crashes and the settings menu is inaccessible, so you cannot click the Export Support Logs button
- Log the version and user agent so we have more info for debugging
> Print app information to the log

- packages/chart/src/FigureChartModel.ts
- packages/code-studio/src/storage/grpc/GrpcFileStorageTable.test.ts
- packages/code-studio/src/storage/grpc/GrpcFileStorageTable.ts
- packages/dashboard-core-plugins/src/panels/FileExplorerPanel.test.tsx
- packages/file-explorer/src/FileStorage.ts
- packages/file-explorer/src/NewItemModal.tsx
Fixes #790 
- added Tooltip to NewItemModal home button and renamed aria-label to uppercase "Home"
- refactored GrpcFileStorageTable and added timers to its test file
The `setExpanded()` and `collapseAll()` methods in the `FileStorageTable` interface in `FileStorage.ts` have changed (they now return `void` instead of `Promise<void>`).
> 790 file explorer render fail

- tsconfig.json
This should not have been changed in the strict-boolean-expressions change. It adds <5% time to type generation and we weren't running into any issues with it before.
The reason I think it got enabled was because vite types were added globally, which is also incorrect. The vite types are added in `code-studio` and the embed packages only. With vite types globally, other packages could use `import.meta..env.VITE_ENV_VARIABLE` and TS would be fine with it.
> Re-enable strictLibCheck

- packages/components/src/context-actions/ContextActionUtils.ts
- packages/components/src/context-actions/ContextActions.tsx
Fixes #829 
- Added keyHandlers to support shortcuts but could be overly complex because it does not use the fact that these actions are `contextActions`
- Does not have support for `discard` or `commit` yet
> Fix keyboard shortcuts not working in Grid

- packages/grid/src/Grid.tsx
**Bug**
The context menu was not showing when right clicking the table or column headers. 
**Fix**
The bug was in `Grid`s `handleContextMenu` method, where the if statement checked whether the `EventHandlerResult` (due to a mouse event) was not `null`. Rather, the result should've been compared to `false` because `EventHandlerResult` can return a boolean or undefined.
> Fix context menu not showing on Grid

- lerna.json
- package-lock.json
- packages/babel-preset/package.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
- packages/eslint-config/package.json
- packages/file-explorer/package.json
- packages/filters/package.json
- packages/golden-layout/package.json
- packages/grid/package.json
- packages/icons/package.json
- packages/iris-grid/package.json
- packages/jsapi-components/package.json
- packages/jsapi-shim/package.json
- packages/jsapi-utils/package.json
- packages/log/package.json
- packages/mocks/package.json
- packages/prettier-config/package.json
- packages/react-hooks/package.json
- packages/redux/package.json
- packages/storage/package.json
- packages/stylelint-config/package.json
- packages/tsconfig/package.json
- packages/utils/package.json
* `code-studio`, `dashboard-core-plugins`, `dashboard`, `golden-layout`, `mocks`
* [#796](https://github.com/deephaven/web-client-ui/pull/796) Convert golden-layout to TypeScript ([@mattrunyon](https://github.com/mattrunyon))
1. Some golden-layout component configs need to assert their type param if it is a separate variable. The type on config was narrowed from `string` to a union of the available types.
* Before: `const config = { type: 'stack', ... };`
* After: `const config = { type: 'stack' as const, ... };`
2. Some types will need to be modified as the `GoldenLayout` namespace type no longer exists. The types from the old namespace can be imported as named imports such as `import type { ContentItem } from '@deehpaven/golden-layout';`
* Before: `item: GoldenLayout.ContentItem`
* …
> Version Bump v0.20.0

- packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
**Bug**
Newly created notebooks don't save properly after clicking the save button.
1. Go to File Explorer and click the 'New Notebook' button
2. Type something into the notebook
3. Click the save button 
4. Rename the notebook 
5. Click save
**Expected**
The blue dot indicating unsaved modifications were made to the file disappears. The tooltip when hovering over the file tab now shows the new file name. Clicking the close button of the file tab does not make the 'Do you want to save changes' modal to open.
**Actual**
The blue dot remains. The tooltip still shows 'untitled-x.py' even though the file has been renamed. Closing the file tab makes the 'Do you want to save changes' modal appear.
**Fix**
The `GrpcFileStorage` was updated in #810 where the `refresh()` method no longer returns a …
> Fix new notebooks not saving when first created

- packages/jsapi-shim/src/dh.types.ts
the function `close` was missing in type `IdeSession`.
> Added function `close` to `interface IdeSession` in `dh.type`

- packages/components/.gitignore
- packages/components/package.json
- packages/components/scss/BaseStyleSheet.scss
- packages/components/scss/custom.scss
- packages/components/scss/custom_vite.scss
- packages/console/src/index.ts
- packages/iris-grid/src/index.ts
- packages/iris-grid/src/sidebar/index.ts
- packages/jsapi-shim/src/index.ts
This will allow us to move DHE to the latest DHC and also switch to Vite.
The exported items were being imported from DHE as `import { item } from @deephaven/package/dist/item` which is bad.
The sass for BaseStyleSheet is not built any more, but DHE can import the sass file since it is published instead of the built css
> Add missing exports and fix CSS for DHE

- packages/components/src/ItemList.scss
- packages/components/src/ItemList.tsx
- packages/console/src/command-history/CommandHistory.tsx
- packages/dashboard-core-plugins/src/panels/CommandHistoryPanel.tsx
Resolves #859
- Use initialScrollOffset prop to set initial position instead of scrolling to bottom in did mount (which doesn't work when in a backgrounded tab)
- forceUpdate the virtualized list when it is picked up and dropped in the same place
> Fixes command history not scrolled to bottom on load

- packages/golden-layout/src/controls/DragProxy.ts
- packages/golden-layout/src/utils/DragListener.ts
- TouchEvent is not always available on desktop machines: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#example
--> It's not defined at all on FireFox desktop or Safari Desktop
- We could use PointerEvents to support both mouse and touch events better: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
--> However, we don't really support touch anyway with Golden-layout, and we probably want to build in intentional support rather than this which has been left behind
> Remove reference to TouchEvent

- packages/components/src/EditableItemList.test.tsx
- packages/components/src/EditableItemList.tsx
- packages/utils/src/RangeUtils.test.ts
- packages/utils/src/RangeUtils.ts
EditableItemList was using wrong event for tracking selection.
- Changed `onSelect` to `onSelectionChange`
- Also changed the list to multiselect, as suggested by QA
Breaking change: `onDelete` is now triggered with array of values instead of a single value
> Fix EditableItemList selection, change to multiselect

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGridUtils.ts
Fixes #897 
This will also merge the saved settings over the default settings if we were to add another advanced setting. It will not purge settings if they're removed, but we have 2 advanced settings and not sure we'll remove any anytime soon.
Enterprise has been updated in the silverheels Vite PR to get advancedSettings from the dehydrated panel state instead of iris grid state. Iris grid doesn't track the settings, the panel does.
> Persist iris grid advanced settings

- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
- packages/iris-grid/src/IrisGrid.test.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/jsapi-utils/src/TableUtils.ts
- Pass `isGrouped` and `isExpandable` flags in selected data in addition to column type, text, and value
- Clear quick filters when applying links on columns with `undefined` value
- Fixes #875
> Fix null in links on grouped columns

- packages/code-studio/src/main/AppInit.tsx
- Allows the server to pass values for canCopy and canDownloadCsv
- Defaults to true if no server values are passed in
- Fixes #703 
Manually tested for three scenarios:
1. server values of canCopy and canDownloadCsv being false
2. server values of canCopy and canDownloadCsv being true
3. server does not provide values for canCopy and canDownloadCsv
Usage:
docker-compose.yml:
```
version: "3.4"
services:
deephaven:
image: ghcr.io/deephaven/server:latest
ports:
- "${DEEPHAVEN_PORT:-10000}:10000"
volumes:
- ./data:/data
- ./deephaven.prop:/opt/deephaven/config/deephaven.prop:ro
environment:
- START_OPTS=-Xmx4g
```
deephaven.prop:
```
includefiles=dh-defaults.prop
internal.webClient.appInit.canCopy=false
internal.webClient.appInit.canDownloadCsv=false …
```
> Added support for canCopy and canDownloadCsv server properties

- packages/code-studio/src/main/AppMainContainer.jsx
- packages/grid/src/key-handlers/SelectionKeyHandler.ts
* Resolves #663 by copying enterprise fix DH-12258. Removes dead code.
* Fix shortcut broken by #203 Separating dashboard into own package
* Cleanup hjkl shortcuts to not conflict with ctrl+L for linker
* add shift key support
> Fix broken ctrl+e to clear filters shortcut (#664)

- packages/grid/src/key-handlers/SelectionKeyHandler.ts
Don't stop Esc event propagation in Grid so it could reach the global handler. Fixes #906.
> Fix Linker Esc shortcut

- packages/console/src/monaco/MonacoCompletionProvider.test.tsx
- packages/console/src/monaco/MonacoCompletionProvider.tsx
> Make MonacoCompletionProvider supply the version for textDocument (#909)

- .github/workflows/cla.yml
- .github/workflows/create-release.yml
- .github/workflows/label-check-ci.yml
- .github/workflows/node.js.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
Fixes #824
The breaking change between 2 and 3 is the removal of node 12, I didn't see any other relevant release notes.
> Update github action versions to remove node 12 warning

- packages/console/src/Console.test.tsx
- MonacoTheme['line-height'] is NaN when running tests, as scss is mocked out in tests
- Just mock out MonacoTheme to include a value for line-height.
Tested by running `npm test`, then press `p` to filter and enter `Console.test`
Previous this console.error was printed out. The test passed, but it had an error in the logs:
```
PASS   @deephaven/console  packages/console/src/Console.test.tsx
● Console
console.error
Warning: `NaN` is an invalid value for the `height` css style property.
at div
at div
at div
at ConsoleInput (/home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/console/src/ConsoleInput.tsx:59:41)
at div
at div
at Console (/home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/console/src/Console.tsx:148:36)
```
Now the test just passes.
> Fix console error that is logged about NaN when running tests

- packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx
- packages/iris-grid/src/ColumnStatistics.tsx
- We fudge the `rowCount` when using InputTables to make the infinite scrolling input table effect. Displaying this `rowCount` was confusing to the user, as that's not the actual size of the table.
- Don't include the pending row count in tooltips when displaying row count. 
- Fixes #889
> Subtract the pending row count when displaying row count

- lerna.json
- package-lock.json
- packages/code-studio/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
- packages/file-explorer/package.json
- packages/grid/package.json
- packages/iris-grid/package.json
- packages/jsapi-components/package.json
- packages/pouch-storage/package.json
* `code-studio`
* [#904](https://github.com/deephaven/web-client-ui/pull/904) Added support for canCopy and canDownloadCsv server properties ([@Zhou-Ziheng](https://github.com/Zhou-Ziheng))
* `dashboard-core-plugins`, `iris-grid`
* [#916](https://github.com/deephaven/web-client-ui/pull/916) Subtract the pending row count when displaying row count ([@mofojed](https://github.com/mofojed))
* `console`
* [#911](https://github.com/deephaven/web-client-ui/pull/911) Fix console error that is logged about NaN when running tests ([@mofojed](https://github.com/mofojed))
* [#918](https://github.com/deephaven/web-client-ui/pull/918) Don't trigger autocomplete when running code from notebook ([@mofojed](https://github.com/mofojed))
* `grid`
* [#907](https://github.com/deephaven/web-client-ui/pull/907) …
> Version Bump v0.22.2

- packages/code-studio/src/main/AppInit.tsx
- While looking through logs reported from a user, the error printed out was just `[AppInit] Connection failure Object`. Stringify it so we may have at least a bit more detail.
> Stringify the error details before outputting to console

- lerna.json
- package-lock.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/embed-grid/package.json
- packages/grid/package.json
- packages/iris-grid/package.json
- packages/jsapi-components/package.json
- packages/jsapi-utils/package.json
- packages/redux/package.json
* `grid`
* [#917](https://github.com/deephaven/web-client-ui/pull/917) Fix Linker Esc shortcut (#907) ([@vbabich](https://github.com/vbabich))
* `code-studio`, `grid`
* [#905](https://github.com/deephaven/web-client-ui/pull/905) Fix broken ctrl+e to clear filters shortcut (#664) ([@vbabich](https://github.com/vbabich))
* `dashboard-core-plugins`, `iris-grid`, `jsapi-utils`
* [#900](https://github.com/deephaven/web-client-ui/pull/900) Fix null in links on grouped columns (#892) ([@vbabich](https://github.com/vbabich))
- Vlad Babich ([@vbabich](https://github.com/vbabich))
> Version bump 0.13.10

- packages/chart/src/Chart.scss
- packages/chart/src/ChartTheme.module.scss
- packages/code-studio/src/settings/SettingsMenu.scss
- packages/components/scss/BaseStyleSheet.scss
- packages/components/scss/bootstrap_overrides.scss
- packages/components/src/ThemeExport.module.scss
- packages/console/src/command-history/CommandHistoryItem.scss
- packages/console/src/log/LogLevelMenuItem.scss
- packages/console/src/monaco/MonacoTheme.module.scss
- packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.scss
- packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.scss
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.scss
- packages/dashboard-core-plugins/src/panels/FilterSetManager.scss
- packages/dashboard-core-plugins/src/panels/MarkdownNotebook.scss
- packages/dashboard-core-plugins/src/panels/NotebookPanel.scss
- packages/file-explorer/src/FileListItemEditor.scss
- packages/iris-grid/src/AdvancedFilterCreatorSelectValue.scss
- packages/iris-grid/src/IrisGrid.scss
- packages/iris-grid/src/IrisGridTheme.module.scss
- packages/iris-grid/src/PendingDataBottomBar.scss
Colors defined with `interface` prefix was intended for use within bootstrap overrides only.
Everywhere else should use either `$foreground`, `$background` or `$content-bg`. If the usage is not semantically relevant, then an explicit `$white` or `$black` is also acceptable.
This might be considered a breaking change as I also removed them from ThemeExport.
> Clean up non-semantic uses of defined colours

- packages/iris-grid/src/IrisGrid.tsx
- Instead of copying the numeric value in nanoseconds of the date, copy it as a full date string
- Tested with a date column, changing time zones, and copying values. The date was correct and time zone was included correctly. Also tested non-date columns still copied as intended.
- Fixes #919
> Copy unformatted cell for dates should copy full date string

- packages/code-studio/.env.development
- packages/code-studio/vite.config.ts
Proxy the websocket (and jsapi files) with the vite server. This is cool because it lets you open an ngrok tunnel to just port 4000 and have everything work.
> Proxy the ws socket within vite to allow tunneling

- packages/grid/src/Grid.tsx
- packages/grid/src/GridMetricCalculator.ts
- packages/iris-grid/src/IrisGrid.tsx
Fixes #581 
@mofojed why does lastTop take into account floating rows but lastLeft doesn't? Noticed, because lastTop was not taking into account floating top rows.
> Fixes Grid isStuckToBottom prop doesn't work correctly on mount if rowCount doesn't increase

- .browserslistrc
- packages/code-studio/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
- Just use the latest defaults specified with browserslist instead of our own list
- Use a root `.browserlistrc` file instead of specifying it in package.json
- Fixes #658
> Update browserslist to latest defaults

- packages/code-studio/src/main/UserLayoutUtils.ts
> Reduce the console height to 40/60 split in the default layout

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/TableCsvExporter.scss
- packages/iris-grid/src/sidebar/TableCsvExporter.tsx
- packages/iris-grid/src/sidebar/TableSaver.tsx
Fixes #938 
- Added checkboxes for the 3 options and their respective state in TableCsvExporter
- Added simple conditionals to TableSaver for hidden columns and header exporting
- Used `toString()` on raw cell value for unformatted option with separate `Date` type formatting
> Add Download CSV options for hidden columns, headers and formatting

- packages/embed-grid/src/App.tsx
- packages/jsapi-utils/src/ConnectionUtils.test.ts
- packages/jsapi-utils/src/ConnectionUtils.ts
- packages/jsapi-utils/src/index.ts
- Pass in an optional `type` parameter that specifies the variable type
- No need for reload button in this case/marking it like a pandas dataframe like we do in panels, just use the browser refresh
- Preparation for https://github.com/deephaven/deephaven-ipywidgets/issues/4 (which I'll get Joseph to do)
Tested by executing the following code:
```
import pandas as pd
data_frame = pd.DataFrame(
{'A': [1, 2, 3],
'B': ['X', 'Y', 'Z']}
)
t = empty_table(100).update("x=i")
```
Then navigated to the following two addresses, made sure they both appeared correctly:
http://localhost:4010/?name=data_frame
http://localhost:4010/?name=t
> Allow embed-grid to open pandas dataframes

- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
- Now packages will be published as `deephaven-bot` instead of `mikebender`
- `DEEPHAVENBOT_NPM_TOKEN` is an organization secret
- I kicked off an alpha build to test: https://github.com/deephaven/web-client-ui/actions/runs/3690219087
> Change publish tokens to deephaven-bot

- packages/console/src/monaco/MonacoUtils.ts
Fixes #953
Firefox was injecting non-breaking spaces based on CSS style on copy, replace them with regular spaces onDidPaste
> Replace non-breaking spaces pasted into monaco editors

- packages/console/src/notebook/ScriptEditor.tsx
- Server doesn't like it when we close a document without opening it beforehand. Will want to handle that error more gracefully.
- Fixes #969
> Only close documents that have been opened

- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- Fix linker spamming errors
- Add listener for `PanelEvent.CLOSE` because we originally only listened to `PanelEvent.CLOSED` and it does not emit every time we need it to
- Change linker dialog text to reflect the ability to change comparison operator and new ways to delete links. Feel free to make it better
- `Delete` key now deletes the selected link, if any. Currently, this is event.key or event.code `Delete` and not `Backspace`. I know on mac keyboards the key labelled delete is actually backspace, which currently shouldn't work. Open to discussion
> Fix linker spamming errors, change linker dialog text, add delete key to delete selected links

- packages/dashboard-core-plugins/src/linker/Linker.tsx
Fixes #971 
- Set `linkInProgress` to undefined and `selectedIDs` to an empty set when `activeTool` is set to default 
- Remove unnecessary setStates based on above change
> Fix closing linker using shortcut not resetting state

- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- packages/dashboard/src/DashboardLayout.tsx
- packages/dashboard/src/PanelEvent.ts
Fixes #964 
- Added `PanelEvent.DRAGGING` and `PanelEvent.DROPPED` events and `isDraggingPanel` state to `Linker.tsx`. isDraggingPanel is set to false if the panel being dragged has a link starting or ending in that panel and set back to true when the panel is dropped.
- Perhaps we can also reopen the linker overlay when the panel is dropped (this would require adding a new event but is otherwise trivial)
> Fix weird UI when dragging a panel with linker overlay open

- packages/console/src/Console.tsx
- tests/console.spec.ts
- tests/table.spec.ts
- tests/utils.ts
- We were mutating objects within the state, violating the immutability principle.
- Clone any object that we were mutating.
- Cleaned up some of the code.
- All tests pass
- Tested by running the steps in the description of #928, also tested importing a CSV and giving it the same name as a prior object. Old objects were updated correctly.
- Updated e2e tests:
- Refactored creating a table command into it's own function
- Fixed up old print commands tests - wasn't verifying the result correctly
- Added test to check that an object button was created when creating a table, and that the old button was disabled when re-running the same command twice
- Fixes #928 
- Fixes [DH-13988](https://deephaven.atlassian.net/browse/DH-13988)
> DH-13988 Fix issue with old buttons not getting disabled in console history

- packages/components/scss/BaseStyleSheet.scss
- packages/components/src/popper/Popper.tsx
- packages/components/src/popper/Tooltip.tsx
- packages/console/src/ConsoleMenu.tsx
- packages/dashboard-core-plugins/src/panels/RenameDialog.tsx
- packages/file-explorer/src/FileList.tsx
Fixes #966
- Sets tooltip placement to bottom by default. Tooltips belong below by convention and not just the side with the most space. 
- Sets boundaries element to viewport by default on popper, instead of scroll parent. We want to allow poppers to escape their panel/scroll parent in almost all cases.
Testing: tried all the tooltips I could find in community, some have new positioning, but it's all fine.
> Change tooltip default placement to bottom instead of auto

- packages/components/src/BasicModal.test.tsx
- packages/components/src/BasicModal.tsx
- Replace inline function in the `Modal` `onOpened` prop with a `useCallback` to prevent re-focusing default button on each `BasicModal` render
- Unit tests
- Fixes #792
> Fix default button focusing on BasicModal re-render

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/grid/src/Grid.tsx
- packages/grid/src/GridMetricCalculator.ts
- packages/grid/src/GridMetrics.ts
- packages/grid/src/GridRenderer.ts
- packages/grid/src/GridUtils.ts
- packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
- packages/grid/src/mouse-handlers/GridHorizontalScrollBarMouseHandler.ts
- packages/grid/src/mouse-handlers/GridRowMoveMouseHandler.ts
- packages/grid/src/mouse-handlers/GridRowTreeMouseHandler.ts
- packages/grid/src/mouse-handlers/GridVerticalScrollBarMouseHandler.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridRenderer.ts
Fixes #316 
This also should make the fix for #936 less hacky
I refactored all uses of `visible` to the `all` versions since the metrics were really exporting `all`. Then added back the `visible` versions of the metrics. The only actual uses of the `visible` metrics should be in `getMetrics` between where the `visible` is created and the `all` version is created. Previously the `visible` version was modified where `all` is created, so any uses of `visible` below it are really uses of `all`.
> Add all and visible maps for row/column size/position

- packages/grid/src/Grid.tsx
- packages/grid/src/GridRenderer.ts
Fixes #936 
Also removed `left` and `top` from the render state passed to the render function. They aren't used and should be retrieved from metrics instead.
I have a version of this which instead updates `left` and `top` in the metric calculator instead of updating the grid state after metrics if that is preferred (relies on #997). In that case we would probably still want to update the state in Grid since a few handlers in Grid use that state.
> Fix cannot scroll left after marking columns as hidden

- packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
Fixes #956 
When saving a notebook with a duplicate name, it will ask you if you want to overwrite.
> Fix silent error when saving notebook with duplicate name

- packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/TreeItem.scss
The negative margin was looking weird with the transparency overlapping creating a darker border, give the items a 1px bottom margin to create a small gap between items, then remove that gap on the depth lines with negative margin so they are still continuous.
> Adjust margin in column header grouping list

- CONTRIBUTING.md
- packages/chart/src/Chart.scss
Fixes https://github.com/deephaven/web-client-ui/issues/1009 
Hello! :wave: @mattrunyon & @dsmmcken 
I'm trying to get more into my open source contributions and came across this project.   I saw this issue and it is listed as `bug` and `good first issue` so I decided to give it a shot.
Just as I was prepping this PR did I notice that [Don opened up a PR that made some improvements with the toast stuff](https://github.com/deephaven/web-client-ui/pull/1010). Hopefully this fixes the issue that Matthew identified and we can use Don's changes in conjunction. 
Fixed the toast issue wrapping issue in Chrome.  
Manually tested clicking the "Download as Png" in Chrome.  Looks good.
> [Fix] Toast Wrapping with Overridden Plotly Styles

- packages/dashboard-core-plugins/src/panels/ChartPanel.test.tsx
- packages/utils/src/PromiseUtils.ts
Fixes #949 
When the cancel function is called on a cancellablePromise, the wrapper promise immediately rejects.
> Cancelled promises reject immediately

- packages/iris-grid/src/IrisGridTreeTableModel.ts
- packages/jsapi-shim/src/dh.types.ts
- We didn't wire it up for some reason. It is now implemented on the core side.
- Used Colin's branch to test: `1763-js-hierarchical-tables`
- Tested with the following snippet in Groovy. Was able to filter the grouped column `J`, but not the column `I`.
```
t = emptyTable(100).update("I=i", "J = `` + (int)(i/10)")
h = t.rollup([io.deephaven.api.agg.Aggregation.of(io.deephaven.api.agg.spec.AggSpec.sum(), "I")], "J")
```
> Fix up groupedColumns in TreeTables

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
Fixes #990 
Allow only pendingRow changes if there are no key columns.
> Existing rows in append-only tables cannot be edited

- packages/iris-grid/src/IrisGridCellOverflowModal.tsx
Fixes #834 
Set the height when the editor is initialized.
> Fix cell overflow viewer with browser zoom

- .github/workflows/e2e.yml
The latest `edge` release may have functionality we need for e2e testing. By using the latest `edge` as well we can pick up on issues in deephaven-core earlier.
> Update e2e tests to use the latest `edge` release

- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Fixes #1003 
Also disables freeze column entry if the column is in a group because that breaks current behavior (groups can't contain frozen columns and must be contiguous)
> Fix freeze column from context menu

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/CustomColumnBuilder.test.tsx
- packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
- packages/iris-grid/src/sidebar/CustomColumnInput.test.tsx
- packages/iris-grid/src/sidebar/CustomColumnInput.tsx
- packages/iris-grid/src/sidebar/InputEditor.tsx
Fixes #939 
Does not validate that the names aren't duplicates of existing column names, only of existing custom columns. The API seems to allow custom columns that overwrite an existing column name. For example, table with coiumns `A, B, C`. Create a custom column `A=C` and `B=A`. All of the columns will display column `C`. If you swap the order of the custom columns, then `B` will show the original `A` and `A` will show `C`.
The API does not allow invalid custom column names (table column validation) or duplicate custom column names.
> Validate custom column names

- packages/code-studio/src/main/AppInit.tsx
- packages/code-studio/src/main/SessionUtils.ts
- packages/jsapi-shim/src/dh.types.ts
- Check query params for the `authRequired` flag
- if flag present, send auth request to the parent window, wait for response with the auth token
- authenticate using the received token
> Add optional worker authentication

- packages/dashboard-core-plugins/src/ConsolePlugin.tsx
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- packages/dashboard/src/layout/LayoutUtils.ts
- packages/file-explorer/src/NewItemModal.tsx
- packages/golden-layout/src/container/ItemContainer.ts
- packages/golden-layout/src/container/index.ts
Fixes #1017 
Overwritten tabs are now closed upon confirming the overwrite modal.
> Overwriting file keeps old tab open with old contents

- packages/code-studio/src/main/AppMainContainer.tsx
Fixes #1050 
Don't think I can add a test easily since paste events were giving trouble in e2e tests and monaco doesn't play nicely w/ unit tests
> fix: Pasting with smart quotes causes double paste in monaco

- packages/grid/src/GridMetricCalculator.ts
- packages/grid/src/mouse-handlers/GridColumnSeparatorMouseHandler.ts
- packages/grid/src/mouse-handlers/GridRowSeparatorMouseHandler.ts
- packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridMetricCalculator.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/sortable-tree/utilities.ts
Fixes #1038, Fixes #526
Also fixes an undocumented issue where reset in the column visibility sidebar would not reset frozen columns to their initial state. Now the reset button from the visibility and ordering menu will reset frozen columns as well. Basically resetting to the initial state from the query.
> Fix resizing/hiding layout hint hidden columns. Fix resetting layout hints

- .github/workflows/conventional-pr-check.yml
- We use the job id `pr-check` as the required status
- Workflow name is already defined as `Conventional PR`
> build: Remove the "Validate PR title" name from the job

- packages/console/src/Console.test.tsx
- packages/console/src/ConsoleInput.tsx
Fixes DH-14237
Was incorrectly converted in #646 
Switched the arrow keys to use `code` instead of `keyCode` because RTL user-event does not set `keyCode` which is a deprecated property
> fix: DH-14237: down arrow in console not returning to blank field

- packages/golden-layout/src/items/Stack.ts
Enterprise uses golden-layout hasHeaders: false in layout config for query monitor. A check  added as part of typescript conversion was preventing headers from being set to display none when it was false (toggle is a jquery method that hides/shows based on a boolean).
> fix: DH-14240 hasHeaders false should hide header bar

- packages/iris-grid/src/IrisGridProxyModel.ts
> fix: add missing return for editvalueforcell, missing from TS conversion

- packages/components/src/ItemList.tsx
Fixes #1085 
- isDragging was always set to true on itemMouseMove which prevented onSelect from firing on even the slightest of mouse movements while clicking
- Set isDragging to true only if the mouse moves at least 5 viewport units in the X or Y direction between the mouseDown and mouseUp events (attempted to get this value as close as possible to when the UI changes to indicate dragging)
> fix: Clicking a folder in file explorer panel sometimes fails to open or close it

- packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.test.ts
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
Conditional formatting for date columns now properly prevents conditions with empty values from being applied.
> fix: Conditional date formatting

- packages/iris-grid/src/sidebar/conditional-formatting/ColumnFormatEditor.tsx
> fix: Disable applying "No formatting"

- packages/utils/src/Asserts.test.ts
- packages/utils/src/ClipboardUtils.test.ts
- packages/utils/src/ColorUtils.test.ts
- packages/utils/src/EventTargetShimUtils.test.ts
- packages/utils/src/InvalidMetadataError.test.ts
- packages/utils/src/PromiseUtils.test.ts
- packages/utils/src/RangeUtils.test.ts
- packages/utils/src/TestUtils.test.tsx
- packages/utils/src/TestUtils.ts
- packages/utils/src/TimeoutError.test.ts
- packages/utils/src/ValidationError.test.ts
Closes #1089 
Increase code coverage in package utils.
> test: Increase code coverage in package utils

- packages/components/src/BasicModal.test.tsx
- packages/components/src/BasicModal.tsx
> feat: isConfirmDangerProp

- packages/jsapi-utils/src/TableUtils.ts
deephaven/deephaven-core#3385 is a port of DH-11692 which adds `Instant` and `ZonedDateTime` support to the engine. I've similarly encoded these types over Barrage as a `long` (as a nanosecond since epoch). The encoding of Zones will actually need to be implemented at a future date as the best implementation requires (encourages?) a much larger refactoring of ColumnSource types. See deephaven/deephaven-core#3455 for more information.
I was able to get the web-client-ui to display these types with this small patch.
> feat: Instants and ZonedDateTimes should be treated as DateTimes

- jest.config.base.cjs
- package-lock.json
- package.json
- packages/chart/package.json
- packages/chart/src/ChartUtils.ts
- The only vulnerability left is in jszip, which we still have pinned
> build: Update versions of some dependencies with vulnerabilities

- packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
- packages/code-studio/src/settings/FormattingSectionContent.tsx
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/code-studio/src/settings/ShortcutsSectionContent.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/AdvancedSettingsMenu.tsx
- packages/iris-grid/src/sidebar/RollupRows.tsx
- packages/iris-grid/src/sidebar/SelectDistinctBuilder.tsx
I asked chatGPT to help me brainstorm improvements to some of the labels and hint text based on the Apple Human Interface Guidelines. I then edited them as human to improve them further.
Review and let me know if you think any are worse or weird.
> feat: Improve text labels based on suggestions from chatGPT

- packages/iris-grid/src/GotoRow.scss
- packages/iris-grid/src/GotoRow.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
Fixes #1027 
- `null` values are not supported by the API, so it is not implemented
> feat: Goto Value Improvements

- packages/code-studio/src/AppRoot.tsx
- packages/code-studio/src/styleguide/StyleGuideRoot.tsx
- packages/code-studio/src/styleguide/index.html
- packages/code-studio/src/styleguide/index.tsx
- Styleguide index wasn't updated to use JS API as a module correctly
> fix: Fix the style guide

- packages/chart/src/ChartTestUtils.ts
- packages/chart/src/ChartUtils.test.ts
- packages/chart/src/ChartUtils.ts
- User is expecting the plots to be ordered 0 at top, increasing downward
- Plotlys bounds coordinate system has 0,0 in the bottom left, increasing upward
- Invert the coordinates so that it appears in plotly correctly
- Add unit tests
> fix: Ordering of subplots

- __mocks__/dh-core.js
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.test.ts
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
Added datetime string parsing / validation.
fixes #1108
> fix: Added date time parsing for conditional formatting

- packages/code-studio/src/remote-component.config.js
Allows plugins to connect to the store and to not have to bundle `react-dom`
> fix: Add react-dom, redux and react-redux to remote component dependencies

- packages/iris-grid/src/IrisGrid.tsx
- When there is a rollup config, aggregations go through the rollup config
- https://github.com/deephaven/web-client-ui/blob/a069543812b6c544957ebf664e0918e98a3affbf/packages/iris-grid/src/IrisGrid.tsx#L1288
- Allow aggregations to be accessed when using a rollup config
> fix: Aggregations should be available when creating a rollup

- .eslintignore
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridRenderer.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/jsapi-types/src/dh.types.ts
- packages/jsapi-utils/src/TableUtils.test.ts
- packages/jsapi-utils/src/TableUtils.ts
resolves #965
BREAKING CHANGE: Removed index property from dh.types Column type. IrisGridUtils.dehydrateSort now returns column name instead of index. TableUtils now expects column name instead of index for functions that don't have access to a columns array.
> refactor: Replace usage of Column.index with column name

- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingGroup.tsx
- Does not select new groups when searching
- Shows validation error if you create a new group and blur without typing anything into the name field
- Prevents Firefox on Mac from getting stuck in a bad state where color pickers can't be opened. The bug occurs when multiple color inputs are on the screen at once and the user clicks between the without closing the previous picker
> fix: DH-12163 - Column grouping sidebar test failure fixes

- packages/iris-grid/src/IrisGridRenderer.ts
> fix: Fixed rollup divider position

- packages/jsapi-utils/src/TableUtils.test.ts
- packages/jsapi-utils/src/TableUtils.ts
Allow null in match filters on string columns, treat it as a regular string value.
Run this query:
```
a = [None, 'Null', 'null - starts with', 'ends with null', 'null', 'ABC']
test_table = empty_table(6).update(formulas=["X = (String)a[i]"])
```
Filter using quick filters treating `null` as a string:
- `*null`, `=*null`, `!=*null` - ends with, does not end with
- `null*`, `=null*`, `!=null*` - starts with, does not start with
- `~null`, `!~null` - contains/does not contain
Special cases treating `null` as a `null` value:
- `=null`, `!=null`
> fix: DH-14439 Fix QueryMonitor breaking on "null" in default search filter

- .github/workflows/e2e.yml
- .github/workflows/unit.yml
This updates the actions to run on `release/` branches for PRs and pushes.
I believe this will need to be cherry-picked back to the release branches
The double star for the wildcard is from the GitHub docs [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters). Single star works as well, but would not run on `release/v0.19/something` if that ever occurred.
> ci: Update workflows to run on PRs and pushes to release branches

- packages/iris-grid/src/IrisGridRenderer.ts
- packages/iris-grid/src/mousehandlers/IrisGridColumnSelectMouseHandler.ts
Fixes #1146 
Changed `assertNotNull` to `getOrThrow` and update `hoverSelectColumn` on scroll so the highlighted column will change on scroll.
> fix: Scrolling horizontally in Linker mode renders empty cells

- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingGroup.tsx
- Does not select new groups when searching
- Shows validation error if you create a new group and blur without typing anything into the name field
- Prevents Firefox on Mac from getting stuck in a bad state where color pickers can't be opened. The bug occurs when multiple color inputs are on the screen at once and the user clicks between the without closing the previous picker
> fix: DH-12163 - Column grouping sidebar test failure fixes (cherry-pick)

- lerna.json
This should hopefully make the lerna publish command use the `v0.31` tag instead of `latest` when the publish action runs.
Will not prevent the GitHub release from being tagged latest. Didn't see any flags in lerna to create a GitHub release and not auto tag it as latest
> ci: Add dist-tag for publish

- packages/iris-grid/src/IrisGrid.test.tsx
- packages/iris-grid/src/IrisGrid.tsx
Added graceful handling to IrisGrid for tables with no columns.
fixes #1169
> fix: Handling no columns

- packages/iris-grid/src/IrisGridRenderer.ts
Fixes #1116 
Couldn't reproduce the bug but changed the code to return `NULL_POSITION` if any needed values are undefined instead of using `assertNotNull`.
> fix: Error thrown when cell overflow position is unknown

- packages/iris-grid/src/IrisGrid.test.tsx
- packages/iris-grid/src/IrisGrid.tsx
Cherry-pick #1170
Added graceful handling to IrisGrid for tables with no columns.
fixes #1169
> fix: DH-14436 Handling no columns (#1170)

- packages/iris-grid/src/IrisGrid.tsx
Fixes #1135 
Removed `getCachedModelColumns` and uses `model.columns` instead.
> fix: Conditional formatting not being applied to custom columns

- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Fixes #1065 
Context menu was being rendered but it was rendered based on the page x and y, so since you have to scroll to the bottom to see IrisGrid, the context menu was being rendered off the screen.
> fix: Context menu does not appear when right-clicking IrisGrid component in styleguide

- README.md
I use `upstream` for the Deephaven repo remote name, and others might too. Added the flag to the release instructions to set the remote.
> chore: Add git-remote flag to release instructions

- packages/golden-layout/src/controls/DragProxy.ts
- packages/grid/src/Grid.tsx
- When we drag something, there is a frame where the width/height is 0
- We didn't update the metrics within the actual animation frame, so it was drawing the wrong thing
- Fix so metrics are always updated in the animation frame, and also to only check the metrics with the previously checked metrics
- Tested with ticking tables stuck to the bottom to ensure they stuck while ticking
- Fixes #1112
> fix: Preview did not draw correctly when dragging Grids

- package-lock.json
- packages/iris-grid/package.json
- packages/iris-grid/src/sidebar/TableSaver.tsx
- packages/iris-grid/src/sidebar/WritableStream.ts
- Import in a different file and just export it
- Use implicit typing to work around the issue
- Fixes #803
> fix: Typing for WritableStream

- packages/dashboard-core-plugins/src/ConsolePlugin.tsx
- packages/dashboard-core-plugins/src/events/NotebookEvent.ts
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- packages/dashboard/src/layout/LayoutUtils.ts
> fix: Double clicking a file causes the loader to flash incorrectly

- __mocks__/dh-core.js
- packages/code-studio/src/storage/LocalWorkspaceStorage.ts
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.test.ts
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.test.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
- Issue with Formatting values - Enterprise uses `multiplier: null` for the default settings, but in Community we only expected `undefined` or `number`.
- Just handle when `multiplier` is `null` as well
- Fixes #1193
- Tested by manually adding a formatter with `multiplier: null` in LocalWorkspaceStorage, e.g.:
```
formatter: [
{
columnType: 'decimal',
columnName: 'Bid',
format: {
label: '',
type: 'type-global',
formatString: '###,##0.00###',
multiplier: null,
},
},
],
```
> fix: Fix column data appearing incorrectly when multiplier null

- __mocks__/dh-core.js
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.test.ts
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.test.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
- Cherry pick fix from main
- Issue with Formatting values - Enterprise uses `multiplier: null` for the default settings, but in Community we only expected `undefined` or `number`.
- Just handle when `multiplier` is `null` as well
- Fixes #1193
- Tested by manually adding a formatter with `multiplier: null` in LocalWorkspaceStorage, e.g.:
```
formatter: [
{
columnType: 'decimal',
columnName: 'Bid',
format: {
label: '',
type: 'type-global',
formatString: '###,##0.00###',
multiplier: null,
},
},
],
```
> fix: Fix column data appearing incorrectly when multiplier null (#1194)

- packages/code-studio/src/main/AppInit.tsx
- packages/redux/src/store.ts
> feat: Added isACLEditor prop to Redux state

- packages/utils/src/TypeUtils.test.ts
- packages/utils/src/TypeUtils.ts
> feat: Created ValueOf<T> util type

- .github/workflows/publish-alpha.yml
- Was defaulting to `latest`, which is incorrect
> build: Fix the dist-tag for canary builds

- packages/dashboard/src/DashboardPlugin.ts
- packages/dashboard/src/layout/index.ts
- packages/dashboard/src/layout/usePanelRegistration.test.tsx
- packages/dashboard/src/layout/usePanelRegistration.ts
> feat: usePanelRegistration hook

- package-lock.json
- packages/code-studio/src/main/AppInit.tsx
- packages/code-studio/src/main/SessionUtils.ts
- packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
- packages/dashboard-core-plugins/src/redux/actions.ts
- packages/jsapi-utils/package.json
- packages/jsapi-utils/src/MessageUtils.test.ts
- packages/jsapi-utils/src/MessageUtils.ts
- packages/jsapi-utils/src/index.ts
Get optional workerName and processInfoId along with the login options response from the DHE host, display in the console status bar.
> feat: Display workerName and processInfoId in the console status bar

- packages/chart/package.json
- packages/components/package.json
- packages/dashboard-core-plugins/package.json
- packages/file-explorer/package.json
- packages/filters/package.json
- packages/golden-layout/package.json
- packages/grid/package.json
- packages/icons/package.json
- packages/iris-grid/package.json
- packages/jsapi-bootstrap/package.json
- packages/jsapi-components/package.json
- packages/jsapi-shim/package.json
- packages/jsapi-types/package.json
- packages/jsapi-utils/package.json
- packages/log/package.json
- packages/pouch-storage/package.json
- packages/react-hooks/package.json
- packages/redux/package.json
- packages/storage/package.json
- packages/utils/package.json
Fixes #1206 
@vbabich you mentioned waiting until JS API was de-globalized, but I don't think that matters. sideEffects will let tree shaking algorithms remove code that doesn't cause any mutations when imported.
Basically if you had an unused import that cannot be removed without breaking things, then that is a sideEffect. JS API stuff doesn't actually do anything but read global state which is not a sideEffect. If we had to do `import @deephaven/jsapi` to make the API load in global scope (like the non-module JS API but that's included as a script tag in the HTML), then that would be considered a sideEffect
> build: Add sideEffects to package.json files

- packages/code-studio/src/main/AppInit.tsx
- packages/code-studio/src/plugins/PluginUtils.tsx
- packages/code-studio/vite.config.ts
Loads plugins individually instead of failing to register if any plugin fails to load. Previously if any plugin failed to load for any reason then no plugins were registered.
Does some validation on if the manifest file exists and the structure of it so that the errors are more descriptive. Does not throw a 2nd error about `Unexpected token <` if there is no manifest file
> feat: Improve plugin load error handling

- packages/components/src/DragUtils.test.ts
- packages/dashboard-core-plugins/src/linker/Linker.test.tsx
- packages/dashboard-core-plugins/src/linker/LinkerLink.test.tsx
- packages/dashboard-core-plugins/src/linker/LinkerLink.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.test.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.test.tsx
Added various tests for Linker. 
- LinkerLink and LinkerUtils are nearly at 100% coverage
- Linker and LinkerOverlayContent are at ~50% coverage
> test: Increase code coverage for Linker

- packages/chart/src/ChartModel.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.ts
- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerLink.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.ts
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- Update `ChartPanel` to get the filter value from `filterList`
- Hide operator selection for filter source and chart links
- Don't allow linking multiple columns from the same table to a chart target
- Fix issue with link in progress not being reset after creating a new link
Fixes #1198
> fix: Fix OneClick links not filtering plots

- packages/chart/src/ChartModel.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.ts
- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerLink.tsx
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
Cherry-pick #1217
- Update `ChartPanel` to get the filter value from `filterList`
- Hide operator selection for filter source and chart links
- Don't allow linking multiple columns from the same table to a chart
target
- Fix issue with link in progress not being reset after creating a new
link
Fixes #1198
> fix: Fix OneClick links not filtering plots (#1217)

- packages/jsapi-components/src/useTableListener.test.ts
- packages/jsapi-components/src/useTableListener.ts
> feat: Added support for null in useTableListener

- package-lock.json
- packages/app-utils/package.json
- packages/dashboard/package.json
- Issue when trying to do an `npm install` in another project that depended on @deephaven/dashboard, as the peerDependency would not resolve the "file:../redux" path
- Not sure if lerna or npm should automatically be replacing those at publish time?
- Was adding redux as a peerDep because we only want one instance of the redux store; otherwise weird bugs can occur that are difficult to track down
- It was already the case with @deephaven/dashboard-core-plugins that it was just a dependency, not a peerDependency. Enterprise handled it just by doing deduplication
- Just move @deephaven/redux to be a dependency instead of a peerDependency
> fix: Move @deephaven/redux to be a dependency instead

- packages/console/src/monaco/MonacoUtils.test.ts
- packages/console/src/monaco/MonacoUtils.ts
- packages/grid/src/GridModel.ts
- packages/grid/src/GridRenderer.test.tsx
- packages/grid/src/GridUtils.ts
- packages/grid/src/MockGridModel.test.ts
Fixes #1252 
Urls require `https://` or `http://`.
> fix: Restrict link parsing so it requires protocol

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/components/src/modal/DebouncedModal.test.tsx
- packages/components/src/modal/DebouncedModal.tsx
- packages/components/src/modal/InfoModal.tsx
- packages/components/src/modal/index.ts
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useDebouncedValue.test.ts
- packages/react-hooks/src/useDebouncedValue.ts
- In some cases, the API disconnects and the reconnects almost immediately afterwards, causing the "Reconnecting..." modal to appear and be distracting
- Rather than have the API lie about whether it's connected or not, UI debounces when it displays the modal, just blocking interaction with a transparent modal for the duration of the disconnection if it reconnects immediately
- Also added logging so we can see when connected/disconnected, in case this is further observed
- Tested using the steps in #1149 , and also manually setting the `debounceMs` to `5000` to be able to react to it
> fix: DH-14657 Better disconnect handling

- package-lock.json
- package.json
- packages/components/src/LoadingSpinner.tsx
- packages/components/src/context-actions/__snapshots__/ContextActions.test.tsx.snap
- packages/dashboard-core-plugins/src/panels/ChartPanel.test.tsx
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.test.tsx
Update adds several new icons see https://github.com/microsoft/vscode-codicons/releases/tag/0.0.33 for changes.
They renamed circle-large-outline to circle-large for naming consistency. I've fixed our usage of vsCircleLargeOutline to vsCircleLarge for the renamed icon (no change in visuals).
BREAKING CHANGE: `vsCircleLargeOutline` icon renamed to `vsCircleLarge`
> feat: Update @vscode/codicons to v0.0.33

- packages/console/src/ConsoleInput.jsx
Cherry pick of #629
When there is autocomplete in the console, the up/down arrows were not cycling through the suggestions
You can use this docker-compose.yml config and run with `VERSION=0.13.0 docker compose up`
```
version: "3.4"
services:
server:
image: ghcr.io/deephaven/server:${VERSION:-latest}
expose:
- '8080'
volumes:
- ./data:/data
- api-cache:/cache
environment:
- JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python
web:
image: ghcr.io/deephaven/web:${VERSION:-latest}
expose:
- '80'
volumes:
- ./data:/data
- web-tmp:/tmp
grpc-proxy:
image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
environment:
- BACKEND_ADDR=server:8080
depends_on:
- server
expose:
- '8080'
envoy:
image: ghcr.io/deephaven/envoy:${VERSION:-latest}
depends_on:
- web
- grpc-proxy
- server
ports:
- …
```
> fix: DH-14732: Cherry-pick arrow keys not selecting next autocomplete item in console

- packages/golden-layout/src/controls/Tab.ts
OnTabContentFocusIn is used to set a class on the tab to highlight which tab currently has focus so the user knows where any keyboard input or shortcuts used will be applied. This was being set by both focusin and any clicks inside the tab, with clicks triggering an addtional call to focus.
Both handlers were commited at the same time, but I can't think of any reason we were actually setting the focus on click. The click itsellf should do that. My best guess is tabindex=-1 wasn't on the parent at the time (during development as it was also added in the same commit) or maybe browser support at the time? It all came in under one commit.
I have tested in chrome (win & mac), firefox (win) and safari (mac) and clicking on or anywher within any panel (tables, plots, one clicks, console, …
> feat: remove click handler setting onTabContentFocusIn

- packages/jsapi-components/src/useDebouncedViewportSearch.ts
- packages/jsapi-components/src/useInitializeViewportData.ts
- packages/jsapi-components/src/useViewportData.ts
> fix: DH-14630: useDebouncedViewportSearch: memoization bug

- packages/iris-grid/src/IrisGrid.tsx
Fixes #1275 
The true issue is we modify `IrisGridProxyModel.model` but there's no update propagated to `IrisGrid` because it receives the proxy model which does not actually change. This causes the potential for out of sync model/metrics
> fix: Select distinct throwing for tables with multiple columns

- packages/code-studio/src/styleguide/Icons.tsx
Changes from searching the kebab case icon name to the component name.
Also strip spaces and dashes before searching, so kebab case search still works.
> fix: Search icon styleguide using prefixed string

- packages/components/src/Button.tsx
- packages/iris-grid/src/sidebar/CustomColumnInput.tsx
resolves: #1282
Broken by #1013. Can't use prop spreading with our Button component, added support for spreading.
Needs silverheels cherry-pick.
> fix: drag to re-arrange custom columns not working

- package-lock.json
- package.json
- packages/code-studio/package.json
- packages/embed-chart/package.json
- packages/embed-grid/package.json
Fixes #1209
Pulled the Vite dependency to the root since we use the same version in any apps like we do with TypeScript
> build: Update to Vite 4.3.5

- packages/code-studio/index.html
- packages/code-studio/vite.config.ts
- packages/embed-chart/index.html
- packages/embed-chart/vite.config.ts
- packages/embed-grid/index.html
- packages/embed-grid/vite.config.ts
Fixes #1161 
Also fixed an embed-grid/embed-chart Vite proxy server issue in preview mode
Tested by running `npm start` and looking at those tags in the head which should be replaced (base, npm version, favicon). Then ran `npm run build` and `npm run preview` and checked the tags in the built version
> build: Use Vite HTML env variable replacement

- packages/jsapi-components/src/HookTestUtils.tsx
- packages/utils/src/MockProxy.test.ts
- packages/utils/src/MockProxy.ts
- packages/utils/src/TestUtils.test.tsx
- packages/utils/src/TestUtils.ts
- makeApiContextWrapper - wrapped in forwardRef to remove console.errr
- createMockProxy - now prints object properties instead of `undefined` in jest matchers. Proxied mock methods now include a mockName() call to give clearer output
fixes #1311
> fix: makeApiContextWrapper and createMockProxy

- packages/app-utils/src/components/FontBootstrap.tsx
Closes #1318 
Fixes bug in font pre-loading created in [previous PR](https://github.com/deephaven/web-client-ui/pull/1180)
> fix: truncated column headers

- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
Steps to reproduce the issue:
1. Have an unsaved notebook with the blue dot indicating unsaved work
3. Drag the panel to a new location
Expected:
Notebook still has unsaved indicator
Actual:
Notebook doesn't have indicator until something causes it to re-render.
> fix: notebook panel unsaved indicator not showing after dragging a panel

- package.json
> fix: disable screenshot tests in debug mode

- packages/app-utils/src/plugins/PluginUtils.tsx
- packages/code-studio/package.json
- packages/code-studio/tsconfig.json
- packages/dashboard/src/Dashboard.tsx
- packages/dashboard/src/DashboardLayout.tsx
- Fix up some types for plugins
- Fix up some packaging
- Add an optional panel wrapper to Dashboard
> fix: Worker plugin definitions, optional panel wrapper for Dashboards

- packages/jsapi-utils/src/TableUtils.test.ts
> fix: DateWrapper fails on first day of month

- packages/code-studio/src/main/AppMainContainer.tsx
Noticed it would shift left sometimes if window is really short. Only allow it to open downwards.
> fix: panels menu should only open downwards

- packages/code-studio/src/main/AppMainContainer.tsx
DH-14657
Increases the timeout to 1s. Immediately shows the disconnect icon on the user settings icon when disconnect happens and changes the tooltip (although it will be extremely difficult for the user to trigger that tooltip since the modal will block access to it 1 second later)
Here's how to test w/ ngrok (I couldn't switch between wired and wireless on my PC b/c I need to fix some wifi drivers apparently)
```
ngrok http 10000
VITE_CORE_API_URL=https://ngrok.link/jsapi npm start
```
Then open `localhost:4000` in firefox and enable work offline from the File menu
> fix: DH-14657 Disconnect handling increase debounce timeout

- packages/utils/src/TestUtils.test.tsx
- packages/utils/src/TestUtils.ts
Console output test util
resolves #1369
> feat: Console output test util

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.scss
- packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.scss
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.tsx
- Adds the "Number of Columns" value to the tooltip.
- Also converted to css-grid so things would line up nicely
> feat: add column count to table tooltip

- packages/app-utils/src/components/AuthBootstrap.tsx
- packages/auth-plugins/src/AuthPluginParent.test.tsx
- packages/auth-plugins/src/AuthPluginParent.tsx
- packages/jsapi-utils/src/MessageUtils.test.ts
- packages/jsapi-utils/src/MessageUtils.ts
- Check for window.opener _or_ window.parent when using AuthPluginParent
- Reorder plugin priority to use AuthPluginParent first if specified
- Tested using an example html page that both embeds and pops open a new tab
- Fixes #1373 
To test:
1. Start up deephaven-core with PSK set to `hello`: `./gradlew server-jetty-app:run -Ppsk=hello`
2. Start up Web UI: `npm start`
3. Create a table named `t` in the Web UI at https://localhost:4000:
```
t = empty_table(50).update(["x=i%5", "y=(i*i)%5"])
```
4. Open the HTML file in the provided zip.
[iframe-auth-provider-local.zip](https://github.com/deephaven/web-client-ui/files/11820375/iframe-auth-provider-local.zip)
5. Ensure the table appears correctly in the iframe. Click the "Open in new tab" link, and ensure …
> fix: AuthPluginParent wasn't working when embedded in an iframe

- packages/app-utils/src/components/AuthBootstrap.tsx
- packages/auth-plugins/src/AuthPluginParent.test.tsx
- packages/auth-plugins/src/AuthPluginParent.tsx
- packages/jsapi-utils/src/MessageUtils.test.ts
- packages/jsapi-utils/src/MessageUtils.ts
- Check for window.opener _or_ window.parent when using AuthPluginParent
- Reorder plugin priority to use AuthPluginParent first if specified
- Tested using an example html page that both embeds and pops open a new tab
- Fixes #1373
- Cherry-pick of #1383
> fix: AuthPluginParent wasn't working when embedded in an iframe (#1383)

- .github/workflows/e2e.yml
- README.md
- deephaven-core defaults to using PSK authentication, which broke our e2e tests
- Specify anonymous authentication when verifying e2e tests
- Fixes #1388
> build: Use anonymous authentication when verifying snapshots

- packages/utils/src/TypeUtils.ts
TypeScript util type "Extends"
resolves #1393
> feat: "Extends" TypeScript util type

- packages/iris-grid/src/AdvancedFilterCreator.test.tsx
- packages/iris-grid/src/AdvancedFilterCreator.tsx
- packages/iris-grid/src/ColumnStatistics.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/jsapi-types/src/dh.types.ts
> feat: disable column sorting on unsupported types

- packages/iris-grid/src/sidebar/CustomColumnInput.tsx
- packages/iris-grid/src/sidebar/InputEditor.tsx
- packages/iris-grid/src/sidebar/index.ts
- Exporting InputEditor from @deephaven/iris-grid
- Added optional properties `className` and `placeholder`
resolves #1397
Supporting DH-14538
> feat: DH-14538: Export InputEditor and added options

- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.ts
- Wasn't adding the error bars in this case
- Needed for https://github.com/deephaven/deephaven-core/issues/2156 to work
- Needs https://github.com/deephaven/deephaven-core/pull/4202
- Tested with the snippet in the ticket to create the plot:
```
from deephaven.plot import PlotStyle
from deephaven.column import int_col, string_col
source = new_table([
string_col("Categories", ["A", "B", "C"]),
int_col("Categories2", [1, 2, 3]),
int_col("Values", [9, 10, 11]),
int_col("LowerError", [8, 9, 10]),
int_col("UpperError", [10, 11, 12])
])
v2_plot = Figure().plot_cat(series_name="Categories Plot v2", t=source, category="Categories2", y="Values", y_low="LowerError", y_high="UpperError").show()
```
- Also tested OHLC and …
> feat: Add support for Category plots with error bars

- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
- .npmrc
- lerna.json
- package-lock.json
- package.json
- Removed `useWorkspaces` flag (no longer used)
- Removed 'useNx' flag (NX seems to work in the latest)
- Add provenance flag to .npmrc
- Fixes #1235
- Tested `npm start`, `npm test`, and `npm run build` steps and ensured they all worked correctly
> build: Update to lerna 7.x

- .github/workflows/audit-fix.yml
- Scheduled to run every Thursday morning at 6am UTC (2am ET)
- Opens a PR automatically
- PR still needs to be reviewed/approved
> ci: Add workflow to automatically run npm audit fix weekly

- packages/console/src/Console.tsx
- packages/console/src/console-history/ConsoleHistoryItem.tsx
- packages/console/src/csv/CsvTypeParser.ts
- Fix adding error console history items
- They weren't appearing as anything because the command was `''` instead of `undefined`
- Map LOCAL_TIME to STRING on CSV import
- `LOCAL_TIME` isn't supported on the server in DHC, and isn't really "safe" anyways since we should have other info in there as well (e.g. date or time zone)
- When exporting, should be exporting the 'unformatted' value, which gives you the full timestamp
- By mapping to String, user can then do an `.update_view` to map it to a timestamp if they wish
- Fixes #1432
> fix: Cannot import CSV with LOCAL_TIME

- packages/eslint-config/index.js
While migrating Enterprise to use our Community eslint rules, there seemed to be only 1 additional rule used by Enterprise:
```json
"react/react-in-jsx-scope": "off"
```
I added it to the Community config.
resolves #1429
> chore: Disabled react/react-in-jsx-scope

- .github/workflows/e2e.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
- .github/workflows/unit.yml
Small thing I noticed when working on an action file is that the setup-node action supports reading the version from a file. This means our actions should automatically stay up to date any time we change the version in `.nvmrc`
> ci: Change setup-node to read version from nvmrc

- packages/code-studio/src/styleguide/index.html
Missed the styleguide in #1304. This fixes the environment variable replacement
> fix: Environment variable replacement in styleguide

- README.md
- jest.setup.ts
- package-lock.json
- package.json
- packages/code-studio/package.json
- packages/console/package.json
- packages/console/src/ConsoleInput.tsx
- packages/console/src/log/LogView.tsx
- packages/console/src/monaco/MonacoUtils.test.ts
- packages/console/src/monaco/MonacoUtils.ts
- packages/console/src/notebook/Editor.tsx
- packages/iris-grid/package.json
- packages/iris-grid/src/sidebar/CustomColumnBuilder.test.tsx
Fixes #1445, fixes #1191 Fixing Monaco bug by upgrading to latest ^0.41.0
Supports DH-15438
BREAKING CHANGE: Monaco will need to be upgraded to ^0.41.0 in Enterprise to ensure compatibility
**Tests Performed**
- Console Input
- `Cmd+F` does nothing
- Intellisense can be closed via `Esc`
- Log tab
- `Esc` does not close find input
- `Esc` does clear selection when focus is in the log content
- Code Editor
- Verified that newline with leading space no longer crashes the browser tab
```
a
a
```
- Wrote some Python code. Intellisense, syntax highlighting, and general typing experience seemed as expected
- Execute full code + selected code successfully
> fix: Upgrade Monaco to ^0.41.0

- packages/chart/package.json
- packages/iris-grid/package.json
- packages/iris-grid/src/IrisGridMetricCalculator.ts
- packages/iris-grid/src/IrisGridRenderer.ts
- packages/iris-grid/src/index.ts
Helps clean up the docs snapshot tool imports. Lets the snapshot tool remove all imports from `@deephaven/<package>/dist/...`
There is a `./*.js` and `./*` exports because [Node has some suggestions](https://nodejs.org/api/packages.html#extensions-in-subpaths) about using extensions to allow leaner import maps and mirror the ESM requirement of full specifiers for imports. However, Docusaurus/Webpack don't like the `./*.js` export and seem to require `./*`
> chore: Add exports for plotly express docs snapshot tool

- packages/dashboard/src/DashboardLayout.tsx
- packages/dashboard/src/DashboardPlugin.ts
- packages/golden-layout/src/LayoutManager.ts
- packages/golden-layout/src/utils/ReactComponentHandler.tsx
This ref doesn't seem to be used by anything and prints dev warnings if any panel is a functional component that doesn't use `React.forwardRef`. I couldn't find anywhere we actually use the ref and it looks like it was a workaround for golden-layout adding the ref as default props to every component. The way we use golden-layout, I don't think it's even possible to attach a ref to the component in a way that a plugin could access that ref.
> fix: Remove unused ref forwarded to all dashboard panels

- packages/code-studio/src/settings/LegalNotice.tsx
Modal shouldn't be nested inside the button, messes up click handling and makes the modal dismiss on a click anywhere.
> fix: legal notices dismisses on click anywhere

- tests/console.spec.ts
- tests/notebook.spec.ts
- tests/table-operations.spec.ts
- tests/table.spec.ts
- tests/utils.ts
Doesn't seem to be a single solution that works in all 3 browsers in headless mode, but between 2 solutions we can cover pasting in all 3 browsers
> test: Add firefox support for playwright pasteInMonaco

- package-lock.json
- package.json
- packages/code-studio/package.json
- packages/console/src/csv/CsvInputBar.tsx
- packages/console/src/csv/CsvParser.ts
- packages/console/src/csv/CsvTypeParser.ts
- packages/console/src/csv/ZipStreamHelper.ts
Fixes #1080. Fixes #1416 
Updates jszip and uses the internal stream helper instead of nodestream which we would need a polyfill for. The progress on zip uploads is a bit odd since we use the unzip progress. It seems papaparse loads more from the stream while processing/before processing and can finish reading the zip before it's done processing chunks.
Also, uploading the tables seems to be a blocking operation. Not sure if that's an easy fix, but after the 50% mark on uploading a large zip, there are some blocks on the main thread (marching ants freezes as an indicator).
There is a ~2GB limit for JSZip it seems https://github.com/Stuk/jszip/issues/777
> fix: Zip CSV uploads not working

- packages/react-hooks/src/useAsyncInterval.test.ts
- packages/react-hooks/src/useAsyncInterval.ts
fixes #1464 - Heap usage checks now run immediately whenever useEffect dependencies change.
> fix: Heap usage should tick immediately when dependencies change

- packages/utils/src/ClassUtils.test.ts
- packages/utils/src/ClassUtils.ts
- packages/utils/src/index.ts
Util functions for binding all methods of an object to itself.
resolves #1474
> feat: bindAllMethods util function

- packages/code-studio/src/storage/grpc/GrpcFileStorage.ts
- packages/components/src/ItemList.tsx
- packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
- packages/dashboard-core-plugins/src/panels/MockFileStorage.ts
- packages/file-explorer/src/FileExplorer.tsx
- packages/file-explorer/src/FileList.tsx
- packages/file-explorer/src/FileListContainer.tsx
- packages/file-explorer/src/FileListItem.tsx
- packages/file-explorer/src/FileStorage.ts
Fixes #185, Fixes #1375, Fixes #1488 and other issues with File Explorer
Fixes issue where you couldn't rename a renamed item, and then can't use context menu at all on file explorer.
Fixes issue where triggering a tooltip while renaming would re-render and exit edit mode.
Wires up copy, new file, new folder in context menu.
Renames copy -> copy file
> feat: adds copy file support to file explorer and fixes rename bug

- packages/console/src/Console.tsx
I discovered DH-14062 independently and found that this method occasionally was prematurely returning when the view should stay stuck to the bottom of the contents.
Sometimes `pane.scrollTop` is sometimes 0.5 less than the expected value when tailing the content. This `Math.round` bumps it up. I only saw `xxxxx.0` and `xxxxx.5` values during investigation, but I did not do any further research on the origin of the value or the rounding error.
Here is a sample groovy snippet that reproduces 100% of the time:
```groovy
import io.deephaven.internal.log.LoggerFactory
log = LoggerFactory.getLogger(Object.class
log.error().append(new RuntimeException()).endl()
t = io.deephaven.engine.util.TableTools.timeTable("PT1s")
```
> fix: Console History Not Scrolling to Bottom (DH-14062)

- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
This is needed so the plotly-express plugin can attach event handlers to the chart container to pause re-renders when the user is manipulating the view on a 3d plot
> feat: Expose containerRef from ChartPanel

- packages/jsapi-bootstrap/src/ApiBootstrap.tsx
- Use webpackIgnore to disable url resolving: https://webpack.js.org/loaders/css-loader/#disable-url-resolving-using-the--webpackignore-true--comment
- Tested with https://github.com/deephaven-examples/deephaven-react-app-enterprise/tree/cra-light-dashboard. No warning was emitted from the webpack build step.
- Tested `npm start` still loaded correctly
> fix: webpack dynamic import

- packages/grid/src/Grid.tsx
* The mouse handler for the table "view full contents" button was called after the mousehandler for cell tokens. This caused links inside the cell to open if the cell overflow button overlapped with a link inside the cell underneath it.
* Priority for GridTokenMouseHandler changed to be after the CellOverflowMouseHandler.
* Fixes #1480
> fix: Table overflow button has lower priority than grid tokens

- packages/code-studio/public/download/serviceWorker.js
- packages/code-studio/src/DownloadServiceWorkerUtils.ts
- packages/iris-grid/src/sidebar/TableSaver.tsx
Fixes #766 
BREAKING CHANGE: `TableSaver` now expects the service worker to send it a complete URL for download instead of just a file name. DHE will need to adjust its `serviceWorker.js` to incorporate the same changes from this PR.
> refactor: Improve table saver to always use the correct service worker

- tests/utils.ts
@georgecwan was having issues w/ e2e tests running on Mac (Intel, only in headless mode). I confirmed they weren't working on my Mac (Intel) either. Specifically, `pasteInMonaco` in chromium was not working (timed out on the paste sanity check).
Tested on Mac and Linux that this adjustment works.
@georgecwan Checkout this repo (I recommend the VSCode GitHub Pull Requests and Issues plugin) and confirm e2e works for you on Mac.
> test: Fix e2e paste in chromium on mac

- packages/components/src/context-actions/ContextMenuRoot.tsx
- tests/context-menu.spec.ts
Fixes #1525 
This was bothering me while working on element plugins which should have a panel w/ the custom context menu enabled. Tested on Chrome/Firefox on Linux
> fix: Right clicking with a custom context menu open should open another context menu

- packages/dashboard/src/DashboardLayout.tsx
- packages/golden-layout/src/utils/ReactComponentHandler.tsx
- tests/notebook.spec.ts
> fix: Dehydration of class components

- packages/embed-grid/README.md
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridCopyHandler.test.tsx
- packages/iris-grid/src/IrisGridCopyHandler.tsx
- embedded iframes require the 'clipboard-write' permission to copy in Chrome. Added note to the README
- Display an error correctly if the copy doesn't succeed, and added unit test
- Fixed context menu as well - default menu handler did not return an array as it should've
- Tested in Firefox and Chrome on Linux
- Fixes #1527
> fix: Copy did not work from embedded iframes

- package.json
`npm run clean` was broken b/c I added a `clean:cache:nx` but then removed `nx` since it doesn't play nicely w/ env variables.
> build: Remove broken nx cache clean script

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.test.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.tsx
- packages/iris-grid/src/PartitionSelectorSearch.tsx
* Partitioned tables were unable to be rendered if the partitioned column type is not `java.lang.String`
* Grid can now render string, numerical, and character columns
* Fixes partitioning columns filter dropdown to correctly display `char` types instead of their ASCII values
* The partition search bar function is now able to search for numbers
* Removes the handleFocus function for `PartitionSelectorSearch` since it made it impossible for the user to edit the search bar after deselecting it
* Fixes #1441
> fix: Render tables partitioned by non-string columns

- tests/table-operations.spec.ts
Temporarily disabling failing e2e test until we can figure out the root cause.
#1553
> fix: Disabled failing e2e test

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/dashboard-core-plugins/src/panels/NotebookPanel.test.tsx
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- tests/golden-layout.spec.ts
User is not prompted to confirm when using the "reset layout" feature.
- With unsaved notebook changes, prompt title will be "Reset layout and discard unsaved changes"
- With open notebooks that are saved or no open notebooks, prompt title will be "Reset Layout"
- If user clicks "Reset", layout will be reset. Unsaved notebook changes will be lost
- If user clicks "Cancel", layout will not be reset and notebooks remain open
fixes #1250
> fix: Prompt for resetting layout

- packages/code-studio/src/settings/ColumnSpecificSectionContent.test.tsx
- packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
- packages/code-studio/src/settings/FormattingSectionContent.tsx
- packages/eslint-config/index.js
* Default Formatting Rule should change depending on the defaults set by the user
* Changing columnType should fill the input with the default string
~~* Pressing `enter` on empty formatting string input fields should fill the input with the default string~~
~~* Updated eslint config to handle lines ending in CRLF correctly~~
> fix: Formatting Rule Doesn't use default set by user

- packages/components/src/theme/theme-dark/theme-dark-semantic-editor.css
- packages/console/src/monaco/MonacoTheme.module.scss
- packages/console/src/monaco/MonacoUtils.ts
This fixes some Monaco suggestion colors
fixes #1592
> fix: Adjusted Monaco "white" colors

- packages/console/src/ConsoleInput.tsx
In the console, pressing the `Tab` key previously brought up the autocomplete prompt. Now it will insert a tab's worth of spaces instead.
Can still trigger autocomplete by using `Ctrl+Space`
> fix: Tab in console input triggers autocomplete instead of indent

- packages/grid/src/Grid.tsx
- packages/grid/src/key-handlers/SelectionKeyHandler.ts
Closes #1477 
Previous comments are in #1571 PR. 
Note: Once this PR is merged #1571 can go in as well
> fix: stuck to bottom on filter clear

- jest.config.base.cjs
- packages/babel-preset/index.js
- packages/code-studio/src/styleguide/ThemeColors.tsx
- packages/components/package.json
- packages/components/src/declaration.d.ts
- packages/components/src/theme/theme-dark/index.ts
- packages/components/src/theme/theme-light/index.ts
- packages/console/src/monaco/MonacoUtils.ts
It seems that Enterprise does not handle css ?inline css imports in node_modules the same way it does in src. Namely, the raw content gets imported as an empty string instead of the raw content.
- Converted ?inline imports to ?raw. These seem to handle the raw content as expected even if in node_modules
- Added a sass minification step to @deephaven/components. Vite seems to minify ?inline imports but does not do so with raw
- Added a try / catch to MonacoUtils to avoid non-hex theme variables from crashing the entire app
fixes #1599
BREAKING CHANGE: Theme css imports were switched from `?inline` to `?raw`. Not likely that we have any consumers yet, but this would impact webpack config.
> fix: Theming - switched from ?inline to ?raw css imports

- packages/dashboard-core-plugins/src/ChartPlugin.tsx
- packages/dashboard-core-plugins/src/ChartPluginConfig.ts
- packages/dashboard-core-plugins/src/GridPlugin.tsx
- packages/dashboard-core-plugins/src/GridPluginConfig.ts
- packages/dashboard-core-plugins/src/PandasPluginConfig.ts
- packages/dashboard-core-plugins/src/WidgetLoaderPlugin.tsx
- packages/dashboard-core-plugins/src/index.test.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/dashboard-core-plugins/src/panels/PandasPanel.tsx
- packages/dashboard-core-plugins/src/panels/Panel.tsx
- packages/dashboard-core-plugins/src/useHydrateGrid.ts
Fixes #1573 
This fix should be adequate for furthering the Deephaven UI alpha. Rather than trying to refactor 2 1k+ line files (IrisGridPanel and ChartPanel), I opted to add some DOM detection to the `Panel` component to prevent rendering tab context menu/tooltips if it is nested within another panel.
For Deephaven UI, we will need to ensure the UI panel uses `Panel` at least and passes through `glContainer` and `glEventHub` to the child elements so grids and charts function roughly as normal.
To test how something would look/function when wrapped, remove the `panelComponent` line from either of the plugin configs. This will wrap in a generic `WidgetPanel` which you can see in dev tools. The panel tab will not have any of the custom tooltip for grid or custom context menus.
Test by …
> feat: Convert DashboardPlugins to WidgetPlugins

- __mocks__/css/mock-theme-dark-components.js
- __mocks__/css/mock-theme-dark-palette.js
- __mocks__/css/mock-theme-dark-semantic-editor.js
- __mocks__/css/mock-theme-dark-semantic-grid.js
- __mocks__/css/mock-theme-dark-semantic.js
- __mocks__/css/mock-theme-light-palette.js
- __mocks__/css/mock-theme-spectrum-alias.module.js
- __mocks__/css/mock-theme-spectrum-overrides.module.js
- __mocks__/css/mock-theme-spectrum-palette.module.js
- jest.config.base.cjs
- packages/babel-preset/mockCssImportPlugin.js
- packages/babel-preset/package.json
- packages/components/src/__snapshots__/SpectrumUtils.test.ts.snap
- packages/components/src/theme/ThemeUtils.test.ts
- packages/components/src/theme/__snapshots__/ThemeProvider.test.tsx.snap
Created a Babel transform plugin `mockCssImportPlugin` that transforms certain css imports into const expressions.
- Replaces import of `.module.css` / `.module.scss` -  with a const object literal containing a key / value of the module name
- Replaces css imports of `?inline` and `?raw` with a const string literal matching the import path
The new plugin is configured as a plugin for `babel-jest`
resolves #1606
> feat: Babel Plugin - Mock css imports

- packages/dashboard-core-plugins/src/WidgetLoaderPlugin.tsx
- packages/dashboard-core-plugins/src/panels/Panel.tsx
- packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx
- packages/dashboard/src/DashboardPlugin.ts
- packages/dashboard/src/layout/LayoutUtils.ts
- Just pass the instance of Panel in if componentPanel is null
- We'll need to do something else to wire up tables to linker
> fix: Panel focus throwing an exception

- packages/grid/src/Grid.tsx
- packages/grid/src/key-handlers/SelectionKeyHandler.ts
Reverts deephaven/web-client-ui#1579
Did a revert + fix of the original issue b/c the revert made a few e2e tests unstable
Fixes #1477
Fixes #1615
> fix: Ticking tables scrolling back to bottom when not stuck to bottom

- packages/dashboard/src/layout/LayoutUtils.ts
Reset `isStuckToBottom` and `isStuckToRight` in `dropLayoutMinorChange`.
The flags are still stored in the shared layout, but don't trigger the sharing dot.
Testing:
- Open a new dashboard, add a table with more rows than fits on the screen
- Share the dashboard layout with the table scrolled up, `isStuckToBottom` is `false`
- Scroll the table to the bottom, confirm the Sharing dot doesn't appear even though the `isStuckToBottom` flag is now set to `true`
- Click on the Sharing button, confirm the dialog shows the "Share updated state" message allowing to share the new `isStuckToBottom` state
- Scroll the table up a few rows to get it un-stuck, confirm the blue dot still doesn't show up. Open the Sharing dialog, confirm the "Share update state" message disappeared since the current …
> fix: DH-15864: Scroll position StuckToBottom shouldn't trigger sharing dot

- .vscode/settings.json
- README.md
- package.json
Added a `test:debug` npm script.
resolves #1627
> feat: Added test:debug script

- packages/chart/src/Chart.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/grid/src/Grid.scss
- packages/grid/src/Grid.test.tsx
- packages/grid/src/Grid.tsx
- packages/iris-grid/src/IrisGrid.scss
- packages/iris-grid/src/IrisGrid.test.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useResizeObserver.ts
- ResizeObserver is now widely available in all browsers, so use it to listen for resizing of our grid and plot elements
- Pull `grid-wrapper` from `IrisGrid` and put it directly in `Grid`
- Now `Grid` doesn't have to listen to the "parent" element, which was kind of strange in the first place.
- Tested by opening up some tables and charts, resizing the panels and ensuring they updated correctly.
> feat: Add ResizeObserver to Grid and Chart

- packages/grid/src/Grid.tsx
While looking at some perf snapshots I noticed calls to updateCanvasScale on every grid render had a ~0.25-0.5ms perf cost (including table ticks). Mostly due to touching the dom with the set width/set height calls triggering a recalculate style call and the getScale call. While insignificant, it is also unnecessary unless size actually changes. Making it conditional improves perf on most re-renders. I used parseFloat in case grid somehow ends up with fractional pixel if set outside of our control (which shouldn't happen, but you never know with plugins).
Before:
After:
updateCanvasScale is now gone from the perf profile entirely on a normal grid render.
Tested re-sizeing panels, and window with table both shown and hidden still resizes grid correctly.
> fix: remove unecessary dom re-calc in grid render

- packages/grid/src/Grid.tsx
- packages/utils/src/ObjectUtils.tests.ts
- packages/utils/src/ObjectUtils.ts
- packages/utils/src/index.ts
- Caused by #1626
- The children on IrisGrid were getting re-rendered as a result of IrisGrid.handleViewChanged getting called after updating the canvas in Grid.componentDidUpdate
- Another fix would be to memoize metrics and not emit a view change if they are exactly the same as previous metrics, but thought that was a bigger change (need to deep equals a bunch of maps and arrays in the metrics)
- Tested by opening up a table with React dev tools highlighting re-renders. Table did not re-render when not being interacted with.
> fix: Infinite loop with grid rendering

- packages/code-studio/src/styleguide/Inputs.tsx
- packages/components/src/DateInput.tsx
> fix: Date argument non-optional for the onChange prop

- packages/app-utils/src/plugins/remote-component.config.ts
- packages/dashboard-core-plugins/src/ChartPlugin.tsx
- packages/dashboard-core-plugins/src/GridPlugin.tsx
- packages/dashboard-core-plugins/src/PandasPlugin.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- packages/dashboard-core-plugins/src/panels/ChartPanelUtils.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/dashboard-core-plugins/src/panels/Panel.scss
- packages/dashboard-core-plugins/src/panels/Panel.tsx
- packages/dashboard-core-plugins/src/useHydrateGrid.ts
Mostly needed for Deephaven UI w/ widget plugin loading which will recreate the `makeModel` method if a new widget is created
> fix: Panels not reinitializing if makeModel changes

- __mocks__/dh-core.js
- packages/chart/src/Chart.scss
- packages/chart/src/Chart.tsx
- packages/chart/src/ChartModel.ts
- packages/chart/src/ChartTestUtils.ts
- packages/chart/src/DownsamplingError.ts
- packages/chart/src/FigureChartModel.test.ts
- packages/chart/src/FigureChartModel.ts
- packages/chart/src/index.ts
- packages/chart/tsconfig.json
- packages/jsapi-types/src/dh.types.ts
- Requires Core PR https://github.com/deephaven/deephaven-core/pull/4763
- Also need to port that to Enterprise
- Actually look at the errors reported by the figure, and log them so we have a clearer idea of what the issue is when plots are reported as not working
- Also show the error message in the chart panel button bar. Clicking the button will display the full error message.
- Don't show the spinner infinitely if there are no series to load
> fix: Log figure errors, don't show infinite spinner

- packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
- packages/code-studio/src/settings/FormattingSectionContent.tsx
- packages/code-studio/src/styleguide/Inputs.tsx
- packages/components/src/Select.tsx
- packages/console/src/csv/CsvInputBar.tsx
- packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.test.tsx
- packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
- packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.tsx
- packages/dashboard-core-plugins/src/panels/FilterSetManager.tsx
- packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
- packages/iris-grid/src/GotoRow.tsx
- packages/iris-grid/src/sidebar/ChartBuilder.tsx
- packages/iris-grid/src/sidebar/SelectDistinctBuilder.tsx
- packages/iris-grid/src/sidebar/TableCsvExporter.tsx
- packages/iris-grid/src/sidebar/conditional-formatting/ConditionEditor.tsx
Replaces all the places we used raw html select components with the Select component.
This was orignally needed for themeing so we could re-style the Select component, but we came up with an alternate solution.
> refactor: replace html selects with Select component

- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
Minor drop in the bucket against #1650, reduces at least some of the re-rendering.
> fix: convert organize columns component to purecomponent

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridTableModel.ts
- Previously we were unable to remove columns from an aggregate selection
- Default to `Skip` operation unless the user has actually applied one or more operations for a column
- Requires https://github.com/deephaven/deephaven-core/pull/4780
- Tested using the steps in the description of #1355
- Fixes #1355
> fix: Default to `Skip` operation instead of `Sum` operation

- tests/docker-scripts/docker-compose.yml
Always pull the latest edge server, as unless you manally pull this regularly your tests can fail.
> test: set pull_policy to always for e2e:docker tests

- packages/console/src/Console.tsx
- packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
- Creating a table with a name that begins with an underscore will not open it regardless of whether "Auto Launch Panels" is checked
- Closes #1549
- Fixes a bug where tables will not update if its variable is reassigned while "Auto Launch Panels" is unchecked
- Closes #1410
1. Run the following code with the "Auto Launch Panels" option checked:
```py
t = empty_table(10).update("x=i")
_t = empty_table(10).update("x=i")
```
2. Table `t` should open automatically but table `_t` should remain closed
3. Clicking on the button for `_t` should open it normally
4. Run `_t = empty_table(10).update("x=i+10")`. This should update the values in `_t` if it is open
- Nothing should happen if `_t` is closed.
BREAKING CHANGE: Tables assigned to variable beginning with …
> feat: Tables that have names starting with underscore do not auto-launch from console

- packages/components/src/theme/theme-dark/theme-dark-semantic-grid.css
- packages/components/src/theme/theme-dark/theme-dark-semantic.css
- packages/iris-grid/src/FilterInputField.scss
- add full accent-100-1400 hsl colours
- use accent colours with transparency to more closely match original grid design for filter bar colour
- use those variables in the filter input field, with a hacky stacked solid colour linear gradient, such that transperncy has the colour underneath as canvas would
- --dh-color-grid-row-hover-bg was too dark, bumped up one level (no longer the same as elsewhere, but grid stripes are lighter so it needs more contrast
> fix: adjust filter bar colour

- packages/code-studio/src/styleguide/grid-examples/DataBarExample.tsx
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/redux/src/selectors.ts
- packages/utils/src/TypeUtils.ts
> fix: Made selector return types generic

- packages/auth-plugins/src/LoginForm.tsx
- packages/chart/src/ChartThemeProvider.tsx
- packages/chart/src/MockChartModel.ts
- packages/components/src/RandomAreaPlotAnimation.tsx
- packages/components/src/theme/ThemeProvider.tsx
- packages/console/src/console-history/ConsoleHistoryResultInProgress.tsx
- packages/iris-grid/src/IrisGridThemeProvider.tsx
- packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
- packages/iris-grid/src/sidebar/TableCsvExporter.tsx
Moved ThemeProvider updates into effect
resolves #1669
> feat: Theming - Moved ThemeProvider updates into effect

- packages/chart/src/ChartTestUtils.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.test.ts
- packages/chart/src/FigureChartModel.ts
- Previously for some reason we were mapping the first subplot chart title to the figure title, which was incorrect. Instead map the Figure title attribute to the figure, and then chart title to the individual subplots
- Annoyingly plotly doesn't have a chart title property, so we need to map these titles to `annotations` to get it to work correctly
- Fixes #1674 , Fixes #1675 
- Tested with the following snippet:
```
from deephaven import read_csv
insurance = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Insurance/csv/insurance.csv")
insurance_by_region = insurance.view(formulas=["region", "expenses"]).avg_by(["region"])
insurance_by_sex = insurance.view(formulas=["sex", "expenses"]).avg_by(["sex"]) …
```
> fix: `figure_title` and `chart_title` were not mapped up correctly

- packages/components/src/actions/ConfirmActionButton.tsx
- packages/components/src/actions/IconActionButton.tsx
- packages/components/src/dialogs/ActionButtonDialogTrigger.tsx
- packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
Added tooltip prop to action button components
resolves #1705
> feat: Action button tooltips

- packages/grid/src/index.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- The implementation for IrisGridTableModelTemplate.backgroundColorForCell did not accept a theme, even though GridModel.backgroundColorForCell does
- This caused issues with classes that extended IrisGridTableModelTemplate or it's subclasses like IrisGridTableModel, as the could not override this method to correctly accept the theme parameter
- Also export all types from GridTheme - there were a few things not being exported (such as `GridColor`)
- Fixes #1697 
BREAKING CHANGE:
- Subclasses of IrisGridTableModelTemplate or it's subclasses that use backgroundColorForCell may need to update their signature to accept the theme if they are calling the superclass
> fix: Interface for IrisGridTableModelTemplate.backgroundColorForCell

- packages/iris-grid/src/IrisGridUtils.ts
- Fixes #1561 
- Added the optional chaining operator to prevent an error from being thrown
> fix: GoToRow timestamp fails when selected row is out of view

- packages/jsapi-bootstrap/src/useApi.test.ts
- packages/jsapi-bootstrap/src/useApi.ts
- packages/jsapi-bootstrap/src/useDeferredApi.test.ts
- packages/jsapi-bootstrap/src/useDeferredApi.ts
- Port over the functionality of GetPanelApiContext into a hook that can be easily used instead
- Will be necessary to ensure widgets panels are wrapped in the correct API, as they are opened using portal panels and may not be wrapped in the same API
- See DH-16249 for issue with wrong API being used in Enterprise
> feat: Add support for useDeferredApi

- packages/jsapi-utils/src/ConnectionUtils.test.ts
- packages/jsapi-utils/src/ConnectionUtils.ts
- Implements #1701 
- `fetchVariableDefinition` now throws an `Error` when a variable is not found (instead of throwing `TimeoutError`)
- `TimeoutError` still used and will be thrown on an actual timeout
- Tests added to check for the correct error
> feat: Reject promise immediately if var not found

- packages/components/src/TimeInput.test.tsx
- packages/components/src/TimeInput.tsx
Update TimeInput to trigger onChange on incomplete input values, missing chars filled in with zeros. Update internal/displayed value on blur to match the last onChange.
fixes #1710
> fix: TimeInput not triggering onChange on incomplete values

- packages/code-studio/src/styleguide/SpectrumComparison.tsx
- packages/components/src/theme/ThemeModel.ts
- packages/components/src/theme/ThemeProvider.tsx
- packages/components/src/theme/ThemeUtils.test.ts
- packages/components/src/theme/ThemeUtils.ts
- Preload now always applies default preload values before applying cached ones. This ensures that cached preload values don't prevent new defaults from being applied if / when we add new variables to the preload list
- Default preload variables can now be passed in to ThemeUtils + ThemeProvider. This will allow DHE to specify additional variables if needed
resolves #1695 and part of #1679
> feat: Improved preload variable handling

- packages/console/src/common/Code.tsx
Fixes an issues where the command history doesn't get re-colorized when the theme changes.
Steps to reproduce:
Run a command, then change theme (depends on which theme you started on, but history will look wrong):
> fix: re-colorize command codeblocks when theme changes

- packages/components/src/HierarchicalCheckboxMenu.scss
Caret shouldn't shrink if component is truncating. Component only used in enterprise right now, and there's a duplicate change in deephaven-ent/iris#1274
> fix: hcm caret shouldn't be allowed to shrink

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/console/src/HeapUsage.tsx
- packages/dashboard-core-plugins/src/panels/ConsolePanel.test.tsx
- packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
- packages/dashboard-core-plugins/src/panels/FileExplorerPanel.tsx
- packages/dashboard-core-plugins/src/panels/LogPanel.tsx
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- packages/dashboard-core-plugins/src/redux/selectors.ts
- packages/react-hooks/src/useAsyncInterval.test.ts
- packages/react-hooks/src/useAsyncInterval.ts
- Handle undefined props on DashboardData. Don't render console panel if no session
- Fixed a set state on unmounted HeapUsage bug
- Removed chatty async interval debug logging
fixes #1684
**Testing**
- Run server with PSK enabled
- Login and open any file
- Logout should no longer show "ConsolePanel.tsx:372 Uncaught TypeError: Cannot destructure property 'config' of 'sessionWrapper' as it is undefined." error in debug console (Note that login will still fail until #1685 is done)
> fix: Handle undefined DashboardData props

- packages/iris-grid/src/mousehandlers/IrisGridDataSelectMouseHandler.ts
resolves: #1704
each click still toggles immediately, but the final state will always be selected as double click handler comes after.
> feat: double-clicking grid rows should select the row rather than toggle selection twice

- package-lock.json
- packages/code-studio/package.json
- packages/code-studio/src/main/AppMainContainer.tsx
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/code-studio/src/settings/SettingsUtils.test.tsx
- packages/code-studio/src/settings/SettingsUtils.tsx
- packages/components/src/shortcuts/GlobalShortcuts.ts
- Adds a shortcut for copying version info to clipboard to make it easier when making tickets.
- Adds a new package for parsing UA strings
- Adds browser/os to version info for copying
> feat: added shortcut for copying version info and added browser/os to info

- packages/jsapi-bootstrap/src/DeferredApiBootstrap.test.tsx
- packages/jsapi-bootstrap/src/DeferredApiBootstrap.tsx
- packages/jsapi-bootstrap/src/index.ts
- It wasn't actually being exported
- Also add a DeferredApiBootstrap component to gate on loading the API
> fix: Fix useDeferredApi export

- packages/dashboard/src/redux/actions.ts
- packages/dashboard/src/redux/hooks.ts
- packages/dashboard/src/redux/index.ts
- packages/dashboard/src/redux/selectors.ts
- packages/redux/src/store.ts
Add `useDashboardPluginData` hook for accessing plugin data in redux
> feat: Add pluginDataMap to redux, add useDashboardPluginData hook

- packages/dashboard-core-plugins/src/GridPluginConfig.ts
- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/plugin/src/PluginTypes.ts
Made `PluginType` generic. This fixes a breaking change that impacts `PlotlyExpressChartPanel` and `PlotlyExpressChart` in the plugins repo so that our next version bump will be cleaner.
fixes #1759
> fix: Made WidgetComponentProps generic

- packages/components/src/modal/DebouncedModal.tsx
- packages/jsapi-components/src/useCheckIfExistsValue.ts
- packages/jsapi-components/src/useDebouncedViewportSelectionFilter.test.ts
- packages/jsapi-components/src/useDebouncedViewportSelectionFilter.ts
- packages/jsapi-components/src/usePickerWithSelectedValues.test.ts
- packages/jsapi-components/src/usePickerWithSelectedValues.ts
- packages/react-hooks/src/useDebouncedValue.test.ts
- packages/react-hooks/src/useDebouncedValue.ts
Supports DH-16336:
- Added an `isDebouncing` prop to `useDebouncedValue`
- Added support for search text trimming to `usePickerWithSelectedValues`
- Introduced a validation delay to account for viewport filtering to improve UX and avoid flicker of validation message
resolves #1747
Note that there's not any place in DHC that uses the `usePickerWithSelectedValues` hook yet. I've been testing locally as part of DH-16336.
BREAKING CHANGE: `usePickerWithSelectedValues` now takes an object as an argument instead of positional args
> feat: DH-16336: usePickerWithSelectedValues - boolean flags should be calculated based on trimmed search text

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/jsapi-types/src/dh.types.ts
Removing databar specific JSAPI code since this API will be moved to dh.ui at some point
> refactor: Remove JSAPI databar code

- packages/iris-grid/src/IrisGridTableModel.ts
- When there are no partition columns, we should just load the whole table instead of hanging
- Tested with the snippet in the ticket
- Fixes #1763
> fix: Load full uncoalesced table if no partition columns available

- packages/dashboard-core-plugins/src/ChartPanelPlugin.tsx
- packages/dashboard-core-plugins/src/ChartPluginConfig.ts
- packages/dashboard-core-plugins/src/ChartWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/GridPanelPlugin.tsx
- packages/dashboard-core-plugins/src/PandasPanelPlugin.tsx
- packages/dashboard-core-plugins/src/PandasPluginConfig.ts
- packages/dashboard-core-plugins/src/PandasWidgetPlugin.tsx
- packages/plugin/src/PluginTypes.ts
I missed making `WidgetPanelProps` generic in the last PR which is needed to version bump plotly express.
resolves #1759
> fix: Made some plugin types generic

- packages/code-studio/src/main/AppMainContainer.tsx
When developing, the prompt to reload is a pretty annoying feature. I am not worried about lost query progress in dev mode, auto-refresh is more important.
> feat: disable "Changes you made may not be saved." prompt in dev mode

- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.test.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
- Fixes #1645 
- Moves are now generated for frozen columns (like front/end for initial moved columns) and only used when sorting
- The range being sorted is truncated to remove frozen/front/end columns
- Added tests to make sure the sort is correct
> fix: sorting frozen columns

- packages/dashboard/src/layout/LayoutUtils.test.ts
- packages/dashboard/src/layout/LayoutUtils.ts
`LayoutUtils.isEqual` gives a false negative when we compare a dehydrated layout having any undefined property with the same layout passed through `JSON.serialize`/`JSON.parse`, because all undefined properties get deleted when serialized.
Fixes DH-16463
> fix: DH-16463: isEqual returns false for layouts with undefined and missing props in panelState

- packages/components/src/theme/ThemeModel.ts
- packages/components/src/theme/__snapshots__/ThemeUtils.test.ts.snap
DH-16461: Preload --dh-color-text-highlight
**Testing**
This doesn't actually impact anything in DHC. If you want to test in DHE, see test plan on DH-16461 and run `npm run start-community` in DHE.
> fix: DH-16461: Preload --dh-color-text-highlight (#1780)

- packages/components/scss/BaseStyleSheet.scss
Chrome adopted offical support for scrollbar-color in chrome 121. However, if you have both scrollbar-color and ::webkit-scrollbar styling, they conflict and chrome will only honour the native styling. This is bad because the native chrome mac scrollbars become really small, and overlap too much with out golden-layout drag.
Our webkit styling forces scrollbars that match monaco and grid, and are preferred. By removing `scrollbar-color` native styling, our webkit styles work. We only had scrollbar-color to style firefox in dark mode (`//applies to firefox only` is no longer true), however the most recent versions of firefox appear to color scrollbars automatically based on the theme, so this is no longer necessary.
The crappy part here is since this is browser change, we will have to …
> fix: address chrome 121 scrollbar style behaviour change

- packages/components/scss/BaseStyleSheet.scss
Chrome adopted offical support for scrollbar-color in chrome 121. However, if you have both scrollbar-color and ::webkit-scrollbar styling, they conflict and chrome will only honour the native styling. This is bad because the native chrome mac scrollbars become really small, and overlap too much with out golden-layout drag.
Our webkit styling forces scrollbars that match monaco and grid, and are preferred. By removing `scrollbar-color` native styling, our webkit styles work. We only had scrollbar-color to style firefox in dark mode (`//applies to firefox only` is no longer true), however the most recent versions of firefox appear to color scrollbars automatically based on the theme, so this is no longer necessary.
The crappy part here is since this is browser change, we will have to …
> fix: address chrome 121 scrollbar style behaviour change (#1787)

- packages/chart/src/ChartUtils.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/iris-grid/src/sidebar/ChartBuilder.tsx
I noticed this issue while investigating https://github.com/deephaven/deephaven-plugins/issues/179 and switching a param of `(v)  => this.chartUtils.unwrapValue(v)` to just `this.chartUtils.unwrapValue`
Looked through the other de-globalization PRs and added `bindAllMethods` to any classes where there were some static methods moved to non-static so that they can be used this way
> fix: Bind this to utils that moved from static to non-static with js api de-globalization

- packages/code-studio/src/settings/FormattingSectionContent.tsx
- packages/code-studio/src/storage/LocalWorkspaceStorage.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/jsapi-utils/src/Formatter.ts
- packages/jsapi-utils/src/Settings.ts
- packages/redux/src/selectors.ts
- packages/redux/src/store.ts
- Adds #1646 
- Add a new state in Redux for if empty and null should be rendered
- Add a check in `IrisGridTableModelTemplate` to check for if the setting is enabled
> feat: toggle empty/null rendering

- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useDelay.test.ts
- packages/react-hooks/src/useDelay.ts
useDelay hook that returns true until a delay timeout has completed then returns false.
resolves #1807
> feat: useDelay hook

- playwright.config.ts
- tests/context-menu.spec.ts
- tests/table-multiselect.spec.ts
- tests/utils.ts
- Fixes #1799 
- Add a check that `.loading-spinner` disappears before locating and clicking the Go To button
Multiselect values (#1736) turned the filter options to be async. This results in the context menu having a loading spinner at the bottom for a few milliseconds. Flakiness happens when the filter options are resolved between the Go To value being located and pressed.
- Add a check for the loading spinner after opening a table/plot
- Add a check for .`iris-grid-loading-status-bar` after applying filter
Upon opening a table/plot, the loading indicator is a `.loading-spinner` instead of `.iris-grid-loading-status`. As such, the check is passed. This causes the mouse click to happen even though the grid isn't loaded yet and Playwright is waiting for a context menu to appear when …
> test: fix flaky tests

- packages/embed-widget/vite.config.ts
- embed-widget loads plugins to load widgets
- Proxy the embed-widget app as well as code-studio so that we can test with plugins
- embed-grid/embed-chart don't use plugins, so no need to proxy there
> build: Proxy plugins in the embed-widget app

- packages/console/src/command-history/CommandHistoryActions.test.tsx
- packages/jsapi-components/src/usePickerWithSelectedValues.test.ts
- packages/utils/src/MockProxy.test.ts
- packages/utils/src/MockProxy.ts
- packages/utils/src/TestUtils.test.tsx
- packages/utils/src/TestUtils.ts
- packages/utils/src/TypeUtils.ts
New test util features
- Generate exhaustive boolean combinations
- Fixed some type errors in `usePickerWithSelectedValues.test.ts` (also updated it to use the new boolean test util)
- Added spread support to MockProxy to avoid empty objects when making copies
- Fixed a console error that was happening due to `null` icons passed to FontAwesomeIcon component in tests
resolves #1809
> feat: Test Utils - Generate exhaustive boolean combinations and MockProxy spread

- package-lock.json
- packages/dashboard-core-plugins/package.json
- Fix #1817 
- Downgrade `remark-gfm` to `3.0.1`, as its release date is more inline with all the other Markdown related packages
> fix: inline blocks throw error in md notebook

- packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
Moves a DHE fix to DHC.
fixes text field spectrum validation icon position: 
BREAKING CHANGE: the duplicate `spectrum-Textfield-validationIcon` css in DHE should be removed
> fix: spectrum textfield validation icon position with set content-box

- packages/grid/src/Grid.tsx
- packages/grid/src/GridRenderer.ts
- packages/grid/src/GridTheme.ts
- packages/iris-grid/src/IrisGrid.scss
- packages/iris-grid/src/IrisGridTheme.module.scss
- packages/iris-grid/src/IrisGridTheme.ts
- packages/iris-grid/src/__snapshots__/IrisGridTheme.test.ts.snap
- change cell input to not go off edge
- makes activeCellSelectionBorderWidth a theme variable, so it can be shared with js and css
- change canvas active cell outline to only stick to edge if at left edge of screen, not in any column
- re-style active cell input to match latest input variables
- change outline of input to use selection border color
active cell input in the first column fully onscreen, before:
after:
cell selected but not active, and partially scrolled offscreen, before:
after:
> fix: keep active cell selection in first column from going offscreen

- packages/dashboard-core-plugins/src/linker/LinkerLink.scss
fixes #1838
Testing Performed
- Open 2 tables
- ctrl / cmd + L to show linker popup
- click cell in 1 table then cell in other
- hover over dotted arrow and click alt
- should see chain link with slash through it
> fix: Fixed svg url

- tests/context-menu.spec.ts
- tests/figure.spec.ts
- tests/table-gotorow.spec.ts
- tests/table-multiselect.spec.ts
- tests/table-operations.spec.ts
- tests/table.spec.ts
- tests/utils.ts
- Adds #1815 
- Move all `page.goto` out of the `openObject` util method and into each test
- Add util function for to go to page and wait for load
- Fixes #1816 
- Use app panel menu instead of console panel menu
- Add check that a new panel is created in `openTable` and `openPlot`
> test: improve openPanel

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/code-studio/src/storage/LocalWorkspaceStorage.ts
- packages/dashboard/src/DashboardEvents.ts
- packages/dashboard/src/redux/hooks.ts
- packages/dashboard/src/redux/selectors.ts
- packages/redux/src/store.ts
- Until we have support for #1746 , load the default dashboard data from workspace
- Needed for testing the widget hydration PR
- Tested with my changes for widget hydration
- Ensured deephaven.ui widgets re-opened upon refresh
- Ensured links remained between existing tables
> fix: Load default dashboard data from workspace data

- packages/app-utils/src/plugins/PluginUtils.test.ts
- packages/app-utils/src/plugins/PluginUtils.tsx
- packages/plugin/src/PluginTypes.test.ts
- packages/plugin/src/PluginTypes.ts
We should be able to use both new and legacy plugin format in the same module, and plugin loader should prioritize the new format.
> feat: Plugin loader should prioritize new plugin format, when available

- playwright.config.ts
- tests/utils.ts
- Fixes #1845 
- Add an expect for loading spinner to disappear
The expects will be in the following order:
1. Table panel is loaded (new `.iris-grid-panel` appears)
2. Grid is lazy loaded (`.iris-grid-panel .loading-spinner` is gone)
3. Grid content is loaded (`.iris-grid .iris-grid-loading-status` is gone)
> test: fix open table flakiness

- tests/table-operations.spec.ts
- Resolves #1553
- Renable the table operations drag test, which is now flaky instead of failing
> test: enable drag test

- packages/iris-grid/src/IrisGrid.tsx
- Fix #1822 
- Add a check for `isExpandAllAvailable` to render the list on the tooltip
> fix: hide expand all when not available

- packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/mousehandlers/IrisGridDataSelectMouseHandler.ts
- Move the doubleClick behaviour from IrisGridDataSelectMouseHandler into GridSelectionMouseHandler, so it's baked into Grid itself (double-clicking a grid in the styleguide was exhibiting erroneous behaviour)
- Allow passing in mouseHandlers to IrisGrid. Will be necessary to support https://github.com/deephaven/deephaven-plugins/issues/320
- Tested using my branch for `on_row_press` support on deephaven.ui: https://github.com/deephaven/deephaven-plugins/pull/346
- Verified Linker still worked as expected
> feat: Add support to pass in mouseHandlers into IrisGrid

- packages/iris-grid/src/GotoRow.tsx
- tests/context-menu.spec.ts
- Fixes #1826 
- Swap "Previous match" and "Next match"
> fix: swap goto tooltips

- packages/components/src/spectrum/Flex.tsx
- packages/components/src/spectrum/index.ts
Simple wrapping of the flex component.
I don't see anything we need to custiomize, so just re-export it I guess.
> feat: expose spectrum `Flex` component as wrapped deephaven component

- package-lock.json
- packages/app-utils/package.json
- packages/auth-plugins/package.json
- packages/chart/package.json
- packages/components/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/dashboard/package.json
- packages/file-explorer/package.json
- packages/golden-layout/package.json
- packages/grid/package.json
- packages/iris-grid/package.json
- packages/jsapi-bootstrap/package.json
- packages/jsapi-components/package.json
- packages/plugin/package.json
- packages/pouch-storage/package.json
- packages/react-hooks/package.json
- packages/storage/package.json
Fixes #1863 
I did `>=16.8.0` because React 17 release notes say "no new features", so we should really be fine with any React that supports hooks. From what I can tell, no changes in React 18 should cause bugs with our packages
In the future if we implement any React 18 specific features we'll need to update the peer deps for those packages.
When React 19 starts publishing alphas/betas I think we would need to bump again (if anybody is testing on react 19 pre-release) to include a `|| 19.0.0-beta.0` or whatever version pattern they use as `>=16.8.0` does not match pre-release versions
> chore: Update react peer dependency versions

- packages/code-studio/src/storage/LocalWorkspaceStorage.ts
- When loading a default layout, the `pluginDataMap` wasn't getting pulled in
> fix: Loading workspace plugin data

- .github/workflows/audit-fix.yml
- .github/workflows/cla.yml
- .github/workflows/e2e.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/publish-packages.yml
- .github/workflows/unit.yml
The only action that is still on Node 16 is the CLA action. I updated it from the Node 12 to Node 16 version though. Also, they changed the repo name, but I didn't see anything in the changelog about it. I did find the commit changing their readme though [here](https://github.com/contributor-assistant/github-action/commit/b2a7f9fb90217ea0b8a0c95c288221457be4a31f)
The only action I saw with a breaking change was `upload-artifact`. We don't use any of the cases in this repo where the breaking change would effect us. [Migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
> chore: Update github actions to Node 20

- packages/components/src/spectrum/forms.ts
`npm start` should work now without the `@react-types/textfield` error.
> fix: Fixed re-export (#1894)

- package-lock.json
- packages/chart/package.json
This adds an explicit dependency to `buffer` to `@deephaven/chart` which we currently get implicitly from `browserify` in `golden-layout`. `plotly.js` depends on `typedarray-pool` which depends on `buffer`, but doesn't list it.
I opened a PR with `typedarray-pool`, but doesn't seem it's an active repo any more. https://github.com/mikolalysenko/typedarray-pool/pull/11
The docs uses webpack 5 w/ docusaurus and I added `buffer` when adding chart support, so this should be all that's needed. https://github.com/deephaven/deephaven.io/commit/6a8bcf29fe32dea1825c6d7f682857cc33b59109#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
> chore: Add buffer as a chart dependency

- packages/console/src/ConsoleInput.tsx
- packages/console/src/notebook/Editor.tsx
- packages/iris-grid/src/sidebar/InputEditor.tsx
Checked enterprise and we don't call `editor.create` anywhere there. We should really centralize these in `MonacoUtils` with a `createEditor` or something, but not doing that here.
> feat: Change autoclosing bracket behavior to beforeWhitespace

- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
- We didn't check if the partition was `null` before adding it to an array
- Was setting a partition of `[null]` for all migrated tables
- Fix up unit tests to actually check the results instead of just checking against the object passed in
> fix: Invalid migration of legacy partitions

- packages/console/src/Console.tsx
- packages/console/src/console-history/ConsoleHistoryItem.tsx
- packages/console/src/csv/CsvTypeParser.ts
- Fix adding error console history items
- They weren't appearing as anything because the command was `''` instead of `undefined`
- Map LOCAL_TIME to STRING on CSV import
- `LOCAL_TIME` isn't supported on the server in DHC, and isn't really "safe" anyways since we should have other info in there as well (e.g. date or time zone)
- When exporting, should be exporting the 'unformatted' value, which gives you the full timestamp
- By mapping to String, user can then do an `.update_view` to map it to a timestamp if they wish
- Fixes #1432
- Cherry-pick back for DH-15013. Tested against dev-vermilion.
> fix: Cannot import CSV with LOCAL_TIME (#1434)

- packages/code-studio/src/log/LogExport.ts
- Adds #1245 
- Add a replacer function to all `JSON.stringify` to filter out blacklisted path
- Add the following paths to blacklist: `api`, `client`, `dashboardData.defaultLayout.connection`, `layoutStorage`, `storage`
> feat: log export blacklist

- packages/iris-grid/src/IrisGrid.scss
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridModelUpdater.tsx
- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- Adds #1865
- Add a check for if there is still data being loaded in the viewport
- Add a new loading message if the above is true for >500ms
- Add state to determine whether `startLoading` will block the grid or show the cancel button
> feat: improve table loading

- packages/grid/src/GridRenderer.ts
- packages/grid/src/mouse-handlers/GridColumnMoveMouseHandler.ts
- packages/grid/src/mouse-handlers/GridSeparatorMouseHandler.ts
- Shouldn't throw in those cases, we should handle when calculatedSizes is empty
- Found when using out [deephaven-doom](https://github.com/mofojed/deephaven-doom), couldn't resize/move columns like expected
- Also tested in the styleguide - dragging columns when there were row headers visible did not work correctly
> fix: Fix issues when auto-size columns/rows is false, and when row headers are not 0

- packages/chart/src/Chart.tsx
- tests/figure.spec.ts
- set responsive config to true which allows plots to properly grow and shrink
- removed unnecessary useResizeHandler (which only watches window), as we have our own observer
- fixed failing test by changing locator to plotly parent container. Responsive setting has an absolutely positioned child that makes the other locator have zero height,
Tested with the following script, and resizing golden-layout panels both vertically and horizontally and resizing browser window horizontally and vertically.
```py
from deephaven import ui, empty_table
from deephaven.plot import express as dx
t = empty_table(100).update(["x = i", "y = i"])
p = dx.line(t, x="x", y="y")
@ui.component
def common_example():
return ui.panel(
ui.flex(
ui.text_field(label="Text Field"),
ui.text_field(label="Text Field"), …
```
> fix: allow plotly plots to shrink inside ui.flex/grid layouts

- packages/code-studio/src/main/AppInit.tsx
- packages/code-studio/src/main/AppMainContainer.tsx
- packages/components/src/navigation/NavTab.tsx
- packages/components/src/navigation/NavTabList.tsx
Fixes #1794
- Label home as "vsTerminal Code Studio"
- Make it part of the navtab list to get an active state
- Allow navtab list to accept an Icon | JSX.Element
> feat: replace code studio home icon with "Code Studio" as label

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.tsx
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/jsapi-components/src/TableDropdown.tsx
- packages/jsapi-utils/src/TableUtils.ts
Closes #1867
Tested in Enterprise using steps from DH-16595 - created a partitioned table and set ACL to `nullFilterGenerator()` to get the `null` value in the partition column. Creating a partitioned table with a `null` in the partition column doesn't seem possible with `db.addTablePartition`  in Enterprise.
```
t=db.t("LearnDeephaven", "StockTrades").where()
db.addPartitionedTableDefinition("<namespace>", "partTable", "Date", t.getDefinition())
test = db.t("<namespace>" , "partTable")
// Set Column ACL on `partTable` to `new NullFilterGenerator()` in swing
test = db.t("<namespace>" , "partTable")
```
Core+ Groovy console:
```
t = emptyTable(1).update("X=(String)null","Y=ii").partitionBy("X")
```
> fix: DH-16595: Fix null partition filter

- package-lock.json
- package.json
- packages/app-utils/package.json
- packages/auth-plugins/package.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/console/package.json
- packages/dashboard-core-plugins/package.json
- packages/embed-widget/package.json
- packages/iris-grid/package.json
- packages/jsapi-bootstrap/package.json
- packages/jsapi-components/package.json
- packages/jsapi-shim/package.json
- packages/jsapi-utils/package.json
- packages/plugin/package.json
- packages/redux/package.json
Updated @deephaven/jsapi-types to 1.0.0-dev0.34.0
resolves #1974
> chore: Updated @deephaven/jsapi-types to 1.0.0-dev0.34.0

- package-lock.json
- packages/chart/package.json
- packages/chart/src/Chart.tsx
- packages/dashboard-core-plugins/package.json
- packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx
- packages/dashboard-core-plugins/src/redux/actions.ts
- packages/dashboard/package.json
- packages/dashboard/src/layout/LayoutUtils.ts
- packages/iris-grid/package.json
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/mousehandlers/IrisGridCellOverflowMouseHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridRowTreeMouseHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridTokenMouseHandler.ts
- packages/iris-grid/src/sidebar/SelectDistinctBuilder.tsx
- packages/redux/package.json
- packages/redux/src/reducers/common/replaceByIdReducer.ts
- Benchmark results: https://www.npmjs.com/package/fast-deep-equal#performance-benchmark
- Tested to make sure notebook lag was reduced (typing in a Notebook with a dashboard with many components)
- Continue using `deep-equal` package in the `IrisGridUtils.test.ts`, as that test requires the `strict: true`. It is only included as a devDependency
> perf: Use `fast-deep-equal` instead of `deep-equal

- packages/dashboard/src/DashboardLayout.tsx
- packages/react-hooks/package.json
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useDebouncedCallback.test.ts
- packages/react-hooks/src/useThrottledCallback.test.ts
- packages/react-hooks/src/useThrottledCallback.ts
- We were checking the diff of the layouts on each keystroke
- DashboardLayout should debounce checking that diff
- Tested by displaying FPS counter, having a Code Studio with a bunch of tables in it, adding a notebook, and then typing in it. FPS is much higher after the change
> fix: Typing in notebooks is laggy

- packages/iris-grid/src/ColumnStatistics.tsx
Had double padding on it, looked weird.
> fix: remove extra padding on column statistic refresh button

- package-lock.json
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/redux/package.json
- packages/redux/src/selectors.ts
Discovered as part of #1977 investigation. Typing in a notebook triggers a workspace update, which was triggering all tables to re-render. Removed deprecated dependeny of workspace from iris-grid.
Further settings is derived from workspace and returns a new settings object. Iris-grid depends on settings, but the object had no changes. Memoize the selector so it always returns the same object if settings haven't changed.
Removes ~100ms of lag that was occuring 400ms after the debounce of notebook key press events.
BREAKING CHANGE: getPluginContent deprecatedProps have been removed from iris-grid
> perf: remove workspace dependancy from iris-grid-panel and memoize settings redux selector

- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
Removed orphaned code that used to do things, but now doesn't do anything but update an unused isFocused state variable. This was causing an additional re-render on focus when state was then updated.
> perf: remove focus tracking in notebook panel causing extra re-render

- packages/components/src/spectrum/listView/ListView.tsx
Wired up ListView props I missed on refactor.
> fix: Fixed ListView props

- packages/jsapi-components/src/useDebouncedViewportSelectionFilter.test.ts
- packages/jsapi-components/src/useDebouncedViewportSelectionFilter.ts
- packages/react-hooks/src/SelectionUtils.test.ts
- packages/react-hooks/src/SelectionUtils.ts
- packages/react-hooks/src/useMappedSelection.test.ts
- packages/react-hooks/src/useMappedSelection.ts
fixes root issue of DH-16914
I published this as an alpha for DHE testing: 
[0.76.1-alpha-optimize-selection-get-key.0](https://www.npmjs.com/package/@deephaven/react-hooks/v/0.76.1-alpha-optimize-selection-get-key.0)
BREAKING CHANGE: @deephaven/react-hooks: `SelectionUtils.optimizeSelection` and `useMappedSelection` require additional `getKey` arg
> fix: Added `getKey` to `SelectionUtils.optimizeSelection`

- packages/components/src/navigation/NavTab.test.tsx
- packages/components/src/navigation/NavTab.tsx
Resolves #1990
- Add functionality to close dashboard tab with middle mouse click by specifying onAuxClick event
- Create NavBar component test cases that test changes
> feat: add middle click dashboard tab deletion

- packages/grid/src/GridRenderer.ts
- Each GridRenderer had an independent cache for checking various colour operations, instead use a shared cache
- Grids are likely to share the same colours because they have similar themes anyway
- Improves performance when opening dashboards with lots of grids
> perf: Improve performance of lots of grids in a dashboard

- packages/jsapi-components/src/useTableSize.test.ts
- packages/jsapi-components/src/useTableSize.ts
- packages/jsapi-components/src/useViewportData.ts
fixes #2003 - useViewportData - re-subscribes to table any time ViewportData changes
- Memoized `dh.Table.EVENT_SIZECHANGED` handler
- Memoized `dh.Table.EVENT_UPDATED` handler
fixes #1928 - useViewportData - setViewport should maintain last firstRow value when table size changes
- Track last set "first row" to be re-used when table size changes but table reference remains the same
**Tested**
- Ticking table 
- table update subscriptions no longer occur on each viewportData change
- size change handler no longer re-subscribes on every render
- ACL Editor - scrolling viewport data still works. Filtering still properly resets viewport to zero
> fix: useViewportData - memoize subscriptions and first row of viewport

- jest.config.base.cjs
- packages/pouch-storage/src/PouchStorageTable.test.ts
- packages/pouch-storage/src/PouchStorageTable.ts
Resolves https://github.com/deephaven/web-client-ui/issues/1505
Changes:
- Modified `PouchFilter` type to use $ne instead of $neq
- Modified `$regex` prop to be able to accept `RegExp` and `string`, rather than just string by default
Steps Moving Forward:
- Code change is implemented, having difficulty with imports when trying to run Unit Tests (did not commit the file yet)
Update: Apparently, there are some issues with PouchDB and jest tests, since it has not been updated to an ES6 module. (https://stackoverflow.com/questions/64905287/import-error-when-running-jest-tests-that-use-the-pouchdb-asyncstorage-adapter). Could create a `babel.config.js`, but not sure if we want to do that just for a function that is never used beyond an internal scope. Thus, going to **omit** unit tests for …
> fix: PouchStorageTable using incorrect $ne operator

- packages/iris-grid/src/IrisGridPartitionSelector.test.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.tsx
Resolves https://github.com/deephaven/web-client-ui/issues/1970
**Changes Implemented:**
- Replace TableDropdown with Picker for the Partition Selector for Iris Grid
- Change corresponding test, since role is no longer "combobox"
**Testing Information:**
Code used:
```
t = empty_table(15000).update(["x = i", "y = i"]).partition_by(["x"]) 
```
Sample visual of new Picker:
> fix: Use picker for iris grid partition selector 

- playwright.config.ts
Shaved about a minute off locally for me, but I didn't get a clean run because of some styleguide timeouts still.
> test: speed up e2e tests by retaining videos only on retry

- packages/components/src/spectrum/buttons.ts
- packages/components/src/spectrum/forms.ts
Re-export Spectrum button and checkbox
> feat: Re-export Spectrum button and checkbox

- .github/workflows/e2e.yml
- tests/console.spec.ts
Fixes #2044
Infra PR https://github.com/deephaven/infra/pull/301
You can see the e2e-results job failed on my 2nd commit to this PR. It should fail if any of the matrix jobs fail or are cancelled.
> fix: e2e test status reporting incorrectly

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTestUtils.ts
- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
- Related to DH-17076
- Needed a Core patch: https://github.com/deephaven/deephaven-core/pull/5555
- Tested using both the Groovy snippet from the ticket
- Fixes #2035
> fix: DH-17076 LayoutHints on TreeTables were not being applied

- lerna.json
- package-lock.json
- package.json
- This template sorts Breaking Changes, Features, Fixes, and then everything else which is what we want
- Sort order defined by the config. See [constants.js](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/src/constants.js) and [commitGroupOrder](https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/conventional-changelog-conventionalcommits/src/writer.js#L70C9-L70C25)
- It also puts Breaking Changes first (which are just notes) [in the template](https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/conventional-changelog-conventionalcommits/src/templates/template.hbs#L5).
- See …
> build: Use conventionalcommits template instead of Angular

- package-lock.json
- packages/app-utils/src/components/ConnectionBootstrap.tsx
- packages/jsapi-bootstrap/package.json
- packages/jsapi-bootstrap/src/index.ts
- packages/jsapi-bootstrap/src/useObjectFetch.test.ts
- packages/jsapi-bootstrap/src/useObjectFetch.test.tsx
- packages/jsapi-bootstrap/src/useObjectFetch.ts
- packages/jsapi-bootstrap/src/useWidget.test.tsx
- packages/jsapi-bootstrap/src/useWidget.ts
- packages/jsapi-bootstrap/tsconfig.json
- Hook for loading a widget that makes it easy to use
- `ObjectManager` context allows for implementation to handle loading the object
- On Core side, we have a very simple `ObjectManager`, as we just have one connection
- On Enterprise side, the `ObjectManager` provided to the context manager will need to handle fetching from queries, and will be able to handle more scenarios (such as when a query is restarting)
- Use with https://github.com/deephaven/deephaven-plugins/pull/502
> feat: DH-16737 Add ObjectManager, `useWidget` hook

- package-lock.json
- packages/app-utils/src/components/ConnectionBootstrap.tsx
- packages/jsapi-bootstrap/package.json
- packages/jsapi-bootstrap/src/index.ts
- packages/jsapi-bootstrap/src/useObjectFetch.test.tsx
- packages/jsapi-bootstrap/src/useObjectFetch.ts
- packages/jsapi-bootstrap/src/useWidget.test.tsx
- packages/jsapi-bootstrap/src/useWidget.ts
- packages/jsapi-bootstrap/tsconfig.json
- Hook for loading a widget that makes it easy to use
- `ObjectManager` context allows for implementation to handle loading
the object
- On Core side, we have a very simple `ObjectManager`, as we just have
one connection
- On Enterprise side, the `ObjectManager` provided to the context
manager will need to handle fetching from queries, and will be able to
handle more scenarios (such as when a query is restarting)
- Use with https://github.com/deephaven/deephaven-plugins/pull/502
> feat: DH-16737 Add ObjectManager, `useWidget` hook (#2030)

- packages/components/src/spectrum/forms.ts
Looks like I exported the incorrect Radio component prop types in previous PR. There are apparently extended ones for Spectrum.
https://github.com/adobe/react-spectrum/blob/7da3d384aa0c6bdc14449c4f138e963a094a7a38/packages/%40react-types/radio/src/index.d.ts#L58-L71
#2020
> fix: Exporting correct Radio prop types

- lerna.json
- Publishing new versions shouldn't clobber the `latest` tag, since this is a release branch
> build: Update distTag to v0.78 instead of `latest` for v0.78 branch

- packages/embed-widget/src/App.tsx
This should fix embed-widget not showing the panel headers when there are multiple panels in a widget, but it's not a dashboard.
The issue is embed-widget is loading the layout from `dashboardData` and the `DEFAULT_DASHBOARD_ID` stores its data in `workspaceData` while all other IDs use `dashboardData`.
Tested with widget with just 1 panel, widget with multiple panels, and widget that is a dashboard.
> fix: Embed-widget with multiple panels not showing panel headers

- packages/components/src/DateTimeInput.tsx
- packages/components/src/index.ts
- Don't allow an undefined to be returned
- Export more types
> fix: A few small cleanups for DateTimeInput

- packages/iris-grid/src/IrisGridTreeTableModel.ts
Provide an initializer for the optional `formatValue` argument in `IrisGridTreeTableModel` `snapshot` method.
Remove the conditional that caused the `resultRow` to be an empty array when the `formatValue` argument isn't provided.
> fix: DH-17199: Filter by value in the tree table context menu always shows null 

- packages/console/src/Console.tsx
Resolves https://github.com/deephaven/web-client-ui/issues/2060
**Changes Implemented:**
- Added `isStuckToBottom` state that is updated on each scroll (in `handleScrollPaneScroll`), then in `componentDidUpdate`, call the `scrollConsoleHistoryToBottom` based on `isStuckToBottom`
> fix: Console scroll bar following dynamic output

- packages/react-hooks/src/ElementUtils.test.tsx
- packages/react-hooks/src/ElementUtils.ts
I missed the 2nd generic argument when I first wrote this util which made the `type` property resolve to `string | React.JSXElementConstructor<any>` in certain cases instead of the actual type. This should fix that.
resolves #2094
> fix: `isElementOfType` Improved type inference

- packages/console/src/Console.tsx
Noticed running code from a notebook wasn't scrolling to the bottom.
I didn't catch this behavior changing in #2076, but looks like the `componentDidUpdate` doesn't necessarily wait until after the paint or the ref isn't updated for some reason. So the `scrollHeight` can be the old value and then `scrollTo` (or `scrollTop = scrollHeight`) triggers the `scroll` event which sets `isStuckToBottom` to false. Not exactly sure 
The `requestAnimationFrame` call seems to be working. The other option I thought of what ignoring programmatic scrolling, but the only way I saw to do that was to set some state in the class and then check it in the scroll handler and reset it after. There's nothing about the event that indicates if it was triggered via `scrollTo`.
There were some weird update values …
> fix: Console does not scroll to bottom when code run from notebook

- packages/components/src/spectrum/utils/itemUtils.test.tsx
- packages/components/src/spectrum/utils/itemUtils.ts
- packages/components/src/spectrum/utils/useRenderNormalizedItem.test.tsx
- packages/components/src/spectrum/utils/useRenderNormalizedItem.tsx
Resolves https://github.com/deephaven/web-client-ui/issues/2112
> fix: make textValue default to key for Normalized Item

- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Needed for proper TS in https://github.com/deephaven/deephaven-plugins/pull/522. Otherwise the class complains it can't properly extend `IrisGridContextMenuHandler`.
> fix: Update IrisGridContextMenuHandler getHeaderActions return type to be more permissive

- packages/iris-grid/src/GotoRow.tsx
- packages/iris-grid/src/IrisGridProxyModel.ts
This makes `IrisGridProxyModel` use an actual Proxy instead of requiring us pass through most of the calls to the underlying model.
The proxy will check if the `IrisGridProxyModel` class implements a method first. If it does, then it calls the implemented method. If it does not, it delegates the call to the current `model`
Many of the methods which had a check for a specific model type first can also be handled by the proxy. A caller is must use that check first anyway or else TS will complain. So the check was really being done twice before
Didn't look into it too hard, but I disabled the TS check for `extends IrisGridModel`. There are many abstract methods in `IrisGridModel` which are implemented by the proxy handling them, but TS doesn't know that.
> refactor: Make IrisGridProxyModel use an actual Proxy

- packages/components/src/spectrum/comboBox/ComboBox.tsx
- Wasn't allowing a ref to be passed in to ComboBox
> fix: Allow ComboBox to accept the FocusableRef for ref

- packages/components/src/spectrum/comboBox/ComboBox.tsx
- packages/components/src/spectrum/picker/Picker.tsx
- packages/components/src/spectrum/picker/useMultiRef.test.ts
- packages/components/src/spectrum/picker/useMultiRef.ts
- Pass through ref to SpectrumPicker correctly
- Added a `useMultiRef` hook for handling multiple refs being passed in
> fix: Ref was not being passed through for Picker

- packages/components/src/spectrum/shared.ts
Resolves https://github.com/deephaven/web-client-ui/issues/2084
**Steps Moving Forward:**
- Once this PR has merged, will go into plugins repo and use the re-exported types, and remove @react-types/shared dependency (in order to further eliminate spectrum dependency)
> fix: re-export remaining types needed by dh ui from @react-types/shared

- packages/code-studio/src/styleguide/ListViews.tsx
- packages/code-studio/src/styleguide/Pickers.tsx
- packages/components/src/UIConstants.ts
- packages/components/src/actions/ConfirmActionButton.tsx
- packages/components/src/actions/IconActionButton.tsx
- packages/components/src/index.ts
- packages/components/src/spectrum/comboBox/ComboBox.tsx
- packages/components/src/spectrum/picker/Picker.tsx
- packages/components/src/spectrum/picker/usePickerItemScale.test.ts
- packages/components/src/spectrum/picker/usePickerItemScale.ts
- packages/components/src/spectrum/picker/usePickerProps.ts
- packages/jsapi-components/src/Constants.ts
- packages/jsapi-components/src/spectrum/ListView.tsx
- packages/jsapi-components/src/spectrum/utils/usePickerProps.ts
- packages/jsapi-components/src/usePickerWithSelectedValues.test.ts
- packages/jsapi-components/src/usePickerWithSelectedValues.ts
- packages/jsapi-components/src/useSearchableViewportData.test.ts
- packages/jsapi-components/src/useSearchableViewportData.ts
- packages/jsapi-components/src/useViewportData.test.tsx
- packages/jsapi-components/src/useViewportData.ts
- packages/jsapi-utils/src/ViewportDataUtils.test.ts
- packages/jsapi-utils/src/ViewportDataUtils.ts
- packages/react-hooks/src/useSpectrumDisableSpellcheckRef.test.ts
- packages/react-hooks/src/useSpectrumDisableSpellcheckRef.ts
- packages/utils/src/UIConstants.ts
- Moved some UI constants to @deephaven/components and deprecated the current ones
- Added `displayName` to Picker and ComboBox to fix unit test React key warnings
resolves #1973
> refactor: 1973 UI constants

- packages/iris-grid/src/IrisGridTreeTableModel.ts
Resolves https://github.com/deephaven/web-client-ui/issues/2029
**Changes Implemented:** 
- Added null check when call formatValue function, to ensure that it is only called when it is defined
> fix: Console error when opening context menu on tree table (#2047)

- packages/chart/src/Chart.tsx
- packages/chart/src/ChartModel.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.ts
- packages/code-studio/src/settings/AdvancedSectionContent.tsx
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/code-studio/src/storage/LocalWorkspaceStorage.ts
- packages/components/src/theme/theme-dark/theme-dark-components.css
- packages/components/src/theme/theme-light/theme-light-components.css
- packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
- packages/dashboard/src/redux/selectors.ts
- packages/jsapi-utils/src/Settings.ts
- packages/redux/src/selectors.ts
- packages/redux/src/store.ts
- Cherry-picked from 011eb33b067412ffb6362237c9f6dc7256476bcd
- Advanced Settings section in the Settings menu, with an option to disable WebGL
- Read from the server config for default values
- web.webgl: default setting for WebGL being enabled or not
- web.webgl.editable: disallow the user from enabling WebGL
- Contextual Help item to add more info
- Tested by adding the following to the deephaven.prop config:
```
web.webgl=false
web.webgl.editable=false
client.configuration.list=java.version,deephaven.version,barrage.version,http.session.durationMs,file.separator,web.storage.layout.directory,web.storage.notebook.directory,web.webgl,web.webgl.editable
```
---------
> feat: Add option to disable WebGL rendering (#2134)

- packages/iris-grid/src/IrisGridTreeTableModel.ts
- Cherry-picked from `4eb38dd2c47071516269662f8a975044e6bb0a9a`
- Needed for DH-17420
Provide an initializer for the optional `formatValue` argument in `IrisGridTreeTableModel` `snapshot` method.
Remove the conditional that caused the `resultRow` to be an empty array when the `formatValue` argument isn't provided.
> fix: DH-17199: Filter by value in the tree table context menu always shows null

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/code-studio/src/styleguide/StyleGuide.tsx
- packages/code-studio/src/styleguide/XComponents.tsx
- packages/dashboard-core-plugins/src/WidgetLoaderPlugin.tsx
- packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
- packages/dashboard/src/DashboardPlugin.ts
- packages/dashboard/src/PanelEvent.ts
- packages/dashboard/src/index.ts
- packages/dashboard/src/layout/LayoutUtils.ts
- packages/dashboard/src/layout/useDashboardPanel.ts
- packages/embed-widget/src/App.tsx
- packages/golden-layout/src/utils/EventUtils.test.ts
- packages/golden-layout/src/utils/EventUtils.ts
- packages/golden-layout/src/utils/index.ts
- tests/styleguide.spec.ts
- Instead of using PanelEvent.OPEN directly and not getting any type safety, add functions for emitting, listening, and a hook to enforce type safety
- Add xcomponents to the styleguide
> feat: Add functions for PanelEvent.OPEN

- packages/grid/src/Grid.tsx
- packages/iris-grid/src/IrisGrid.tsx
Resolves #2087 
**Steps Moving Forward:**
- Clarify whether we want to be able to **handle edits that are not in the current viewport** -- with my understanding, this will mean we will have to load in more grid data, which does not seem overly valuable (in terms of the efficiency tradeoff) since we are dealing with an improbable edge case where the user begins to edit in the viewport, continues editing outside of the viewport where the cell originally was, and then wants to commit those changes outside as well
** A better solution for the edge case above IMO  is to **create a new enhancement ticket** where we attempt to have the editing cell be floating/sticky in the grid viewport, similar to how it is done on Google Sheets **
**_Ticket Created:_** …
> fix: error when edited cell is out of grid viewport

- .vscode/settings.json
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.scss
- packages/iris-grid/src/IrisGridPartitionSelector.test.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.tsx
- packages/iris-grid/src/IrisGridPartitionedTableModel.ts
- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/iris-grid/src/PartitionedGridModel.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/iris-grid/src/mousehandlers/IrisGridPartitionedTableMouseHandler.ts
- packages/iris-grid/src/mousehandlers/index.ts
Resolves #2079  ( Resolves #2066 , Resolves #2103 , Resolves #2104 , Resolves #2105 , Resolves #2106 , Resolves #2107 , Resolves #2108 , Resolves #2109 , Resolves #2049 ), Resolves #2120, Resolves #1904
**Changes Implemented:**
- Replaced `keysTable` with `baseTable` 
- Made small UI changes to differentiate between Partition Table and Partition-aware source table
- Allow double clicking to set partition
- Add context menu action to set partition
**Sample Visuals:**
_Default Partition Table View_
_Default Partition-aware source table view:_
> feat: Partitioned Table UI Enhancements

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
Closes #2093  (For now, will reopen ticket after merge for better solution to handle deprecated `panel` prop)
> fix: add back panel prop to IrisGrid Plugin

- packages/embed-widget/src/App.tsx
- We creating a new session and getting the session details, even though that was unnecessary for fetching the object itself since we already have a connection
- Just pass `isConsoleAvailable: false` here, since we will never have the console available in the embedded widget scenario
- Should speed up the embed-widget fetch quite a bit
> fix: Remove the session wrapper from the embedded widget app

- packages/eslint-config/index.js
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/utils/src/ClipboardUtils.test.ts
- packages/utils/src/ClipboardUtils.ts
Enabled `@typescript-eslint/return-await` eslint rule and fixed offending code.
fixes #2154
BREAKING CHANGE: Fix any try / catch blocks that return non-awaited Promises
> fix: Enabled @typescript-eslint/return-await rule and fixed offending code

- packages/iris-grid/src/IrisGridPartitionedTableModel.ts
- If it's not available, just fallback to the getKeyTable API (which we were using before)
- Tested against deephaven-core 0.35.1
```
x = new_table({
"Foo": [0, 1, 2, 0, 1, 2],
"Bar": [4, 5, 6, 7, 8, 9]}
).partition_by(["Foo"])
```
> fix: Check for the getBaseTable API before calling it

- packages/components/scss/BaseStyleSheet.scss
- packages/components/src/modal/Modal.tsx
- packages/components/src/theme/SpectrumThemeProvider.tsx
Wrap the `Modal` component attached to `document.body` in `SpectrumThemeProvider`.
Had to add `zIndex: 0` and `position: relative` to the `SpectrumThemeProvider` to fix the issue with `DatePicker` popovers nested in the `Modal` rendering behind it.
> fix: DH-17454: Wrap Modal in SpectrumThemeProvider

- packages/grid/src/Grid.tsx
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
Resolves https://github.com/deephaven/web-client-ui/issues/2089
> fix: Input Tables cannot paste more rows than number of visible rows

- .browserslistrc
- README.md
- package-lock.json
- package.json
- packages/code-studio/vite.config.ts
Closes #1752
** The only thing I am not 100% sure about is how we can test this before merging **
I tried experimenting with checking the compatible browsers on their own website: https://browsersl.ist/
> fix: Restrict officially supported browserlist

- package-lock.json
I ran `npm i` to sync package-lock with latest package.json. Fixed a mismatched version number for `@internationalized/date`
fallout from #2170
> build: Sync package-lock

- packages/iris-grid/src/IrisGridProxyModel.test.ts
- packages/iris-grid/src/IrisGridProxyModel.ts
Something I noticed when working on dh.ui databars. I don't think this currently causes any issues in DHC, but it could. If we defined a member field in the proxy model and then set the value, we could end up with the wrong values.
This is only an issue if we directly set a public member. In the current proxy model, we only set via `setField` type functions, so things seem to be fine. Inside of class definitions the proxy is skipped (since the proxy is just returned from the ctor).
This change makes setting a member defined in the proxy class work even if you try to do it on the proxy object.
```ts
class ProxyModel {
myField = 4
}
test = new ProxyModel();
test.myField; // 4
test.model.myField; // undefined
test.myField = 5;
test.myField; // 4 - WRONG
test.model.myField; // 5
```
> fix: Proxy model not setting defined values in parent class

- packages/grid/src/Grid.tsx
Errors thrown during a `requestAnimationFrame` are not caught because they're thrown from a separate stack than the component. This means any render method that throws after the first grid render won't actually be caught and the grid will potentially draw incorrectly.
> fix: Errors thrown during a grid update are not caught

- package-lock.json
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/plugin/package.json
- packages/plugin/src/TablePlugin.ts
> fix: TablePlugin needs to know table name and selected range

- packages/components/src/modal/Modal.tsx
- packages/components/src/modal/ModalBody.tsx
- packages/components/src/modal/ModalFooter.tsx
- packages/components/src/modal/ModalHeader.tsx
- packages/components/src/theme/SpectrumThemeProvider.tsx
Cherry-pick #2173 and #2169 from v0.88
> fix: DH-17454: Fix Spectrum component theming in modal dialogs

- packages/dashboard/src/PanelEvent.ts
- packages/golden-layout/src/utils/EventUtils.test.ts
- packages/golden-layout/src/utils/EventUtils.ts
- Previously every emit required exactly one parameter, which is not the case
- Allow zero or more parameters
> fix: makeEventFunctions take an array of parameters

- packages/dashboard-core-plugins/src/events/TabEvent.ts
- packages/dashboard-core-plugins/src/events/TabEventMap.ts
Add TabEventMap associating TabEvent types to callback signatures.
Change TabEvent to object literal so it could be used to define TabEventMap.
BREAKING CHANGE: Delete unused event types: `openPQObject`, `openControl`, `reload`, `clearAllFilters`.
> refactor: Change TabEvent to object literal, add TabEventMap

- packages/components/src/theme/ThemeModel.ts
- packages/components/src/theme/ThemeProvider.test.tsx
- packages/components/src/theme/ThemeProvider.tsx
- packages/components/src/theme/ThemeUtils.test.ts
- packages/components/src/theme/ThemeUtils.ts
- packages/components/src/theme/__snapshots__/ThemeProvider.test.tsx.snap
Allow setting selected theme via a `themeKey` query string param.
Can test by passing `themeKey=default-light` and `themeKey=default-dark` as query string params.
resolves #2203
> feat: Set selected theme via query string param

- packages/components/src/transitions/FadeTransition.tsx
- packages/components/src/transitions/SlideTransition.tsx
Fixes #2192
Tested by following steps in the ticket. Created a react app w/ `create-react-app` and installed `@deephaven/components@0.91.1-webpack-fix.0` (alpha build from this PR). It properly started without webpack errors.
> fix: Invalid import in @deephaven/components for webpack

- packages/components/src/modal/Modal.test.tsx
- packages/components/src/modal/Modal.tsx
For the Ruff settings editor, I wanted to close the modal when pressing escape, but not clicking outside. Turns out this wasn't possible with our previous modal component.
> feat: Add clickOutside prop to Modal

- packages/app-utils/src/plugins/remote-component.config.ts
- packages/console/src/index.ts
- packages/console/src/notebook/Editor.tsx
- Allows plugins to use context of @deephaven/console
- Will be needed eventually for https://github.com/deephaven/deephaven-plugins/issues/781
> build: Add @deephaven/console as shared package

- packages/dashboard-core-plugins/src/panels/Panel.tsx
- packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx
- additionalActions was only a prop on Panel
- Add it as a prop on WidgetPanel and pass it through
> feat: Pass through additional actions from WidgetPanel

- package-lock.json
- package.json
- packages/components/src/BulkActionBar.tsx
- packages/components/src/context-actions/ContextActionUtils.ts
- packages/components/src/spectrum/utils/itemUtils.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/CustomColumnBuilder.tsx
- packages/log/src/LogProxy.ts
- packages/plugin/src/PluginTypes.ts
- packages/redux/src/reducers/common/mergeReducer.ts
- packages/redux/src/reducers/common/replaceByIdReducer.ts
- packages/redux/src/reducers/common/replaceReducer.ts
- packages/utils/src/EventTargetShimUtils.ts
Upgraded to TypeScript 5.6.2
resolves #2222
> build: Upgrade to TypeScript 5.6.2

- packages/iris-grid/src/IrisGridModel.test.ts
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
Move `isValuesTableAvailable` getter from `IrisGridTableModel` to `IrisGridTableModelTemplate` to make it availalbe in tree table model.
Fixes DH-17537 in enterprise.
Note, this doesn't fix the issue with Advanced Filter on tree tables in Community. JSAPI throws an exception on a `treeTable.copy` call.
```
[AdvancedFilterCreator] Unable to open values table Error: java.lang.UnsupportedOperationException: reexport
at UnsupportedOperationException_0.createError (dh-core.js:1383:10)
at UnsupportedOperationException_0.initializeBackingError (dh-core.js:1409:46)
at UnsupportedOperationException_0.Throwable_0 (dh-core.js:1348:8)
at UnsupportedOperationException_0.Exception_1 (dh-core.js:1433:18)
at UnsupportedOperationException_0.RuntimeException_1 (dh-core.js:1446:18)
at new …
```
> fix: DH-17537: Fix Advanced Filter dialog not showing the values list on tree tables

- packages/iris-grid/src/IrisGridModel.test.ts
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
Move `isValuesTableAvailable` getter from `IrisGridTableModel` to
`IrisGridTableModelTemplate` to make it availalbe in tree table model.
Fixes DH-17537 in enterprise.
Note, this doesn't fix the issue with Advanced Filter on tree tables in
Community. JSAPI throws an exception on a `treeTable.copy` call.
```
[AdvancedFilterCreator] Unable to open values table Error: java.lang.UnsupportedOperationException: reexport
at UnsupportedOperationException_0.createError (dh-core.js:1383:10)
at UnsupportedOperationException_0.initializeBackingError (dh-core.js:1409:46)
at UnsupportedOperationException_0.Throwable_0 (dh-core.js:1348:8)
at UnsupportedOperationException_0.Exception_1 (dh-core.js:1433:18)
at UnsupportedOperationException_0.RuntimeException_1 (dh-core.js:1446:18)
at new …
```
> fix: Cherry-pick DH-17537: Fix Advanced Filter dialog not showing the values list on tree tables

- packages/iris-grid/src/IrisGridProxyModel.ts
closes https://github.com/deephaven/web-client-ui/issues/2234
Fixes https://deephaven.atlassian.net/browse/DH-17730 in Enterprise. This is the cherry pick back to v0.85.
> fix: DH-17730: Fix Proxy Model Undefined Formatter (#2237)

- packages/dashboard/src/layout/LayoutUtils.test.ts
- packages/dashboard/src/layout/LayoutUtils.ts
- packages/golden-layout/src/items/RowOrColumn.ts
Fixes #1268
This mostly occurs when you have a relatively fresh state. There's a video in the ticket, but if you have just 2 rows then this is frequently triggered. Using incognito mode should give you a fresh state which is affected by this bug.
This fixes both the vertical shift when you open a new panel type (open a notebook from a fresh state or open a table from a fresh layout state) and when you close the last panel in a stack (like in the ticket)
> fix: Layout shifts when opening and closing panels from a fresh state

- packages/console/package.json
- packages/console/src/csv/CsvTypeParser.ts
- packages/console/src/index.ts
- packages/console/tsconfig.json
- packages/jsapi-utils/src/NewTableColumnTypes.ts
- packages/jsapi-utils/src/index.ts
Moved `NewTableColumnTypes` to jsapi-utils
resolves #2239
> refactor: Moved NewTableColumnTypes to jsapi-utils

- packages/components/src/theme/theme-dark/theme-dark-semantic-editor.css
User reported editor find contrast in dark mode was bad. Changed color for semantic editor highlight in dark mode to an orange similar to what monokai uses for find in vs code. Confirmed existing color in light mode was fine.
Before:
After:
> fix: improve color contrast of editor find in dark mode

- packages/iris-grid/src/IrisGridModelUpdater.tsx
`pendingRowCount` and `pendingDataMap` setters in `IrisGridModelUpdater` were emitting an event in the render cycle, that caused a React warning about the render not being a pure function because the event triggered state update in `IrisGrid`.
Wrap the setters in `useEffect` instead of `useOnChange` so the events are emitted after the render.
> fix: DH-17861: Fix the warning about IrisGridModelUpdater render not being a pure function

- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
`IrisGridTreeTableModel.snapshot` was attempting to access data outside of the populated `viewportData` array.
> fix: DH-17851: Fix snapshot error in TreeTable model when selection extends past viewport

- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.scss
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.test.tsx
- packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.tsx
> fix: add gap between type and name in widget panel tooltip

- packages/iris-grid/src/format-context-menus/DecimalFormatContextMenu.ts
- packages/iris-grid/src/format-context-menus/IntegerFormatContextMenu.ts
- packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
- packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts
> feat: add thousands format for numbers

- packages/chart/src/Chart.tsx
- packages/chart/src/ChartModel.ts
Adds new events that enable render-blocking overlays to the chart.
The current error pop-up is not sufficient because it still allows the chart to render. This is problematic in the case of webgl because disabling webgl means we don't want the chart rendering at all in case the computer can't handle it.
This is specifically built with https://github.com/deephaven/deephaven-plugins/issues/612 in mind.
Here is an example of the pop-up as implemented in https://github.com/deephaven/deephaven-plugins/pull/934
> feat: Add render blocking errors to Chart

- packages/utils/src/TypeUtils.ts
Copying branded type utils from `vscode-deephaven` to @deephaven/utils for broader usage.
#2263
> feat: Branded type utils

- packages/components/src/theme/theme-spectrum/theme-spectrum-alias.module.css
closes https://github.com/deephaven/web-client-ui/issues/2266
> fix: Fix Type in Spectrum Modal Overlay Background Color

- CHANGELOG.md
- packages/jsapi-components/CHANGELOG.md
- RefreshToken and other related classes were removed from `@deephaven/jsapi-components`, which was an unmarked breaking change.
> chore: Add BREAKING CHANGES note for RefreshToken

- packages/jsapi-nodejs/src/serverUtils.ts
In cases of 404 status messages, an html content 404 page was getting saved to disk later showing a non-helpful error to consumers. This should make the problem more explicit.
resolves #2271
> feat: Added a 404 status check

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridMetricCalculator.ts
- packages/iris-grid/src/IrisGridModelUpdater.tsx
- packages/iris-grid/src/IrisGridRenderer.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/key-handlers/ReverseKeyHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Fixes #2149 
This shouldn't be breaking. `reverseType` prop is deprecated, but still accepted. `reverseType` in saved states will be changed into `reverse` and then dropped from the saved state.
Tested this by exporting a layout with a table with reverse from the current DHC release. Then imported the layout to my dev UI and checked the reverse persisted.
> refactor: Change iris-grid reverseType to reverse and deprecate reverseType

- __mocks__/@astral-sh/ruff-wasm-web.js
- jest.config.base.cjs
- packages/code-studio/src/settings/EditorSectionContent.tsx
- packages/console/src/monaco/MonacoProviders.tsx
- packages/console/src/monaco/MonacoUtils.ts
- packages/console/src/monaco/RuffSettingsModal.tsx
- packages/dashboard-core-plugins/src/ConsolePlugin.tsx
- packages/dashboard-core-plugins/src/index.ts
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- packages/dashboard-core-plugins/src/useConfigureRuff.ts
Support for DH-17923 and also fixes some other edge cases with Ruff.
- Adds a hook for configuring Ruff and keeping it in sync w/ redux settings.
- Fixes a bug where if Ruff was enabled, but there was no user session then quick fixes were shown but linting underlines were not. Changed so Python is always linted if opened since it doesn't require a session to lint.
- Allow passing a default config to the Ruff config editor since DHE can set a custom config as the default via server props
- Added readOnly mode to the Ruff config editor
- Moved some formatting logic into MonacoUtils since DHE implements its own notebook panel. Eventually we should just consume the DHC NotebookPanel in DHE with extensions for PQs and other DHE options
> feat: Ruff updates for DHE support

- packages/code-studio/src/settings/SettingsMenu.scss
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/code-studio/src/settings/SettingsUtils.test.tsx
- packages/code-studio/src/settings/SettingsUtils.tsx
Fixes #2184
Fixes #2289
Updates from tooltip to contextual help button, adds python/grrovy version and changes OS name to "User Agent OS" to clarify that it is the user agent reported version (and thus may be different from what you expect).
> feat: update version info pop-up with python/groovy version

- packages/components/src/spectrum/forms.ts
> fix: missing search field import

- __mocks__/dh-core.js
- packages/chart/src/ChartUtils.test.ts
- packages/chart/src/ChartUtils.ts
- Partial holidays were not generating valid range breaks, as they did not account for business periods specified on the calendar
- Essentially we were adding another "closed" period that overlapped with time that was already outside of regular business hours
- Added a ticket to plotly.js to take into account range breaks which may overlap: https://github.com/plotly/plotly.js/issues/7270, as that would be nice to handle on their end, but this should be sufficient to resolve from our end
- Needed for DH-16016
- Added a bunch of test cases
> fix: Partial holidays range breaks

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- Deprecated props were not being passed through at all to the plugins
- We need to continue to pass through the deprecated props until we have a replacement
- Partial #2274
> fix: Table plugins - pass through deprecated props

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- Deprecated props were not being passed through at all to the plugins
- We need to continue to pass through the deprecated props until we have a replacement
- Partial #2274
> fix: Table plugins - pass through deprecated props (#2308)

- .github/workflows/e2e.yml
- tests/docker-scripts/docker-compose.yml
- The edge version of deephaven-core installs the latest version of deephaven.ui, which is not compatible with this old version of the UI
- Just pin the e2e tests to an older build of core
> build: Fix e2e tests for builds on v0.85

- package-lock.json
- packages/jsapi-nodejs/package.json
- packages/jsapi-nodejs/src/loaderUtils.ts
DH-18191: Swapping esbuild for esbuild-wasm to fix OS specific dependency
> fix: Swapping esbuild for esbuild-wasm to fix OS specific dependency

- packages/jsapi-components/src/useViewportData.test.tsx
- packages/jsapi-utils/src/ViewportDataUtils.test.ts
- packages/jsapi-utils/src/ViewportDataUtils.ts
- Was using `row.offsetInSnapshot`, which was a "protected" API and recently removed from the JS API
- API was removed in JS API refactoring: https://github.com/deephaven/deephaven-core/pull/5890
- Instead just use the viewport `offset` and add the index of the row in the snapshot, which is there in both versions of the API
- New API does support `row.index`, but this way is compatible with both
- Updated unit tests
- Tested using a deephaven.ui.list_view:
```python
from deephaven import time_table, ui
import datetime
initial_row_count = 200
column_types = time_table(
"PT1S",
start_time=datetime.datetime.now() - datetime.timedelta(seconds=initial_row_count),
).update(
[
"Id=new Integer(i)",
"Display=new String(`Display `+i)",
]
)
@ui.component
def ui_list_view_table():
value, set_value = …
```
> fix: Use correct offset in snapshot (#2217)

- packages/console/src/Console.tsx
- Cherry-pick of: console scrolls on 1st code block run (#2275)
- Cherry-pick of: Console does not scroll to bottom when code run from notebook (#2114)
- Tested by running a large block of code
> fix: Console history scroll not always sticking to bottom

- jest.setup.ts
- packages/console/src/Console.tsx
- tests/console.spec.ts
fix: Console history did not stick to bottom on visibility changes
- When debugging, I found that the `Code` block was rendering while the Console tab was in the background (invisible, size 0) so when it did finally render, there was a lot of content added but it wasn't scrolled. By checking sticky bottom when visibility changes, we handle this situtation where content causes a resize while it is invisible
- Use an IntersectionObserver to detect visibility changes: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
- Tested by running the following:
1. Run a code snippet to print a bunch of lines, causing the console history to scroll:
```python
for i in range(0, 200):
print("i is", i)
```
2. Run a snippet to create a dashboard, and have a lot of text in the …
> fix: Console history did not stick to bottom on visibility changes

- packages/console/src/Console.tsx
Resolves https://github.com/deephaven/web-client-ui/issues/2060
**Changes Implemented:**
- Added `isStuckToBottom` state that is updated on each scroll (in `handleScrollPaneScroll`), then in `componentDidUpdate`, call the `scrollConsoleHistoryToBottom` based on `isStuckToBottom`
Needed to support cherry-picking https://github.com/deephaven/web-client-ui/pull/2320 to v0.78.
> fix: Console scroll bar following dynamic output (#2076)

- package-lock.json
- packages/jsapi-nodejs/package.json
- packages/jsapi-nodejs/src/loaderUtils.ts
DH-18191: Removed esbuild runtime dependency and replaced it with an optional `PostDownloadTransform` function. Files now get downloaded directly to the `serverStorageDir` instead of `target` subdirectory.
BREAKING CHANGES: @deephaven/jsapi-nodejs `loadModules` arguments has changed. Transformation of module types is now the responsibility of the consumer.
> feat: Removed esbuild runtime dependency

- __mocks__/dh-core.js
- packages/chart/src/ChartUtils.test.ts
- packages/chart/src/ChartUtils.ts
- Partial holidays were not generating valid range breaks, as they did not account for business periods specified on the calendar
- Essentially we were adding another "closed" period that overlapped with time that was already outside of regular business hours
- Added a ticket to plotly.js to take into account range breaks which may overlap: https://github.com/plotly/plotly.js/issues/7270, as that would be nice to handle on their end, but this should be sufficient to resolve from our end
- Needed for DH-16016
- Added a bunch of test cases
> fix: Partial holidays range breaks (#2297)

- packages/jsapi-utils/src/TableUtils.ts
DH-18086: Making event details generic on TableUtils.makeCancelableTableEventPromise
> feat: Made event details generic

- package-lock.json
- packages/jsapi-nodejs/package.json
- packages/jsapi-nodejs/src/NodeHttp2gRPCTransport.ts
- packages/jsapi-nodejs/src/index.ts
- packages/jsapi-nodejs/tsconfig.json
DH-18086: gRPC transport implementation for nodejs backed by http2
Note that this is not consumed anywhere in the web but will be used by the vscode extension and tested on
https://github.com/deephaven/vscode-deephaven/pull/202
> feat: DH-18086: gRPC transport implementation for nodejs backed by http2

- packages/dashboard-core-plugins/src/controls/markdown/MarkdownEditor.tsx
- packages/dashboard-core-plugins/src/panels/MarkdownPanel.scss
- Fixes #2312
- Tested using a code block from the ticket
> fix: Markdown incorrectly rendering inline code blocks

- package.json
- packages/app-utils/src/components/AppBootstrap.tsx
- packages/app-utils/src/utils/createExportLogsContextAction.ts
- packages/app-utils/src/utils/index.ts
- packages/code-studio/src/index.tsx
- packages/code-studio/src/main/App.tsx
- packages/code-studio/src/main/AppMainContainer.test.tsx
- packages/code-studio/src/main/AppMainContainer.tsx
- packages/components/src/shortcuts/GlobalShortcuts.ts
- packages/embed-widget/src/App.tsx
- packages/embed-widget/src/index.tsx
- packages/embed-widget/vite.config.ts
- playwright-ci.config.ts
- tests/shortcuts.spec.ts
- Added `Ctrl+Alt+Shift+L/Cmd-Option-Shift-L` as a global shortcut for exporting support logs
- When pressed in code-studio, it will download logs with the same contents as logs produced by pressing the 'Export Logs' button in the settings menu
- When pressed in other contexts: when not logged in, on a reconnect error, or in embed-widgets, the logs are exported without the plugin and server info
- Tested by E2E tests that navigate to the various contexts, presses the shortcut, and checks if a file was downloaded. Can further inspect the file downloaded in the tests but unsure if that's necessary
Closes #1963
> feat: Add global shortcut to export logs

- packages/components/src/ErrorBoundary.test.tsx
- packages/components/src/ErrorBoundary.tsx
- packages/dashboard/src/PanelErrorBoundary.test.tsx
- packages/dashboard/src/PanelErrorBoundary.tsx
- If either were asked to render `undefined` children, they would throw.
- They should be catching all errors, so we definitely do not want them to throw. They should be more robust.
- Added unit tests.
> fix: Ensure ErrorBoundary and PanelErrorBoundary do not throw

- packages/console/src/notebook/Editor.scss
Container has 1462.86px of space but Monaco is setting itself to 1463px, causing overflow.
May have to play with zoom levels and browser widths to get it to reproduce. For me a 2560 window with 2 levels of zoom reliably reproduced.
Fix by overriding those widths to be 100%. Noticed no behavior differences other than fixing zoom issue.
> fix: monaco editor overflowing at certain zoom levels

- packages/grid/src/Grid.tsx
- packages/grid/src/key-handlers/PasteKeyHandler.test.tsx
- packages/grid/src/key-handlers/PasteKeyHandler.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/NoPastePermissionModal.tsx
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- packages/utils/src/ClipboardUtils.test.ts
- packages/utils/src/ClipboardUtils.ts
- packages/utils/src/PermissionUtils.test.ts
- packages/utils/src/PermissionUtils.ts
- packages/utils/src/errors/ClipboardPermissionDeniedError.ts
- packages/utils/src/errors/ClipboardUnavailableError.ts
- packages/utils/src/errors/UnsupportedPermissionError.ts
- packages/utils/src/errors/index.ts
- packages/utils/src/index.ts
- Added paste as a context menu option in IrisGrid
- Added methods to check for and request clipboard permissions, which are called when clicking paste in context menu
- For browsers that support the `clipboard-read` permission (e.g. Chrome), clicking paste results in the same behaviour as pressing the keyboard shortcut, provided the user has accepted the request for permission 
- For browsers that don't support the `clipboard-read` permission (e.g. Firefox and Safari), a modal is shown to explain the reason and to suggest using the keyboard shortcut instead
Additional related issues fixed
- Show relevant warning when attempting to paste too many columns into input table
- Fixed copy and pasting between Deephaven tables on Firefox. The issue is caused by tabs in pasted content being …
> fix: No context menu item for paste in an input table

- packages/components/src/spectrum/comboBox/ComboBox.tsx
- Was receiving an error on running `npm start`: [ERROR] Failed to resolve entry for package "@react-types/combobox". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
- Seemed to be an issue with how we exported the type. An issue has been filed with esbuild: https://github.com/evanw/esbuild/issues/4054
- Just change the export so that we avoid this issue. Tested by running `npm start` again
> fix: Combobox exported type error

- packages/components/src/navigation/NavTab.tsx
- packages/components/src/navigation/NavTabList.scss
- Moved the title into its own element in the navbar tab so that `text-overflow: ellipsis` would work properly. 
- Tested by creating dashboards with both long and short titles to confirm that long titles are truncated with ellipses, and short titles display in the same way as before.
> fix: Long dashboard titles overflow the navbar tab

- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Useful snippet for testing
```
from deephaven import empty_table, input_table
source = empty_table(10).update(["X = i", "Y = i"])
result = input_table(init_table=source)
```
- The source table is not an input table and now has no option to paste into any cells
- The result table is an input table, and the option to paste will appear only if the current selection can be pasted into
> fix: Paste option shows when it shouldn't

- packages/console/src/monaco/MonacoProviders.tsx
Should remove the invalid quick fixes to disable syntax errors (wouldn't that be nice if you could do that)
Also if there is a duplicate code detected (usually only if you have a selection and use the light bulb instead of the hover quick fix link in the modal), then the "diasble RULE for file" should only appear once. There should also be "disable RULE for line X" and "disable RULE for line Y" instead of just "for line".
> fix: DH-18542: Remove duplicate and invalid ruff quick fixes

- packages/golden-layout/src/controls/DragProxy.ts
- packages/golden-layout/src/controls/Tab.ts
- packages/golden-layout/test/title-tests.js
- Golden Layout was setting the title in panel titles with `.html()` method, which allows remote code execution, and potentially could craft a notebook with a malicious name that could run arbitrary JS
- Instead just use `.text` and treat it like text, as we should.
- Tested on DHC - created a notebook with the name `<img src=q onerror=prompt(1)>.py`. It now appears correctly as text and does not pop up an alert message. Also verified that title still appears in italics when in "preview" mode.
- Fixes DH-18645
> fix: Don't use HTML in panel titles, treat as text

- packages/golden-layout/src/controls/DragProxy.ts
- packages/golden-layout/src/controls/Tab.ts
- packages/golden-layout/test/title-tests.js
- Golden Layout was setting the title in panel titles with `.html()` method, which allows remote code execution, and potentially could craft a notebook with a malicious name that could run arbitrary JS
- Instead just use `.text` and treat it like text, as we should.
- Tested on DHC - created a notebook with the name `<img src=q onerror=prompt(1)>.py`. It now appears correctly as text and does not pop up an alert message. Also verified that title still appears in italics when in "preview" mode.
- Fixes DH-18645
> fix: Don't use HTML in panel titles, treat as text (#2365)

- package-lock.json
- packages/code-studio/src/index.tsx
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/log/package.json
- packages/log/src/LogExport.test.ts
- packages/log/src/LogExport.ts
- packages/log/src/LogInit.ts
- packages/log/src/index.ts
Cherry-pick #2279 
- Move `exportLogs` and `logInit` to the `log` package so they could be reused in Enterprise
- Remove `@deephaven/redux` and `@deephaven/jsapi-shim` dependencies from `LogExport.ts`
- Serialize Maps in redux data
- Unit tests for `getReduxDataString`
> refactor: DH-14692 Stop exporting client from support logs

- packages/grid/src/Grid.tsx
- packages/grid/src/GridMetricCalculator.ts
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridTableModel.js
- cherry-picked from #2053 and #2152
- Resolves https://github.com/deephaven/web-client-ui/issues/2089
- I published an alpha package and tested it against dev-jackson2 with the test steps from DH-18184
> fix: Input Tables cannot paste more rows than number of visible rows (DH-18723)

- packages/grid/src/GridModel.ts
This adds a cache for the token cache. I tested this was actually causing the issue by adding some code to the cell renderer to prefill the cache to 1 million items. It hung around 200k without the max. With max it prefills just fine (cleaning out every 10k) and doesn't hinder performance.
> fix: DH-18798 - token cache growing unbounded

- packages/grid/src/GridModel.ts
Cherry picking back.
This adds a cache for the token cache. I tested this was actually causing the issue by adding some code to the cell renderer to prefill the cache to 1 million items. It hung around 200k without the max. With max it prefills just fine (cleaning out every 10k) and doesn't hinder performance.
> fix: DH-18798 - token cache growing unbounded (#2374)

- @types/memoizee/index.d.ts
- packages/chart/src/FigureChartModel.ts
- packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
- packages/code-studio/src/settings/FormattingSectionContent.tsx
- packages/code-studio/src/styleguide/DraggableLists.tsx
- packages/components/src/AutoCompleteInput.tsx
- packages/components/src/ItemList.tsx
- packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
- packages/dashboard-core-plugins/src/controls/input-filter/InputFilter.tsx
- packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx
- packages/grid/src/MockTreeGridModel.ts
- packages/grid/src/memoizeClear.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridPartitionSelector.tsx
- packages/iris-grid/src/sidebar/RollupRows.tsx
- packages/iris-grid/src/sidebar/visibility-ordering-builder/VisibilityOrderingBuilder.tsx
Related to #2374 (and might need that change before this can merge). This requires all `memoizee` and `memoizeClear` calls to provide a max cache size. Most of these were small caches most likely, but this should help prevent another issue that is hard to spot since it takes potentially hours to reproduce like DH-18798
> refactor: Require memoizee and memoizeClear calls have a max size

- packages/file-explorer/src/FileList.tsx
- We were using `innerHTML` with the text of the name of the file to create the drag placeholder content
- Instead, inject the name using `innerText` so it is escaped properly
- Tested by naming a file `<img src=q onerror=prompt(1)>.py`, and then attempting to move it. It no longer triggered the popup.
> fix: Don't use innerHTML to populate drag item (DH-18645)

- packages/file-explorer/src/FileList.tsx
- We were using `innerHTML` with the text of the name of the file to create the drag placeholder content
- Instead, inject the name using `innerText` so it is escaped properly
- Tested by naming a file `<img src=q onerror=prompt(1)>.py`, and then attempting to move it. It no longer triggered the popup.
> fix: Don't use innerHTML to populate drag item (DH-18645) (#2378)

- packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
- packages/iris-grid/src/sidebar/aggregations/index.ts
Need to export the aggregation operations so dh.ui can convert to the proper case for available aggregations. The JS API is case sensitive and expects `Sum` or `CountDistinct` not `count` or `COUNT`
> fix: Exports needed for ui.table aggregations

- packages/chart/src/FigureChartModel.test.ts
- packages/chart/src/FigureChartModel.ts
Example from [DH-18279](https://deephaven.atlassian.net/browse/DH-18279)
```
import deephaven.plot.express as dx
from deephaven.plot.selectable_dataset import one_click
stocks = dx.data.stocks()
one_click = Figure().plot_xy(series_name="Stock Prices", t=one_click(stocks, ["Sym"]), x="Timestamp", y="Price").show()
```
Title now updates as the input filter is updated
[DH-18279]: https://deephaven.atlassian.net/browse/DH-18279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: DH-18279: fix one click titles

- .github/workflows/conventional-pr-check.yml
Just something I noticed when closing/re-opening the npm audit PR earlier. The pr-check action doesn't run on re-opened PRs, so you have to close/reopen, then edit the PR title to trigger all the actions
> ci: Run pr-check action on reopened PRs

- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useChangeEventValueCallback.test.ts
- packages/react-hooks/src/useChangeEventValueCallback.ts
Hook that passes `event.target.value` to a callback
In support of DH-17600
> feat: useChangeEventValueCallback hook

- packages/chart/src/Chart.tsx
- packages/chart/src/ChartModel.ts
These are for https://github.com/deephaven/deephaven-plugins/pull/1088
Currently the layout is only set once, but with indicator it may change, although specifically the title, so I added an event for that. Not sure if it's the best approach.
> feat: Add chart event for title change (#2352)

- packages/chart/src/FigureChartModel.test.ts
- packages/chart/src/FigureChartModel.ts
Example from [DH-18279](https://deephaven.atlassian.net/browse/DH-18279)
```
import deephaven.plot.express as dx
from deephaven.plot.selectable_dataset import one_click
stocks = dx.data.stocks()
one_click = Figure().plot_xy(series_name="Stock Prices", t=one_click(stocks, ["Sym"]), x="Timestamp", y="Price").show()
```
Title now updates as the input filter is updated
[DH-18279]:
https://deephaven.atlassian.net/browse/DH-18279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---------
[DH-18279]: https://deephaven.atlassian.net/browse/DH-18279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DH-18279]: https://deephaven.atlassian.net/browse/DH-18279?atlOrigin=eyJpI …
> fix: DH-18279: fix one click titles (#2381)

- package-lock.json
- packages/jsapi-nodejs/README.md
- packages/jsapi-nodejs/package.json
- packages/jsapi-nodejs/src/loaderUtils.ts
DH-19067: Added a `loadDhModules()` function to simplify common usage. Also updated @deephaven/jsapi-nodejs README to reflect latest api.
I deployed an alpha and tested the changes in a sample repo:
https://github.com/bmingles/deephaven-repl/pull/1
Once the changes have been released, I plan to update VS Code extension to use the new apis as well
> feat: @deephaven/jsapi-nodejs loadDhModules() util

- packages/log/src/LogExport.test.ts
- packages/log/src/LogExport.ts
- Wildcards are now accepted for logs blacklist JSON paths (e.g. `dashboardData.*.sessionWrapper`)
- Updated default blacklist to remove the `sessionWrapper` from any dashboard under `dashboardData`
- This technically removes the ability to look for a `*` literal path and an escape could be added for that case, but it seems like an extreme edge case to handle.
> feat: Allow wildcards for logs blacklist

- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridTableModel.ts
- Fixes the observed issue of the partition selector button flipping between Merge and Coalesce depending on which partition view is selected. 
- The original condition for `isPartitionAwareSourceTable` in `IrisGridTableModel.ts` isn't always accurate as `table.isUncoalesced` is only true when no filters have been applied yet. Once a filter is applied, the table is no longer considered uncoalesced but the source table should still have the same property as before.
- Test snippet is linked on the ticket: [DH-19015](https://deephaven.atlassian.net/browse/DH-19015)
[DH-19015]: https://deephaven.atlassian.net/browse/DH-19015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Partition aware source table UI widget swaps from merge to coalesce

- packages/utils/src/DbNameValidator.test.ts
- packages/utils/src/DbNameValidator.ts
- Updated `STERILE_TABLE_AND_NAMESPACE_REGEX` in `DbNameValidator` to match the Java class and allow hyphens in table names
- Added `replace` arg to `DbNameValidator.legalize` to preserve the existing `legalizeColumnName` behavior - replace spaces and hyphens in column names with underscores.
- Updated unit tests
> fix: DH-17599: Fix table name validation - allow hyphens

- packages/log/src/LogExport.test.ts
- packages/log/src/LogExport.ts
Cherry-pick changes made to `LogExport.ts` in `main` into `v0.85` to address [DH-19079](https://deephaven.atlassian.net/browse/DH-19079)
- fix: avoid exceeding call stack when exporting logs with large number of queries (#2382)
- feat: Allow wildcards for logs blacklist (#2396)
[DH-19079]: https://deephaven.atlassian.net/browse/DH-19079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Cherry-pick latest log export changes into v0.85

- packages/jsapi-nodejs/src/NodeHttp2gRPCTransport.ts
DH-19010: Delete closed http2 sessions from the cache. This ensures new sessions get created on next request since closed sessions cannot be re-used.
Note that this is currently only used by the VS Code extension. I tested it locally, but final testing will happen as part of the PR that updates DH packages to use this change.
> fix: DH-19010: Delete closed http2 sessions from the cache

- packages/utils/src/DbNameValidator.test.ts
- packages/utils/src/DbNameValidator.ts
PR #2398 allowed hyphens in namespace and table names. However, I noticed that server-side validation rejects names starting with a hyphen, while these names appear valid on the client-side.
`io.deephaven.db.tables.utils.DBNameValidator` uses separate regular expressions to sanitize and validate names. This change adds the correct `TABLE_NAME_PATTERN` for table name validation instead of checking if the name matches its sanitized version.
> fix: DH-17599: Fix table name validation

- package-lock.json
- packages/code-studio/src/index.tsx
- packages/code-studio/src/settings/SettingsMenu.tsx
- packages/log/package.json
- packages/log/src/LogExport.test.ts
- packages/log/src/LogExport.ts
- packages/log/src/LogInit.ts
- packages/log/src/index.ts
Cherry-pick changes made to `LogExport.ts` in `main` into `v0.78` to address [DH-18984](https://deephaven.atlassian.net/browse/DH-18984)
- https://github.com/deephaven/web-client-ui/pull/2396
- https://github.com/deephaven/web-client-ui/pull/2382
- https://github.com/deephaven/web-client-ui/pull/2279
[DH-18984]: https://deephaven.atlassian.net/browse/DH-18984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: Cherry-pick latest log export changes into v0.78

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
Controls visiblity of the Organize Columns menu in Table Options
> refactor: Add isOrganizeColumnsAvailable flag to IrisGrid

- packages/console/src/csv/CsvInputBar.tsx
- packages/utils/src/DbNameValidator.test.ts
- packages/utils/src/DbNameValidator.ts
- Add `makeVariableName` method to create valid variable names
- Add/update unit tests.
> fix: DH-17599: Change illegal characters to underscores in variable names

- packages/console/src/csv/CsvInputBar.tsx
- packages/utils/src/DbNameValidator.test.ts
- packages/utils/src/DbNameValidator.ts
Cherry-pick #2409 into v0.85:
- Add `makeVariableName` method to create valid variable names
- Add/update unit tests.
> fix: Cherry-pick DH-17599: Change illegal characters to underscores in variable names

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
https://deephaven.atlassian.net/browse/DH-19138
For totals table columns, we were applying renaming logic based on number of operations in the config, but it should be on number of operations for each given column.
E.g., for a config `{X : [SUM, COUNT], Y: [COUNT]}` then your columns will be `[X_SUM, X_COUNT, Y]` but we were expecting `[X_SUM, X_COUNT, Y_COUNT]`
> fix: DH-19138: Determine Totals Column Name by Num Aggs Per Column

- packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.test.tsx
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
- Although we handle the case where the grid is right-clicked outside of the current selection in `GridSelectionHandler.ts`, where the new selection will be updated to the row the cursor is on, state changes are batched in event handlers so `IrisGridContextMenuHandler.tsx` will be using a stale value for `selectedRanges` when it runs. 
- To fix this we can implement the exact same logic in both components, such that the selected ranges used in `onContextMenu` in `IrisGridContextMenuHandler.tsx` will be the same as what `onContextMenu` in `GridSelectionHandler.ts` will set it to after all handlers have ran.
Test Snippet (any table will work though)
```
from deephaven import empty_table, input_table
source = empty_table(10).update(["X = i", "Y = i"])
result = input_table(init_table=source) …
```
> fix: Context menu using stale selection

- packages/grid/src/mouse-handlers/GridSelectionMouseHandler.test.ts
- packages/grid/src/mouse-handlers/GridSelectionMouseHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
After merging in https://github.com/deephaven/web-client-ui/pull/2407, I thought a bit more about my implementation and decided to refactor it (before picking this back to `v0.85`)
It makes more sense for `getLatestSelection` to live in `GridSelectionMouseHandler` since its logic also depends on the implementation of `onContextMenu` in this class, and this will make it more straightforward for other mouse handlers that might want to use this method to get the Grid's most recent selected ranges.
> refactor: move getLatestSelection to GridSelectionMouseHandler

- packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
> fix: missing specturm accordian icon due to styling

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
https://deephaven.atlassian.net/browse/DH-19138
For totals table columns, we were applying renaming logic based on number of operations in the config, but it should be on number of operations for each given column.
E.g., for a config `{X : [SUM, COUNT], Y: [COUNT]}` then your columns will be `[X_SUM, X_COUNT, Y]` but we were expecting `[X_SUM, X_COUNT, Y_COUNT]`
> fix: DH-19138: Determine Totals Column Name by Num Aggs Per Column (#2411)

- @types/memoize-one/index.d.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGridCacheUtils.test.ts
- packages/iris-grid/src/IrisGridCacheUtils.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/index.ts
Adds `IrisGridCacheUtils` which provides 3 methods to create memoized dehydrators: `makeMemoizedGridStateDehydrator`, `makeMemoizedIrisGridStateDehydrator`, and `makeMemoizedCombinedGridStateDehydrator`. The first 2 are used for `IrisGridPanel` which saves the state under separate keys for `gridState` and `irisGridState`. The 3rd is for newer uses like `UITable` which can just save the combined state and spread it to `IrisGrid` since `IrisGrid` accepts both `GridState` and `IrisGridState` props.
Added tests for `dehydrateIrisGridState`.
Improved the `memoize-one` type override to infer the types of the equality function based on the actual function args.
> feat: Add IrisGridCacheUtils for memoizing iris grid state

- packages/iris-grid/src/IrisGridUtils.ts
Removed in #2416 but they may be needed if we're migrating from old saved states.
The main reason they're needed even though the type specifies they aren't all optional is some non-TS code in DHE still.
> fix: Add back some defaults to dehydrateIrisGridState

- packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
- packages/iris-grid/src/sidebar/aggregations/index.ts
Need to export the aggregation operations so dh.ui can convert to the proper case for available aggregations. The JS API is case sensitive and expects `Sum` or `CountDistinct` not `count` or `COUNT`
> fix: Exports needed for ui.table aggregations (#2385)

- __mocks__/dh-core.js
- package-lock.json
- package.json
- packages/chart/src/ChartTestUtils.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.test.ts
I went with `autorangeoptions` instead of range as it provides more intuitive behavior.
```from deephaven import read_csv
import deephaven.plot.express as dx
stocks = dx.data.stocks().where("Sym = `FISH`")
plot_single = (
Figure()
.plot_xy(
series_name="Price",
t=stocks,
x="Timestamp",
y="Price",
)
.y_axis(min=0.0, max=170.0)
.x_twin()
.plot_xy(
series_name="SPet500",
t=stocks,
x="Timestamp",
y="SPet500",
)
.y_axis(log=True, max=300.0)
.show()
)
```
> fix: DH-18832: propagate min and max to plotly figure axis

- packages/dashboard-core-plugins/src/GridWidgetPlugin.test.tsx
- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/useIrisGridModel.test.ts
- packages/dashboard-core-plugins/src/useIrisGridModel.ts
Part of DH-19000. This adds the `GridWidgetPlugin` implementation of `usePersistentState`. It will effectively do nothing right now since the state will always be `undefined` to start. Once the dh.ui side of this merges, then normal tables in a `dh.ui` panel will persist their state
> feat: Add usePersistentState implementation to GridWidgetPlugin

- packages/chart/src/ChartUtils.ts
- In some headless environments, `document` is `undefined` and this would throw an uncaught exception
- Just catch the exception and return `false`
- Now this matches the same check that was added to the plotly-express plugin: https://github.com/deephaven/deephaven-plugins/pull/1147
> fix: Catch errors when detecting if WebGL is supported

- packages/console/src/monaco/MonacoProviders.tsx
Looks like it was an issue caused if Ruff was disabled when we changed settings (we set settings on initial load). This was causing a check to pass and then trying to use Ruff without initializing it
Also added some log suppression because Ruff internals call `console.log` when the workspace is created and it's not useful to us. It's something along the lines of `glob 25 created ...` and I just found it unnecessary noise
> fix: DH-19350: Ruff tries to lint before initializing when disabled

- packages/components/src/theme/theme-dark/theme-dark-semantic.css
DH-18562: Fixes issue with picker styling when using dark mode. Previously the background did not serve as a good indicator when hovering over items.
I checked in with @dsmmcken to confirm the styling changes. I also tested the picker component in both the style guide and theme selector under settings.
**Hovered Styling (Before)**
**Hovered Styling (After)**
> fix: DH-18562: Deephaven picker hover blends with non-hovered styling in dark mode

- package-lock.json
- packages/components/package.json
- packages/components/src/spectrum/TabPanels.test.tsx
- packages/components/src/spectrum/TabPanels.tsx
- packages/components/src/spectrum/navigation.ts
Part of DH-18349. Will need a small update in dh.ui to enable support there which is what the ticket wants.
Does not change default behavior of `TabPanels`, just adds an extra param to keep static panels mounted (in React, but not actually mounted in the DOM).
There are unit tests, but can also test with local plugins from this PR https://github.com/deephaven/deephaven-plugins/pull/1177
> feat: Add keepMounted param to TabPanels for persisting panels when they are not active

- __mocks__/dh-core.js
- package-lock.json
- package.json
- packages/chart/src/ChartTestUtils.ts
- packages/chart/src/ChartUtils.ts
- packages/chart/src/FigureChartModel.test.ts
I went with `autorangeoptions` instead of range as it provides more intuitive behavior.
```from deephaven import read_csv
import deephaven.plot.express as dx
stocks = dx.data.stocks().where("Sym = `FISH`")
plot_single = (
Figure()
.plot_xy(
series_name="Price",
t=stocks,
x="Timestamp",
y="Price",
)
.y_axis(min=0.0, max=170.0)
.x_twin()
.plot_xy(
series_name="SPet500",
t=stocks,
x="Timestamp",
y="SPet500",
)
.y_axis(log=True, max=300.0)
.show()
)
```
> fix: DH-18832: propagate min and max to plotly figure axis (#2424)

- tests/table-multiselect.spec.ts
- tests/utils.ts
- Update `openTable` in `tests/utils.ts` to better target the added panel, check for the canvas element to be present and the overlay to be removed from the DOM.
- Throw error to fail tests instead of just skipping.
- Change `Control` to `ControlOrMeta` for shortcuts.
- Wait for the filter input to appear after activating Quick Filters.
> test: Fix issues with e2e when running locally

- packages/grid/src/Grid.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridTableModel.ts
- packages/iris-grid/src/index.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Cherry-pick #2437:
- Reset movedColumns in IrisGrid and re-calculate metrics on TABLE_CHANGED event
- Fix the issue with grid metrics calculations based on stale state in Grid.componentDidUpdate
- Disable advanced filters for non-filterable columns
- Expose DisplayColumn type export
- Trigger COLUMNS_CHANGED instead of TABLE_CHANGED in updateFrozenColumns
Tested alpha build on `vlad-18275-3`
> fix: Cherry-pick Simple Pivot prerequisites

- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/PandasWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/useIrisGridModel.test.ts
- packages/dashboard-core-plugins/src/useIrisGridModel.ts
1st of 3 cherry-picks for dh.ui persistent state in grizzly
- When the model is disconnected, we should just display an error. There's no option to reconnect, as the widget schema could change entirely
- By unloading the IrisGrid component, it's no longer throwing an error by trying to access table methods after a table.close()
- Fixes DH-17292 from Enterprise
- Tested using the steps in the description
> fix: DH-17292 Handle disconnect from GridWidgetPlugin (#2086)

- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridMetricCalculator.ts
- packages/iris-grid/src/IrisGridModelUpdater.tsx
- packages/iris-grid/src/IrisGridRenderer.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/key-handlers/ReverseKeyHandler.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
Cherry pick 3 of 5 (I think) for usePersistentState. Wasn't a completely clean pick, but verified against the original PR that the expected changes are all that changed.
This shouldn't be breaking. `reverseType` prop is deprecated, but still accepted. `reverseType` in saved states will be changed into `reverse` and then dropped from the saved state.
Tested this by exporting a layout with a table with reverse from the current DHC release. Then imported the layout to my dev UI and checked the reverse persisted.
> refactor: Change iris-grid reverseType to reverse and deprecate reverseType (#2278)

- @types/memoize-one/index.d.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/IrisGridCacheUtils.test.ts
- packages/iris-grid/src/IrisGridCacheUtils.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/index.ts
Cherry pick 4 of 5 for usePersistentState
Adds `IrisGridCacheUtils` which provides 3 methods to create memoized dehydrators: `makeMemoizedGridStateDehydrator`,
`makeMemoizedIrisGridStateDehydrator`, and
`makeMemoizedCombinedGridStateDehydrator`. The first 2 are used for `IrisGridPanel` which saves the state under separate keys for `gridState` and `irisGridState`. The 3rd is for newer uses like `UITable` which can just save the combined state and spread it to `IrisGrid` since `IrisGrid` accepts both `GridState` and `IrisGridState` props.
Added tests for `dehydrateIrisGridState`.
Improved the `memoize-one` type override to infer the types of the equality function based on the actual function args.
> feat: Add IrisGridCacheUtils for memoizing iris grid state (#2416)

- packages/dashboard-core-plugins/src/GridWidgetPlugin.test.tsx
- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/useIrisGridModel.test.ts
- packages/dashboard-core-plugins/src/useIrisGridModel.ts
Final cherry pick for usePersistentState
Part of [DH-19000](https://deephaven.atlassian.net/browse/DH-19000). This adds the `GridWidgetPlugin` implementation of `usePersistentState`. It will effectively do nothing right now since the state will always be `undefined` to start. Once the dh.ui side of this merges, then normal tables in a `dh.ui` panel will persist their state
[DH-19000]: https://deephaven.atlassian.net/browse/DH-19000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add usePersistentState implementation to GridWidgetPlugin (#2427)

- packages/iris-grid/src/IrisGridUtils.ts
Removed in #2416 but they may be needed if we're migrating from old saved states.
The main reason they're needed even though the type specifies they aren't all optional is some non-TS code in DHE still.
> fix: Add back some defaults to dehydrateIrisGridState (#2419)

- packages/code-studio/src/AppRoot.tsx
- packages/code-studio/src/styleguide/StyleGuideRoot.tsx
I noticed my console logs spammed with `Registering service worker` in dev mode (with dh.ui tables/panels with tables) and multiple service workers in the sources tab.
This doesn't seem to be an issue in prod, so I'm guessing it has something to do with React dev mode. I also think previously these initializers were actually at the root, but now they are under a bunch of contexts that can be changed and cause the dev re-render.
Didn't see the same behavior in enterprise where these inits are either under a `useEffect` or above the contexts at the root.
> fix: Download worker and monaco initializing multiple times in dev

- packages/console/src/notebook/ScriptEditor.tsx
DH-14302: Prevents 'run' and 'run selected' shortcuts from triggering unintended behavior when session disconnects or if there is a language mismatch.
Changes:
- Always initialize contextActions when editor is created
- Only cleanup contextActions when editor is destroyed
- Add session/language checks to the shortcut handlers
When the session is disconnected, or the notebook language does not match the session (e.g. running a Groovy notebook with a Python session), the 'run' and 'run selected' shortcuts will log a message to console instead of falling back to default browser/OS behavior.
> fix: prevent keyboard shortcuts from triggering unwanted behaviour when disconnected

- packages/dashboard/src/DashboardLayout.tsx
- packages/dashboard/src/index.ts
- packages/dashboard/src/useDhId.test.tsx
- packages/dashboard/src/useDhId.ts
- packages/dashboard/src/usePanelId.ts
Not breaking because `DhIdContext` was added recently and is not in any releases
> refactor: Rename DhIdContext to PanelIdContext

- packages/code-studio/src/main/AppMainContainer.tsx
- packages/components/src/shortcuts/NavigationShortcuts.ts
- packages/components/src/shortcuts/index.ts
- packages/dashboard/src/NavigationEvent.ts
- packages/dashboard/src/PanelEvent.ts
- packages/dashboard/src/PanelManager.ts
- packages/dashboard/src/index.ts
- packages/dashboard/src/layout/LayoutUtils.ts
- packages/golden-layout/src/items/Component.ts
- packages/golden-layout/src/items/Stack.ts
Part of DH-19632. Introduces keyboard navigation to cycle between and within stacks. Navigating through shortcuts activates content items and respects any existing active selections.
`Ctrl + '` / `Ctrl + ;`: to cycle forward/backward between different stacks in the layout
`Ctrl + Shift + '` / `Ctrl + Shift + ;`: to cycle forward/backward between tabs within the currently focused stack
Changes:
- Create`NavigationEvent` system
- Implement stack and tab cycling handlers in `PanelManager`
- Add `getFocusedStack()` and `getFocusedStackIndex()` helper methods to `LayoutUtils` for focus detection
- Add `forceFocus` parameter that bypasses the normal `isFocusonShow` check
> feat: DH-19632: Add shortcuts to cycle stacks and panels

- packages/grid/docs/README.md
- packages/grid/docs/customize/frozen.md
- packages/grid/docs/customize/interaction.md
- packages/grid/docs/customize/selection.md
- packages/grid/docs/customize/theme.md
- packages/grid/docs/display-data/asynchronous.md
- packages/grid/docs/display-data/grouped.md
- packages/grid/docs/display-data/quadrillion.md
- packages/grid/docs/display-data/static.md
- packages/grid/docs/sidebar.json
Adds initial set of grid docs, porting from deephaven.io repo.
Changes:
- Removed frontmatter, making title just #h1 
- Added sidebar in salmon format
Note: Will publish initial version manually. Publishing action TBD later.
> docs: Initial grid docs commit

- packages/golden-layout/jest.config.cjs
- packages/golden-layout/src/utils/EventUtils.ts
Noticed we had migrated a test into golden-layout, but it never ran. At a future point I then broke the test (not cleaning up event handlers on unmount), but it wasn't running so it wasn't caught.
This enables the test and fixes the broken logic so the test passes.
> fix: Enable golden-layout jest test and fix broken EventUtils test

- packages/grid/src/Grid.test.tsx
- packages/grid/src/Grid.tsx
- packages/grid/src/GridRange.ts
Needed as part of DH-19292 to ensure we don't emit duplicate selection events. Even with debouncing, we might emit the event, and then emit the same selection (in a different array reference) on mouse up. This fixes that so we don't emit the unnecessary events if the mouse up did not remove selections
There are still some quirks around the selection events like when using ctrl+click+drag to deselect part of a range, `onSelectionChanged` is emitted with the subtracted portion as an extra range (e.g., `[[0, 5], [1, 2]]`) until mouse up which commits the selection and removes the overlapping ranges (`[[0, 0], [3, 5]]`). On the dh.ui side I'm just consolidating the ranges, but would probably be good to fix that at some point.
> fix: Grid making unnecessary onSelectionChanged calls

- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
After merging https://github.com/deephaven/web-client-ui/pull/2461, I wasn't a big fan of the massive describe block for `colorForcell` and `textAlignForCell`.
> refactor(tests): split IrisGridTreeTableModel text color and alignment unit tests

- packages/grid/src/Grid.test.tsx
- packages/grid/src/Grid.tsx
- packages/grid/src/GridRange.ts
Cherry-pick for Grizzly
Needed as part of DH-19292 to ensure we don't emit duplicate selection events. Even with debouncing, we might emit the event, and then emit the same selection (in a different array reference) on mouse up. This fixes that so we don't emit the unnecessary events if the mouse up did not remove selections
There are still some quirks around the selection events like when using ctrl+click+drag to deselect part of a range, `onSelectionChanged` is emitted with the subtracted portion as an extra range (e.g., `[[0, 5], [1, 2]]`) until mouse up which commits the selection and removes the overlapping ranges (`[[0, 0], [3, 5]]`). On the dh.ui side I'm just consolidating the ranges, but would probably be good to fix that at some point.
> fix: Grid making unnecessary onSelectionChanged calls (#2471)

- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/index.ts
- packages/dashboard-core-plugins/src/linker/ColumnSelectionValidator.ts
- packages/dashboard-core-plugins/src/linker/Linker.tsx
- packages/dashboard-core-plugins/src/linker/LinkerEvent.ts
- packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.test.tsx
- packages/dashboard-core-plugins/src/linker/LinkerUtils.ts
- packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
- packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/dashboard-core-plugins/src/useDashboardColumnFilters.ts
- packages/dashboard-core-plugins/src/useGridLinker.ts
- packages/grid/src/GridMetrics.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridUtils.ts
Cherry-pick for Grizzly
This adds support for linker to `GridWidgetPlugin` so if you have tables within a dh.ui component (like 2 tables in a flex), you can link with them.
> feat: Add linker support to GridWidgetPlugin (#2459)

- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
Part of DH-19693. Anything that renders as "empty" for empty strings, and "null" for null strings, should still render the same when rolledup. This adds the missing null and empty string formatting logic for tree table constituent values.
Changes:
- Checks if the result should show "null" or "empty" based on formatter
> fix: DH-19693: Add null/empty formatting to constituent strings

- packages/jsapi-components/src/spectrum/utils/usePickerProps.ts
Cherry pick for Grizzly
DH-19864 seems to be caused by not closing these tables making the JS API client unhappy and it refuses to send data after so many re-renders with pickers in dh.ui
> fix: DH-19864 Close tables used by Picker and ComboBox (#2482)

- packages/grid/src/Grid.tsx
- Have an `updateRevision` state property that will update when forceUpdate is called, so we actually have a state variable that changes
- Similar to how Plotly handles data updates
- Removed the old logic that would trigger a draw any time componentDidUpdate was called
> fix: DH-19882: Render loop occurring in React v18

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
Part of DH-18976. Fixes an issue where the pendingRow check didn't account for totals rows, causing aggregations to be incorrectly flagged as pending in the color logic.
> fix: DH-18976: Add proper bounds to pendingRow logic

- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
Part of DH-19614. Fixes an issue with rollups where tree table aggregated constituents were not being rendered based on the original column type. This change ensures that leaf nodes in tree tables use the appropriate column type for formatting and alignment.
Changes:
- Added tree table specific overrides to `IrisGridTreeTableModel`:
- Updated `colorForCell` to use `column.constituentType` instead of `column,type` for leaf node values
- Updated `textAlignForCell` to use `column.constituentType` for leaf node values
- Added type guard `isUITreeRow` function in `IrisGridTreeTableModel.ts`
> fix: DH-19614: Add tree table formatting logic to tree model (#2461)

- packages/jsapi-nodejs/src/errorUtils.ts
- packages/jsapi-nodejs/src/loaderUtils.ts
- packages/jsapi-nodejs/src/serverUtils.ts
DH-19897: Handle missing jsapi/dh-internal.js files on core workers
I added a flag to resolve 404s as empty content instead of throwing an error. 404s were already differentiated from other errors that get retry attempts, so it was a simple change.
Testing
I tested locally by renaming `jsapi/dh-internal.js` in the `loadModules` call to `jsapi/dh-internal2.js` to mimick a 404. Confirmed empty content file gets created in VS Code extension.
I also tested stopping the server which produces a different error that invokes the retry mechanism instead of a 404. Worst case scenario, if we ever get out of sorts, restarting VS Code will delete the tmp download folder and retry everything again.
> feat: DH-19897: Handle missing jsapi/dh-internal.js files on core workers

- package-lock.json
- packages/chart/package.json
- packages/code-studio/package.json
- packages/embed-widget/package.json
- Plotly.js 3.0.x has an issue where it's bringing in some unnecessary webpack dependencies, and I think is causing issues when updating Grizzly+ with the latest web packages
- Used the package-lock.json from before we updated to plotly.js v3.0.0 and jumped straight to v3.1.0-rc.0, which shouldn't have the issue, then updated package-lock.json again
- This should resolve the build issues in G+ when updating packages
- Bumped up the heap size to avoid some build issues
> chore: Update plotly.js to 3.1.0-rc.0

- packages/grid/src/Grid.tsx
Fix for https://deephaven.atlassian.net/browse/DH-19963
> fix: DH-19963: Remove grid-block-events when Grid unmounts (#2507)

- packages/dashboard-core-plugins/src/index.ts
Looks like I forgot to export this when adding the hook so it could also be used by `ui.table`.
> fix: Export useTablePlugin for use in dh.ui

- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/sidebar/aggregations/Aggregations.tsx
For DH-19601. Input tables with aggregations in the footer were experiencing conflicts between aggregated data and insertions to the pending area. This pr pins aggregations to the top of input tables, that way we have the bottom of the table reserved for pending rows, and we don't need to worry about conflicts.
> fix: DH-19601: Pin aggregations to the top in input tables

- packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
- packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
- packages/iris-grid/src/CommonTypes.tsx
- packages/iris-grid/src/EmptyIrisGridModel.ts
- packages/iris-grid/src/IrisGrid.tsx
- packages/iris-grid/src/IrisGridCacheUtils.test.ts
- packages/iris-grid/src/IrisGridCacheUtils.ts
- packages/iris-grid/src/IrisGridModel.ts
- packages/iris-grid/src/IrisGridModelUpdater.tsx
- packages/iris-grid/src/IrisGridProxyModel.ts
- packages/iris-grid/src/IrisGridTableModelTemplate.ts
- packages/iris-grid/src/IrisGridTreeTableModel.test.ts
- packages/iris-grid/src/IrisGridTreeTableModel.ts
- packages/iris-grid/src/IrisGridUtils.test.ts
- packages/iris-grid/src/IrisGridUtils.ts
- packages/iris-grid/src/format-context-menus/TextAlignmentFormatContextMenu.ts
- packages/iris-grid/src/format-context-menus/index.ts
- packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
For DH-10205. Allows users to override the default type-based alignment logic on a per column basis using a context menu.
Text alignment is determined with the following priority order: 1. context menu, 2.ui.table, 3. column type.
TODO:
> feat: DH-10205: Add column text alignment to web

- packages/dashboard-core-plugins/src/useTablePlugin.tsx
Small thing needed for ui.resolve b/c the JS API may not be available on mount of `UITable`, so `irisGridUtils` may be null
This won't affect any rendering of table plugins since `model` is also required and possibly undefined until the JS API and table are loaded.
> fix: Allow undefined for useTablePlugin irisGridUtils

- packages/dashboard/src/Dashboard.tsx
- Instead of using a Record generically, use the GoldenLayout Settings type
> fix: Types for dashboard layout settings were not typed correctly

- packages/app-utils/src/components/ConnectionContext.ts
- packages/app-utils/src/components/FontBootstrap.tsx
- packages/app-utils/src/components/ServerConfigBootstrap.tsx
- packages/auth-plugins/src/UserContexts.ts
- packages/chart/src/ChartThemeProvider.tsx
- packages/components/src/XComponentMap.ts
- packages/components/src/theme/ThemeProvider.tsx
- packages/dashboard/src/layout/LayoutManagerContext.ts
- packages/dashboard/src/useDashboardId.ts
- packages/dashboard/src/useFiber.tsx
- packages/dashboard/src/usePanelId.ts
- packages/iris-grid/src/IrisGridThemeProvider.tsx
- packages/jsapi-bootstrap/src/ApiBootstrap.tsx
- packages/jsapi-bootstrap/src/ClientBootstrap.tsx
- packages/jsapi-bootstrap/src/useDeferredApi.ts
- packages/jsapi-bootstrap/src/useObjectFetch.ts
- packages/jsapi-bootstrap/src/useObjectFetcher.ts
- packages/plugin/src/PersistentStateContext.tsx
- packages/plugin/src/PluginsContext.ts
Added displayName to React contexts so that they can be identified in React dev tools.
Part of DH-19529
- Run DH web locally via `npm start`
- Open Components tab from React dev tools
- Verify that context providers now have names in the component tree
> feat: Added displayName to React contexts

- packages/app-utils/src/components/AppDashboards.tsx
- packages/app-utils/src/components/AuthBootstrap.tsx
- packages/app-utils/src/components/ServerConfigBootstrap.tsx
- packages/chart/src/LazyChart.tsx
- packages/chart/src/plotly/LazyPlot.tsx
- packages/code-studio/src/index.tsx
- packages/code-studio/src/main/AppInit.tsx
- packages/code-studio/src/main/AppMainContainer.tsx
- packages/components/src/ErrorBoundary.tsx
- packages/console/src/notebook/ScriptEditor.tsx
- packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/PandasWidgetPlugin.tsx
- packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx
- packages/dashboard-core-plugins/src/panels/MarkdownPanel.tsx
- packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx
- packages/dashboard/src/BasePanel.tsx
- packages/dashboard/src/LazyDashboard.tsx
- packages/dashboard/src/PanelErrorBoundary.tsx
- packages/embed-widget/src/App.scss
- packages/embed-widget/src/App.tsx
- packages/embed-widget/src/index.tsx
- packages/iris-grid/src/LazyIrisGrid.tsx
- packages/jsapi-bootstrap/src/ApiBootstrap.tsx
- packages/jsapi-components/src/TableInput.tsx
DH-19445: Set data-testid props on LoadingOverlay instances
While I was looking at performance, I set data-testid props to make it possible to identify different loading spinners.
> chore: Set data-testid props on LoadingOverlay instances

- lerna.json
From https://docs.npmjs.com/adding-dist-tags-to-packages
> We recommend avoiding dist-tags that start with a number or the letter "v".
This is now in line with what we do with v0.85 as well.
> ci: Change distTag from 'v0.99' to 'release-v0.99'

- packages/embed-widget/.env
DH-20388: VITE_MODULE_PLUGINS_URL path was set to an absolute path which breaks DH UI in VS code extension when targetting Envoy servers. Changed to a relative path.
> fix: DH-20388: VITE_MODULE_PLUGINS_URL path should be relative

- packages/golden-layout/src/LayoutManager.ts
- packages/grid/src/key-handlers/SelectionKeyHandler.ts
fixes: #1165
Was annoyed with this while working on something, add handling to escape close maximize fields.
Exclude if inputs are focused (ex. monaco uses escape to deselect, but doesn't consume it, native searches clear field but don't consume it either).
> feat: close maximized panels with escape key

- packages/iris-grid/src/IrisGridModelUpdater.tsx
`IrisGridModelUpdater` displays an error/warning in the browser console when
- The reset button is clicked in the organize columns tab in the sidebar of the grid
- A rollup is added to the table using the sidebar tab
These warnings were causing two e2e tests to fail locally. Full logs can be found in the ticket.
Similar to https://github.com/deephaven/web-client-ui/pull/2249, it looks like the `frozenColumns` setter in `IrisGridModelUpdater` was also emitting an event in the render cycle that caused a React warning about the render not being a pure function, because the event triggered a state update in `IrisGrid`. The setter is now wrapped in `useEffect` instead of `useOnChange` so the events are emitted after the render.
> fix: IrisGridModelUpdater causes "cannot update during an existing state transition" warning
