examples/component-template/README.md
examples/component-template/src/test/eslint.test.js
examples/component-template/src/test/stylelint.test.js
packages/grid/package-lock.json
packages/grid/package.json
packages/grid/src/CellInputField.tsx
packages/grid/src/test/eslint.test.js
packages/grid/src/test/stylelint.test.js

Fixes #5 
Grid was missing linter tests. Also fixed a few linter errors in grid after adding the test.

Add missing linter tests

---

packages/utils/src/ColorUtils.ts

Still new to this so expect gremlins.

convert util ColorUtils to TS

---

packages/utils/src/Pending.ts

Lots of `unknown`s but it *is* a util.

convert util Pending to TS

---

packages/chart/package-lock.json
packages/code-studio/package-lock.json
packages/components/package-lock.json
packages/console/package-lock.json
packages/grid/package-lock.json
packages/iris-grid/package-lock.json
packages/log/package-lock.json
packages/log/package.json
packages/log/src/LogProxy.ts
packages/react-hooks/package-lock.json
packages/redux/package-lock.json
packages/utils/package-lock.json

Add event-target-shim to LogProxy

---

packages/components/src/context-actions/ContextMenuRoot.tsx

Reposition new context menu when another was open on Mac

---

packages/code-studio/.env

Fix docs link in settings panel

---

packages/console/src/monaco/index.js
packages/console/src/notebook/ScriptEditor.jsx

Fix linting error from last checkin

---

packages/file-explorer/src/FileExistsError.ts
packages/file-explorer/src/FileExplorer.tsx
packages/file-explorer/src/FileList.tsx
packages/file-explorer/src/FileListContainer.tsx
packages/file-explorer/src/FileListItemEditor.tsx
packages/file-explorer/src/FileNotFoundError.ts
packages/file-explorer/src/FileStorage.ts
packages/file-explorer/src/FileUtils.test.ts
packages/file-explorer/src/FileUtils.ts
packages/file-explorer/src/NewItemModal.tsx
packages/file-explorer/src/WebdavFileStorage.ts

- Inline Renaming now validates files correctly
- Rename from the right click menu also validates correctly
- Prompt to overwrite existing file
- Fixes #91

Add validation for renaming files

---

packages/chart/package-lock.json
packages/chart/package.json

bump plotly.js to 2.2.1

---

packages/code-studio/.env.development
packages/code-studio/README.md

Updating default port to 4000 so we don't conflict with default port for Enterprise. Noticed that a couple things were incorrect in the readme so cleaned those up as well.

Update default port to 4000, fix up/remove parts of the readme that were incorrect

---

packages/console/src/ConsoleShortcuts.ts

Fix focus command history shortcut name

---

packages/iris-grid/src/IrisGridTableModel.js

- Related to https://github.com/deephaven/deephaven-core/pull/931
- Rollup, column statistics already checked if the methods existed, just needed to add the same check for totals
- Fixes #136 
Requires this PR on core well: https://github.com/deephaven/deephaven-core/pull/931

Disable aggregations if they're not enabled

---

packages/console/src/log/LogView.scss

- Added background behind console menu buttons
- Aligned find widget with top of log view
- Fixes #118

Fix up styling of console find widget

---

examples/component-template/package.json
packages/chart/package.json
packages/components/package.json
packages/console/package.json
packages/file-explorer/package.json
packages/golden-layout/package-lock.json
packages/grid/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/log/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/utils/package.json

https://github.com/deephaven/web-client-ui/security/dependabot/packages/components/package-lock.json/glob-parent/open

Update @babel/cli to fix dependabot alert

---

packages/components/src/ItemList.test.tsx
packages/components/src/ItemList.tsx
packages/components/src/ItemListItem.tsx
packages/golden-layout/package-lock.json

- Right-click now updates the selection before showing context menu
- Fixes #154

Improve context menu selection in Command History/Item List

---

packages/jsapi-shim/README.md

Update the @deephaven/jsapi-shim README

---

.github/workflows/publish-alpha.yml
.github/workflows/publish-nightly.yml

I forgot to remove the registry flag, I only removed the registry-url in the setup step.

Fix the registry used when publishing

---

packages/iris-grid/src/IrisGrid.jsx
packages/iris-grid/src/PendingDataBottomBar.tsx

- Ctrl+S only triggers a save if the table is editable, has pending data, and there are no errors
- Ctrl+Alt+S only discards if the table is editable and there's pending data
- Save error message is now correctly displayed by PendingDataBottomBar
- Use a circle checkmark instead of the square checkbox
Related to https://deephaven.atlassian.net/browse/DH-11388

Fix up some issues with input tables

---

.github/workflows/create-release.yml

Remove unnecessary uses flag

---

.github/workflows/create-release.yml

- Remove unnecessary uses flag
- Pass the GITHUB_AUTH as an env var in the run command

fix release action

---

packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx

This way table plugins state is saved with the grid state.

Allow JS table plugins to save to workspace

---

packages/utils/src/TextUtils.test.ts
packages/utils/src/TextUtils.ts

- Add optional conjunction arg to TextUtil.join
- Add unit test

Add optional conjunction arg to TextUtil.join

---

packages/code-studio/src/main/AppInit.jsx
packages/code-studio/src/settings/ShortcutsSectionContent.tsx
packages/components/src/shortcuts/Shortcut.ts
packages/components/src/shortcuts/ShortcutRegistry.ts
packages/redux/package.json
packages/redux/src/selectors.ts
packages/redux/src/store.ts

Persist shortcut definitions

---

packages/chart/src/ChartUtils.js

- Was mapping the constant to the wrong value for the data
- Fixes #290
Tested using the steps in the bug

Fix OHLC plots

---

packages/code-studio/src/main/AppMainContainer.jsx

Fix panels menu not working correctly

---

jest.config.cjs

The way it gets thresholds on the diff is not how I expected

Disable code coverage

---

.github/workflows/publish-nightly.yml

- fetch-depth was being used on the wrong action

Fix the nightly build

---

packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx
packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx

Update FilterSetManagetPanel and IrisGridPanel to use the new hydrate/dehydrate methods for quick and advanced filters

Fix unusable filter set manager

---

packages/dashboard/src/layout/GoldenLayout.scss
packages/golden-layout/src/scss/goldenlayout-base.scss
packages/grid/src/Grid.scss

Also see matching PR in enterprise, that adds pointer/grabbing cursor for dashboards tabs.

DH-11786: Cursor inconsistent between dragging dashboard and dragging panel

---

packages/dashboard-core-plugins/jest.config.cjs
packages/dashboard/jest.config.cjs

Rename jest.config.js to .cjs, fix baseConfig path

Fix unit tests not running on dashboard and core-plugins packages

---

packages/dashboard-core-plugins/src/ConsolePlugin.tsx

Pass unwrapped notebook panel to `getLastUsedPanelOfType`

Fix Add to Active Notebook action

---

packages/iris-grid/src/IrisGridTreeTableModel.js

missing formatting and I don't think the intersection is quite right but it's quite the snack

tree table snapshots

---

packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx

fix console error message for single line errors

---

packages/iris-grid/src/IrisGrid.jsx

Should be able to theme IrisGrid to look like however we want
Fixes #355

Allow IrisGrid to be themeable

---

packages/babel-preset/index.js
packages/code-studio/src/main/SessionUtils.ts
packages/jsapi-shim/src/dh.ts
packages/jsapi-shim/src/dh.types.ts
packages/jsapi-shim/tsconfig.json
packages/tsconfig/tsconfig.json

Adds some TS to the JS API
Need to add overrides and extended types in enterprise so the enterprise shim doesn't cause TS errors

Add types for JS API

---

packages/code-studio/src/main/AppInit.jsx
packages/code-studio/src/settings/FormattingSectionContent.jsx
packages/code-studio/src/settings/FormattingSectionContent.scss
packages/code-studio/src/settings/FormattingSectionContent.test.jsx
packages/code-studio/src/storage/LocalWorkspaceStorage.ts
packages/code-studio/src/storage/WorkspaceStorage.ts

- Add reset buttons to default decimal, date, integer formats
- Fixes #371

Settings Reset to Defaults

---

packages/iris-grid/src/IrisGrid.jsx

This is pretty standard but I don't like the name similarity with the showSearchBar prop. Suggestions are welcomed.

hide search bar toggle if serverConfig showSearch is false

---

packages/code-studio/package-lock.json
packages/code-studio/package.json
packages/dashboard-core-plugins/package-lock.json
packages/dashboard-core-plugins/package.json
packages/file-explorer/package-lock.json
packages/file-explorer/package.json

- Update follow-redirects package to address CVE: https://nvd.nist.gov/vuln/detail/CVE-2022-0155

Dependabot fixes - follow-redirect issue

---

.github/workflows/node.js.yml

It's not currently configured correctly for our coverage reporting, and is just annoying.
See #394 for fixing the coverage reporting.

Disable Codecov

---

packages/dashboard-core-plugins/src/GridPlugin.tsx
packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
packages/iris-grid/src/index.ts

- Now you can use GridPlugin and update the theme by passing one in
- Fixes #393

Allow theme to be passed in as a prop to GridPlugin and IrisGridPanel

---

packages/grid/src/GridMetricCalculator.ts

Fix for resizing columns

---

packages/code-studio/src/storage/PouchStorageTable.ts

Fix pouchdb deprecation warning when starting up UI

---

packages/dashboard-core-plugins/src/ChartPlugin.tsx
packages/dashboard-core-plugins/src/ConsolePlugin.tsx
packages/dashboard-core-plugins/src/FilterPlugin.tsx
packages/dashboard-core-plugins/src/GridPlugin.tsx
packages/dashboard-core-plugins/src/LinkerPlugin.tsx
packages/dashboard-core-plugins/src/MarkdownPlugin.tsx
packages/dashboard-core-plugins/src/PandasPlugin.tsx
packages/dashboard-core-plugins/src/index.test.tsx
packages/dashboard/src/DashboardPlugin.ts
packages/iris-grid/src/index.ts
packages/mocks/src/golden-layout.js
packages/redux/src/createMockStore.ts
packages/redux/src/index.ts

- Make dashboard props for plugin optional
- Add an assertIsDashboardPluginProps method to assert optional dashboard props
- Add unit tests to verify
Fixes #392

Fix up Dashboard Plugin props

---

packages/dashboard-core-plugins/src/panels/FilterSetManager.tsx
packages/dashboard-core-plugins/src/panels/FilterSetManagerPanel.jsx

Fix active filter set after edit

---

packages/console/src/Console.jsx
packages/dashboard-core-plugins/src/panels/ConsolePanel.jsx

- In Community, ConsolePanel is always loaded, so remove transition/isLoaded flags
- Keep track of objects in the ConsolePanel and pass it into Console
Fixes #405

Fix the objects not being loaded with console

---

packages/components/src/popper/Popper.tsx
packages/components/src/popper/Tooltip.tsx
packages/console/src/command-history/CommandHistoryItemTooltip.jsx
packages/console/src/command-history/CommandHistoryItemTooltip.scss

Resolves #415
Makes separate scroll panes for code and result.

Improve command history tooltip layout

---

packages/iris-grid/src/sidebar/CustomColumnBuilder.jsx

UX was reviewed by Don already.

DH-10115: add temporary success state to save custom column button

---

package-lock.json
package.json
packages/code-studio/package.json
packages/components/package-lock.json
packages/components/package.json
packages/embed-grid/package-lock.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/icons/package.json

New packages were just published yesterday. Not sure why they're causing errors, but pinning the packages to prevent errors

Pin the fontawesome deps

---

package-lock.json
packages/code-studio/src/main/AppInit.jsx
packages/code-studio/src/main/AppMainContainer.jsx
packages/code-studio/src/main/AppMainContainer.test.jsx
packages/code-studio/src/main/LayoutStorage.ts
packages/code-studio/src/main/UserLayoutUtils.test.ts
packages/code-studio/src/main/UserLayoutUtils.ts
packages/code-studio/src/main/WebdavLayoutStorage.ts

- Was broken with the previous change to export filterSets and links with layout export
- Added tests to cover legacy imports
Fixes #438

Fix layout import/export, add tests

---

packages/dashboard-core-plugins/src/panels/IrisGridPanel.jsx
packages/dashboard-core-plugins/src/panels/IrisGridPanel.scss
packages/dashboard-core-plugins/src/panels/WidgetPanel.jsx
packages/dashboard-core-plugins/src/panels/WidgetPanelTooltip.jsx

This is just the OSS portion of the work already merged in Ent. Main difference is the lack of `queryName` in WidgetPanel so far.

DH-11189: add rowCount tooltip to table panel tab

---

packages/code-studio/package-lock.json
packages/code-studio/package.json
packages/code-studio/src/styleguide/StyleGuide.test.jsx
packages/components/package-lock.json
packages/embed-grid/package-lock.json
packages/golden-layout/package-lock.json
packages/mocks/src/monaco-editor.js
packages/stylelint-config/package-lock.json
packages/utils/package-lock.json

add component mount test for styleguide

---

packages/console/src/notebook/ScriptEditor.jsx

remove last line from editor selection if cursor is in column 1

---

packages/console/src/Console.jsx
packages/console/src/Console.scss
packages/console/src/console-history/ConsoleHistoryResultInProgress.scss

- Fix disabled not being passed to history
- Clean up styling of disabled progress button
- Disable pointer events

Fix some console history styling

---

packages/code-studio/src/settings/FormattingSectionContent.jsx
packages/code-studio/src/settings/FormattingSectionContent.test.jsx

Part of issue 440. This also adds some missed `for` attributes on a few labels.

rm enzyme: FormattingSectionContent refactor

---

packages/console/src/ConsoleStatusBar.test.jsx

rm enzyme: refactor ConsoleStatusBar to use RTL

---

lerna.json
package-lock.json
package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/log/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/utils/package.json

* `grid`, `iris-grid`
* [#495](https://github.com/deephaven/web-client-ui/pull/495) Always populate the calculated item size maps ([@mofojed](https://github.com/mofojed))
* `chart`, `code-studio`, `components`, `console`, `dashboard-core-plugins`, `dashboard`, `embed-grid`, `file-explorer`, `golden-layout`, `grid`, `icons`, `iris-grid`, `jsapi-shim`, `log`, `react-hooks`, `redux`, `storage`, `utils`
* [#501](https://github.com/deephaven/web-client-ui/pull/501) Update package.json with file: links ([@mofojed](https://github.com/mofojed))

web v0.11.4

---

packages/components/src/RadioItem.tsx
packages/components/src/navigation/MenuItem.tsx
packages/components/src/navigation/Page.tsx
packages/iris-grid/src/IrisGrid.jsx
packages/iris-grid/src/sidebar/TableCsvExporter.jsx

Add data-testid attributes to allow test automation to use CSV Download.

Add data-testid Attributes for CSV Download

---

packages/eslint-config/index.js
packages/iris-grid/src/mousehandlers/IrisGridCellOverflowMouseHandler.ts

- Requires all if statements to have curly braces
- Fixes #353

Enable the curly eslint rule

---

packages/golden-layout/src/js/config/defaultConfig.js

Americanize golden-layout maximise label spelling

---

packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.jsx

Don't check isColumnFrozen unless we click on a column

DH-12435 Fix exception on right-click in the empty space of the table

---

packages/code-studio/src/styleguide/Grids.jsx
packages/grid/src/Grid.tsx
packages/grid/src/ThemeContext.ts
packages/grid/src/index.ts

- Added theme context to styleguide as well
- Fixes #516

Add grid ThemeContext for providing the theme in a context

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/stylelint-config/package.json

* `code-studio`, `grid`
* [#517](https://github.com/deephaven/web-client-ui/pull/517) Add grid ThemeContext for providing the theme in a context ([@mofojed](https://github.com/mofojed))
* `components`, `dashboard-core-plugins`, `iris-grid`
* [#479](https://github.com/deephaven/web-client-ui/pull/479) DH-12233 Save rollups, aggregations, selectDistinct in filter sets ([@vbabich](https://github.com/vbabich))
* `dashboard-core-plugins`, `golden-layout`, `iris-grid`
* [#519](https://github.com/deephaven/web-client-ui/pull/519) Focus irisgrid on tab click ([@dsmmcken](https://github.com/dsmmcken))
* `iris-grid`
* [#527](https://github.com/deephaven/web-client-ui/pull/527) Fix CSV download formatting ([@vbabich](https://github.com/vbabich))
* …

Version Bump v0.11.6

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/dashboard-core-plugins/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/iris-grid/package.json

* `components`, `dashboard-core-plugins`, `iris-grid`
* [#539](https://github.com/deephaven/web-client-ui/pull/539) DH-12498: Swap vsIssues icon for vsWarning icon ([@dsmmcken](https://github.com/dsmmcken))
* `console`
* [#538](https://github.com/deephaven/web-client-ui/pull/538) DH-10208 Fix arrow up at top of history loading empty history commands ([@mattrunyon](https://github.com/mattrunyon))
* `file-explorer`
* [#535](https://github.com/deephaven/web-client-ui/pull/535) Fix vertical scroll bar when FileExplorer tab shown ([@mofojed](https://github.com/mofojed))
* `iris-grid`
* [#531](https://github.com/deephaven/web-client-ui/pull/531) Fix IrisGridPanel crashing when stacking formatting rules ([@vbabich](https://github.com/vbabich))
* …

Version Bump v0.11.7

---

.github/workflows/cla.yml
README.md
packages/code-studio/README.md

- Clean up some instructions
- Add cla.yml for enabling clabot
- Removed references to Enterprise - Enterprise depends on Community, not the other way around.

Update README with some onboarding updates, contributing instructions

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/embed-grid/package.json
packages/iris-grid/package.json

* `console`
* [#538](https://github.com/deephaven/web-client-ui/pull/538) DH-10208 Fix arrow up at top of history loading empty history commands ([@mattrunyon](https://github.com/mattrunyon))
* `iris-grid`
* [#544](https://github.com/deephaven/web-client-ui/pull/544) Fix cell overflow button overlapping scroll bar and not truncating text with row header ([@mattrunyon](https://github.com/mattrunyon))
* [#534](https://github.com/deephaven/web-client-ui/pull/534) Fix column tooltip not repositioning correctly when resizing columns ([@mofojed](https://github.com/mofojed))
* `code-studio`
* [#533](https://github.com/deephaven/web-client-ui/pull/533) Update README with some onboarding updates, contributing instructions ([@mofojed](https://github.com/mofojed))
- Matthew Runyon …

Version Bump v0.11.8

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/dashboard-core-plugins/package.json
packages/embed-grid/package.json
packages/grid/package.json
packages/iris-grid/package.json

* `components`
* [#550](https://github.com/deephaven/web-client-ui/pull/550) Added data-testid ([@SparkyFnay](https://github.com/SparkyFnay))
* `grid`
* [#543](https://github.com/deephaven/web-client-ui/pull/543) DH-10111 Fix missing horizontal scroll bar for single column tables ([@mattrunyon](https://github.com/mattrunyon))
- Matthew Runyon ([@mattrunyon](https://github.com/mattrunyon))
- Tony Zhou ([@SparkyFnay](https://github.com/SparkyFnay))

Version Bump web-v0.11.9

---

examples/component-template/package.json
lerna.json
package-lock.json
packages/babel-preset/package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/log/package.json
packages/mocks/package.json
packages/prettier-config/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/stylelint-config/package.json
packages/tsconfig/package.json
packages/utils/package.json

* `code-studio`, `console`, `dashboard-core-plugins`
* [#548](https://github.com/deephaven/web-client-ui/pull/548) Remove dependency on jszip from @deephaven/console ([@mofojed](https://github.com/mofojed))
* `grid`
* [#571](https://github.com/deephaven/web-client-ui/pull/571) Don't scroll columns into view on click ([@dsmmcken](https://github.com/dsmmcken))
* `code-studio`
* [#565](https://github.com/deephaven/web-client-ui/pull/565) remove enzyme code studio and replace with react-testing-library ([@SparkyFnay](https://github.com/SparkyFnay))
* `code-studio`, `components`, `console`, `dashboard-core-plugins`, `dashboard`, `embed-grid`, `eslint-config`, `file-explorer`, `grid`, `icons`, `iris-grid`, `react-hooks`, `storage`
* [#553](https://github.com/deephaven/web-client-ui/pull/553) …

web v0.12.0

---

packages/grid/src/GridRenderer.ts

Fix floating column border not touching top and bottom

---

packages/components/src/context-actions/ContextActionUtils.ts

Improved clipboard write handling

---

lerna.json
package-lock.json
packages/babel-preset/package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/filters/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/mocks/package.json
packages/prettier-config/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/stylelint-config/package.json
packages/tsconfig/package.json
packages/utils/package.json

* `chart`, `code-studio`, `dashboard-core-plugins`, `embed-grid`, `filters`, `iris-grid`, `jsapi-utils`, `redux`, `storage`
* [#576](https://github.com/deephaven/web-client-ui/pull/576) BREAKING: Clean up iris-grid dependencies ([@mofojed](https://github.com/mofojed))
* `components`
* [#583](https://github.com/deephaven/web-client-ui/pull/583) Improved clipboard write handling ([@SparkyFnay](https://github.com/SparkyFnay))
* `golden-layout`
* [#594](https://github.com/deephaven/web-client-ui/pull/594) Listen for click instead of mousedown on golden layout Tabs ([@mofojed](https://github.com/mofojed))
* `grid`, `iris-grid`
* [#566](https://github.com/deephaven/web-client-ui/pull/566) Fix various layout hint issues ([@mattrunyon](https://github.com/mattrunyon))
* `iris-grid`
* …

Version Bump v0.13.0

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/dashboard-core-plugins/package.json
packages/embed-grid/package.json
packages/grid/package.json
packages/iris-grid/package.json

* `grid`
* [#600](https://github.com/deephaven/web-client-ui/pull/600) Fix unintended scroll wheel behavior for single row and column tables ([@mattrunyon](https://github.com/mattrunyon))
- Matthew Runyon ([@mattrunyon](https://github.com/mattrunyon))

Version Bump v0.13.1

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/grid/package.json
packages/iris-grid/package.json

* `grid`
* [#598](https://github.com/deephaven/web-client-ui/pull/598) Refactor GridUtils move items ([@mattrunyon](https://github.com/mattrunyon))
* `iris-grid`
* [#608](https://github.com/deephaven/web-client-ui/pull/608) Fixed column Header not being saved in table downloads to CSV file ([@SparkyFnay](https://github.com/SparkyFnay))
* [#604](https://github.com/deephaven/web-client-ui/pull/604) DH-12627 Fix Aggregations formatting when only one operation on a column ([@mofojed](https://github.com/mofojed))
* `code-studio`, `grid`
* [#603](https://github.com/deephaven/web-client-ui/pull/603) Fix grid resizing automatically when outer parent size not specified ([@mofojed](https://github.com/mofojed))
* Other
* [#607](https://github.com/deephaven/web-client-ui/pull/607) Remove enzyme from …

Version Bump v0.13.2

---

lerna.json
package-lock.json
packages/babel-preset/package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/filters/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/mocks/package.json
packages/prettier-config/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/stylelint-config/package.json
packages/tsconfig/package.json
packages/utils/package.json

* `code-studio`, `components`, `dashboard-core-plugins`, `embed-grid`, `filters`, `grid`, `iris-grid`, `jsapi-shim`, `jsapi-utils`, `utils`
* [#605](https://github.com/deephaven/web-client-ui/pull/605) Convert Iris-Grid from Javascript to Typescript ([@SparkyFnay](https://github.com/SparkyFnay))
* `grid`
* [#613](https://github.com/deephaven/web-client-ui/pull/613) Add support for moving ranges within grids ([@mattrunyon](https://github.com/mattrunyon))
* `code-studio`, `components`, `dashboard-core-plugins`, `embed-grid`, `filters`, `grid`, `iris-grid`, `jsapi-shim`, `jsapi-utils`, `utils`
* [#605](https://github.com/deephaven/web-client-ui/pull/605) Convert Iris-Grid from Javascript to Typescript ([@SparkyFnay](https://github.com/SparkyFnay))
* `code-studio`, `components`, `console`, …

Version Bump v0.14.0

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json

* `code-studio`, `console`, `dashboard-core-plugins`, `icons`
* [#633](https://github.com/deephaven/web-client-ui/pull/633) Adds dhRunSelection icon and pandas icon ([@dsmmcken](https://github.com/dsmmcken))
* `iris-grid`
* [#639](https://github.com/deephaven/web-client-ui/pull/639) Fix filters in IrisGrid ([@mofojed](https://github.com/mofojed))
* [#627](https://github.com/deephaven/web-client-ui/pull/627) Fix column tooltip error when side menu is opened ([@mattrunyon](https://github.com/mattrunyon))
* [#631](https://github.com/deephaven/web-client-ui/pull/631) iris-grid displays null instead of empty when fast scrolling for string columns ([@SparkyFnay](https://github.com/SparkyFnay))
* [#625](https://github.com/deephaven/web-client-ui/pull/625) Iris grid circular dependency …

Version Bump v0.14.1

---

packages/code-studio/src/main/AppMainContainer.jsx
packages/code-studio/src/main/WidgetUtils.ts

- Was trying to fetch the pandas table with the wrong variable type specified
- Fixes #632

Fix Pandas table not re-hydrating properly

---

lerna.json
package-lock.json
packages/babel-preset/package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/filters/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/mocks/package.json
packages/prettier-config/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/stylelint-config/package.json
packages/tsconfig/package.json
packages/utils/package.json

* `code-studio`, `iris-grid`, `redux`
* [#634](https://github.com/deephaven/web-client-ui/pull/634) DH-12796: fixed redux workspace types redeclared in code-studio error ([@SparkyFnay](https://github.com/SparkyFnay))
* `grid`, `iris-grid`
* [#638](https://github.com/deephaven/web-client-ui/pull/638) Added Goto row feature in Iris Grid ([@SparkyFnay](https://github.com/SparkyFnay))
* `chart`, `jsapi-shim`
* [#545](https://github.com/deephaven/web-client-ui/pull/545) Treemaps ([@mofojed](https://github.com/mofojed))
* [#649](https://github.com/deephaven/web-client-ui/pull/649) Fix filter set capture failing on timestamp column advanced filters, DH-12754 ([@vbabich](https://github.com/vbabich))
* `code-studio`, `iris-grid`, `redux`
* …

Version Bump v0.15.0

---

packages/components/src/Checkbox.tsx
packages/components/src/Option.tsx
packages/components/src/Select.tsx
packages/components/src/SelectValueList.scss
packages/components/src/SelectValueList.tsx

Update components:
- Checkbox: add optional `name` prop
- Option: optional `disabled` prop
- Select: optional `name` and `onBlur` props
- SelectValueList: optional `className` and `isInvalid` props

Component updates for Parameterized Query UI

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/grid/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/redux/package.json
packages/storage/package.json

* [#673](https://github.com/deephaven/web-client-ui/pull/673) Allow copying the widget name from tab context menu ([@dsmmcken](https://github.com/dsmmcken))
* `grid`, `iris-grid`
* [#657](https://github.com/deephaven/web-client-ui/pull/657) Go to row UX cleanup ([@dsmmcken](https://github.com/dsmmcken))
* [#615](https://github.com/deephaven/web-client-ui/pull/615) Scrollbar Selection Ticks ([@SparkyFnay](https://github.com/SparkyFnay))
* `components`, `console`, `jsapi-shim`
* [#646](https://github.com/deephaven/web-client-ui/pull/646) Convert Console to typescript ([@SparkyFnay](https://github.com/SparkyFnay))
* `log`
* [#645](https://github.com/deephaven/web-client-ui/pull/645) Convert Log package to typescript ([@SparkyFnay](https://github.com/SparkyFnay))
* …

Version Bump v0.15.1

---

package-lock.json
packages/dashboard/src/layout/LayoutUtils.ts

- Change isReactComponentConfig and isStackItemConfig to check the type instead
- Do not assert it is a react component config

Fix up dashboard layout utils TS conversion changes

---

packages/iris-grid/src/IrisGridCellOverflowModal.tsx

Add "Copy" button to cell overflow preview modal

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/filters/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/tsconfig/package.json

* `code-studio`, `dashboard-core-plugins`, `grid`, `iris-grid`, `jsapi-shim`, `tsconfig`
* [#642](https://github.com/deephaven/web-client-ui/pull/642) DH-12182: Column Grouping ([@mattrunyon](https://github.com/mattrunyon))
* `iris-grid`
* [#683](https://github.com/deephaven/web-client-ui/pull/683) Add "Copy" button to cell overflow preview modal ([@dsmmcken](https://github.com/dsmmcken))
* `dashboard-core-plugins`, `dashboard`, `golden-layout`, `redux`
* [#659](https://github.com/deephaven/web-client-ui/pull/659) dashboard typescript conversion ([@SparkyFnay](https://github.com/SparkyFnay))
* `iris-grid`, `jsapi-utils`
* [#681](https://github.com/deephaven/web-client-ui/pull/681) Fix broken advanced filter creator ([@dsmmcken](https://github.com/dsmmcken))
* `dashboard`
* …

Version Bump v0.15.2

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/iris-grid/package.json

* `dashboard`, `iris-grid`
* [#697](https://github.com/deephaven/web-client-ui/pull/697) Fix layout utils react config ([@mofojed](https://github.com/mofojed))

Version Bump v0.15.3

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/grid/package.json
packages/iris-grid/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/redux/package.json
packages/utils/package.json

* `chart`, `components`, `console`, `dashboard-core-plugins`, `jsapi-shim`, `redux`
* [#718](https://github.com/deephaven/web-client-ui/pull/718) Heap size UI ([@SparkyFnay](https://github.com/SparkyFnay))
* `chart`, `dashboard-core-plugins`, `jsapi-shim`
* [#723](https://github.com/deephaven/web-client-ui/pull/723) @deephaven/chart TypeScript Conversion ([@SparkyFnay](https://github.com/SparkyFnay))
* `chart`, `code-studio`, `components`, `console`, `dashboard-core-plugins`, `dashboard`, `file-explorer`, `grid`, `iris-grid`, `jsapi-shim`, `jsapi-utils`, `redux`, `utils`
* [#716](https://github.com/deephaven/web-client-ui/pull/716) @deephaven/code-studio TypeScript Conversion ([@SparkyFnay](https://github.com/SparkyFnay))
* …

Version Bump v0.15.6

---

packages/components/src/Checkbox.tsx
packages/components/src/Option.tsx
packages/components/src/Select.tsx
packages/components/src/SelectValueList.scss
packages/components/src/SelectValueList.tsx

* Add Checkbox name prop
* Add SelectValueList className prop
* Add isInvalid style and prop to SelectValueList
* Add name, onBlur to Select, add disabled to Option

Component updates for Parameterized Query UI (cherry-pick #666)

---

packages/console/src/ConsoleInput.tsx

Blank commands not added to history

---

packages/grid/src/GridRenderer.ts
packages/utils/src/ColorUtils.ts

Fixes a performance issue introduced by #757

Memoize column header isDark to fix performance issue

---

packages/iris-grid/src/AdvancedFilterCreator.jsx
packages/iris-grid/src/AdvancedFilterCreatorFilterItem.scss
packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
packages/jsapi-utils/src/TableUtils.test.js
packages/jsapi-utils/src/TableUtils.ts

Cherry picked from https://github.com/deephaven/web-client-ui/pull/736
Should partially improve DH-12869 (though does not completely solve the spinning Advanced Filter select list)

Cherry pick: DH-13043 Filter validation fixes and nulls in Advanced Filters

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/jsapi-utils/package.json
packages/redux/package.json

* `code-studio`, `components`, `jsapi-components`, `jsapi-utils`
* [#762](https://github.com/deephaven/web-client-ui/pull/762) DH-12970 TableInput component for Parameterized Queries ([@vbabich](https://github.com/vbabich))
* `code-studio`, `components`
* [#756](https://github.com/deephaven/web-client-ui/pull/756) DH-12965 Date/DateTime inputs ([@vbabich](https://github.com/vbabich))
* `components`
* [#744](https://github.com/deephaven/web-client-ui/pull/744) DH-12969 Add EditableItemList component ([@vbabich](https://github.com/vbabich))
* `iris-grid`, `jsapi-utils`
* [#767](https://github.com/deephaven/web-client-ui/pull/767) DH-13043 Filter validation fixes and nulls in Advanced Filters ([@mofojed](https://github.com/mofojed))
- …

Version Bump v0.13.6

---

packages/dashboard-core-plugins/src/controls/markdown/MarkdownStartPage.tsx
packages/dashboard-core-plugins/src/panels/MarkdownPanel.test.tsx
packages/dashboard-core-plugins/src/panels/MarkdownPanel.tsx
packages/dashboard-core-plugins/src/panels/Panel.test.tsx
packages/dashboard-core-plugins/src/panels/Panel.tsx
packages/dashboard-core-plugins/src/panels/PanelContextMenu.test.tsx
packages/dashboard-core-plugins/src/panels/PanelContextMenu.tsx
packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx

- Some tests were failing after the latest golden-layout changes
- import type instead of a straight import

Fix up imports after golden-layout changes

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/jsapi-utils/package.json
packages/redux/package.json

- DH-12969 Add EditableItemList component (#744)
- DH-13043 Filter validation fixes and nulls in Advanced Filters (#767)
- DH-12965 Date/DateTime inputs (#756)
- DH-12970 TableInput component for Parameterized Queries (#762)
- Fix tsconfig formatting (#774)
- Version Bump v0.13.7

Version Bump v0.13.7

---

lerna.json
package-lock.json
packages/babel-preset/package.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-chart/package.json
packages/embed-grid/package.json
packages/eslint-config/package.json
packages/file-explorer/package.json
packages/filters/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/icons/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/log/package.json
packages/mocks/package.json
packages/prettier-config/package.json
packages/react-hooks/package.json
packages/redux/package.json
packages/storage/package.json
packages/stylelint-config/package.json
packages/tsconfig/package.json
packages/utils/package.json

* `code-studio`, `components`, `dashboard-core-plugins`, `dashboard`, `embed-chart`, `embed-grid`, `golden-layout`
* [#759](https://github.com/deephaven/web-client-ui/pull/759) Convert golden-layout to ES Modules ([@mattrunyon](https://github.com/mattrunyon))
* [#777](https://github.com/deephaven/web-client-ui/pull/777) 751 add path information ([@jason-wang24](https://github.com/jason-wang24))
* `components`, `dashboard-core-plugins`, `file-explorer`
* [#758](https://github.com/deephaven/web-client-ui/pull/758) Add path information and breadcrumb interactivity to NewItemModal ([@jason-wang24](https://github.com/jason-wang24))
* `code-studio`, `components`, `jsapi-components`
* [#771](https://github.com/deephaven/web-client-ui/pull/771) Cherry-pick Table Input …

Version bump v0.18.0

---

packages/grid/src/Grid.test.tsx
packages/iris-grid/src/IrisGridProxyModel.ts

Unable to edit input table

---

packages/iris-grid/src/AdvancedFilterCreator.jsx
packages/iris-grid/src/AdvancedFilterCreatorFilterItem.tsx
packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.jsx

- Manual cherry-pick of https://github.com/deephaven/web-client-ui/pull/681
- Without this change, the fix https://github.com/deephaven/web-client-ui/pull/767 has broken Advanced Filters in v0.13

Fix broken advanced filter creator

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/dashboard-core-plugins/package.json

* [#801](https://github.com/deephaven/web-client-ui/pull/801) Add NotebookPanel hydration function ([@mofojed](https://github.com/mofojed))
* [#791](https://github.com/deephaven/web-client-ui/pull/791) Allow up to 0.05% drop in code coverage per commit ([@mofojed](https://github.com/mofojed))

Version Bump v0.19.1

---

packages/iris-grid/src/IrisGridTestUtils.ts
packages/iris-grid/src/sidebar/TableCsvExporter.test.tsx
packages/iris-grid/src/sidebar/TableCsvExporter.tsx

Catch and display errors in downloading in the `TableCsvExporter` component

---

packages/file-explorer/src/NewItemModal.tsx

Refactor <button> to <Button> in NewItemModal

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/jsapi-utils/package.json
packages/redux/package.json

* `iris-grid`
* [#784](https://github.com/deephaven/web-client-ui/pull/784) Fix broken advanced filter creator ([@mofojed](https://github.com/mofojed))

Version Bump v0.13.8

---

packages/components/src/EditableItemList.test.tsx
packages/components/src/EditableItemList.tsx

Ignore empty Editable List input, add unit tests

DH-13511 Ignore empty Editable List input

---

packages/code-studio/src/settings/FormattingSectionContent.tsx

Fix default formatting rule always showing empty error

---

packages/components/src/EditableItemList.test.tsx
packages/components/src/EditableItemList.tsx

DH-13511 Ignore empty EditableList input

---

packages/components/src/DateTimeInput.test.tsx
packages/components/src/DateTimeInput.tsx

- Update `DateTimeInput` to fill in the missing time digits with zeros in the `onChange` argument
- Displayed input value not changed until the blur event. On blur the displayed value is updated to match the one sent in onChange
- Date part of the value stays unchanged
- Added unit tests for the new behaviour

DH-13548 Fix DateTimeInputs missing nanos

---

__mocks__/dh-core.js
packages/chart/src/ChartUtils.test.ts
packages/chart/src/ChartUtils.ts
packages/chart/src/FigureChartModel.ts
packages/jsapi-shim/src/dh.types.ts

- UI Side of https://github.com/deephaven/deephaven-core/issues/2835
- Support multiple charts in one figure
- Automatically update the domain of the axes of the charts to be positioned correctly row/col of the chart
- Tested using the following snippet to create some figures (used Groovy as the rowspan/colspan are not available in Python yet):
```
tt = timeTable("00:00:00.01").update("X=0.01*ii", "Y=ii*ii", "S=sin(X)", "C=cos(X)", "T=tan(X)").tail(1000)
f1 = figure().plot("Y", tt, "X", "Y").show()
f2 = figure(2, 1)
.newChart(0,0).plot("S", tt, "X", "S")
.newChart(1,0).plot("C", tt, "X", "C")
.show()
f3_c = figure(2, 2)
.newChart(0,0).plot("T", tt, "X", "T").colSpan(2)
.newChart(1,0).plot("S", tt, "X", "S")
.newChart(1,1).plot("C", tt, "X", "C")
.show()
f3_r = figure(2, 2) …
```

DH-13577 Subplots

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-chart/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/golden-layout/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/pouch-storage/package.json

* `code-studio`, `components`, `iris-grid`
* [#860](https://github.com/deephaven/web-client-ui/pull/860) Replaces old Deephaven logo spinner with more minimal animation ([@dsmmcken](https://github.com/dsmmcken))
* `golden-layout`
* [#868](https://github.com/deephaven/web-client-ui/pull/868) Remove reference to TouchEvent ([@mofojed](https://github.com/mofojed))
* `components`, `console`, `dashboard-core-plugins`
* [#861](https://github.com/deephaven/web-client-ui/pull/861) Fixes command history not scrolled to bottom on load ([@dsmmcken](https://github.com/dsmmcken))
- Don ([@dsmmcken](https://github.com/dsmmcken))

Version Bump v0.21.1

---

packages/iris-grid/src/IrisGrid.tsx

Fix page flicker when advanced filters open

---

packages/dashboard-core-plugins/src/linker/Linker.tsx
packages/dashboard-core-plugins/src/linker/LinkerUtils.tsx
packages/iris-grid/src/IrisGrid.jsx
packages/iris-grid/src/IrisGrid.test.jsx
packages/jsapi-utils/src/TableUtils.ts

Fix null in links on grouped columns (#892)

---

packages/iris-grid/src/IrisGrid.tsx
packages/iris-grid/src/TreeTableViewportUpdater.tsx
packages/iris-grid/src/sidebar/RollupRows.tsx

These are items which are only used in enterprise at the moment and were broken after TS conversions.

Bug fixes for enterprise silverheels

---

lerna.json
package-lock.json
packages/chart/package.json
packages/code-studio/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-chart/package.json
packages/embed-grid/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/jsapi-shim/package.json
packages/jsapi-utils/package.json
packages/pouch-storage/package.json
packages/redux/package.json

* `code-studio`, `jsapi-shim`, `redux`
* [#893](https://github.com/deephaven/web-client-ui/pull/893) Added engine version to settings menu ([@Zhou-Ziheng](https://github.com/Zhou-Ziheng))
* `iris-grid`
* [#899](https://github.com/deephaven/web-client-ui/pull/899) Bug fixes for enterprise silverheels ([@mattrunyon](https://github.com/mattrunyon))
* `dashboard-core-plugins`, `iris-grid`, `jsapi-utils`
* [#892](https://github.com/deephaven/web-client-ui/pull/892) Fix null in links on grouped columns ([@vbabich](https://github.com/vbabich))
* `dashboard-core-plugins`, `iris-grid`
* [#898](https://github.com/deephaven/web-client-ui/pull/898) Persist iris grid advanced settings ([@mattrunyon](https://github.com/mattrunyon))
- Matthew Runyon ([@mattrunyon](https://github.com/mattrunyon))
- Tony …

Version Bump v0.22.1

---

packages/grid/src/key-handlers/SelectionKeyHandler.ts

Fix Linker Esc shortcut (#907)

---

packages/iris-grid/src/IrisGridTableModelTemplate.ts

Add optional parameter choosing whether or not to consolidate ranges in IrisGridTableModel snapshot

---

packages/grid/src/GridMetricCalculator.ts

Fix dragging empty tables

---

codecov.yml

- We don't bother checking it anyway

Disable patch checking for codecov

---

packages/code-studio/src/main/AppControlsMenu.tsx
packages/code-studio/src/main/AppMainContainer.tsx
packages/code-studio/src/settings/FormattingSectionContent.tsx
packages/code-studio/src/storage/LocalWorkspaceStorage.ts
packages/code-studio/src/styleguide/DraggableLists.tsx
packages/code-studio/src/styleguide/MockIrisGridTreeModel.ts
packages/code-studio/src/styleguide/StyleGuideInit.tsx
packages/code-studio/tsconfig.json
packages/embed-chart/tsconfig.json
packages/embed-grid/tsconfig.json
tsconfig.json

Code studio was not being type checked on builds (errors would still show up in VSCode if you had the file open). This should fix the config so code-studio is type checked on build. Also fixes a few TS errors from code-studio

Fix tsconfig to type check code studio

---

package-lock.json
package.json
packages/code-studio/src/styleguide/Charts.tsx
packages/components/src/ValidateLabelInput.tsx
packages/console/src/log/LogView.tsx
packages/file-explorer/src/FileUtils.ts
packages/golden-layout/src/config/Config.ts
packages/iris-grid/src/AdvancedFilterCreatorSelectValueList.tsx

A few minor types needed to be adjusted/tightened due to the upgrade

Upgrade to TypeScript 4.9

---

packages/file-explorer/src/FileListItemEditor.test.tsx
packages/file-explorer/src/FileListItemEditor.tsx
packages/file-explorer/src/FileUtils.test.ts

- `FileListItemEditor` - 100% coverage
- `FileUtils` - 88% coverage

FileExplorer tests

---

packages/components/src/modal/Modal.tsx

Change onclick to separate mousedown and mouseup events in Modal.tsx

---

packages/dashboard-core-plugins/src/panels/ChartColumnSelectorOverlay.test.tsx
packages/dashboard-core-plugins/src/panels/ChartFilterOverlay.test.tsx
packages/file-explorer/src/FileExplorerToolbar.test.tsx

- `ChartColumnSelectorOverlay` mount/unmount
- `FileExplorerToolbar` mount/unmount
- `ChartFilterOverlay` mount/unmount and other small tests

Add File Explorer Toolbar and small Chart Panel mount tests

---

packages/components/src/SocketedButton.tsx
packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.test.tsx
packages/dashboard-core-plugins/src/controls/dropdown-filter/DropdownFilter.tsx
packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.test.tsx
packages/dashboard-core-plugins/src/panels/DropdownFilterPanel.tsx

- Coverage is now 100% for DropdownFilter

Add tests for DropdownFilter

---

packages/grid/src/GridMetricCalculator.ts

Fix scrollbars drawing without handles when grid is the perfect size

---

packages/console/src/common/ConsoleUtils.ts
packages/console/src/common/ObjectIcon.tsx
packages/dashboard-core-plugins/src/GridPlugin.tsx
packages/embed-grid/src/App.tsx
packages/jsapi-shim/src/dh.types.ts

- Adding support for Hierarchical tables (rename of TreeTable)
- Tested using Colin's branch: https://github.com/niloc132/deephaven-core/tree/rwc-rollup-ui-draft-squashed

Hierarchical table support

---

packages/components/src/ItemListItem.tsx

Fixes #1006 
Right clicking an item now deletes the correct selected item.

Deleting file deletes last selected entity

---

lerna.json
package-lock.json
packages/code-studio/package.json
packages/components/package.json
packages/console/package.json
packages/dashboard-core-plugins/package.json
packages/dashboard/package.json
packages/embed-chart/package.json
packages/embed-grid/package.json
packages/file-explorer/package.json
packages/golden-layout/package.json
packages/grid/package.json
packages/iris-grid/package.json
packages/jsapi-components/package.json
packages/pouch-storage/package.json

* `golden-layout`
* [#1028](https://github.com/deephaven/web-client-ui/pull/1028) Clicking save on a new notebook automatically selects input field ([@emilyhuxng](https://github.com/emilyhuxng))
* `iris-grid`
* [#1029](https://github.com/deephaven/web-client-ui/pull/1029) Fix cell overflow viewer with browser zoom ([@emilyhuxng](https://github.com/emilyhuxng))
* [#1031](https://github.com/deephaven/web-client-ui/pull/1031) Existing rows in append-only tables cannot be edited ([@emilyhuxng](https://github.com/emilyhuxng))
* `grid`
* [#1037](https://github.com/deephaven/web-client-ui/pull/1037) Grid selection tick mark goes away after deselection ([@emilyhuxng](https://github.com/emilyhuxng))
* [#1025](https://github.com/deephaven/web-client-ui/pull/1025) Fix vertical scrollbar appearing …

Version Bump v0.26.1

---

package-lock.json
package.json
packages/chart/package.json

- Ran tests and tested some cases locally

Update plotly.js to v2.18.0

---

packages/jsapi-bootstrap/src/ApiBootstrap.tsx
packages/jsapi-shim/src/dh.ts
packages/jsapi-shim/src/dh.types.ts
packages/jsapi-shim/src/index.ts
packages/jsapi-types/src/index.ts

fix: Remove default export in jsapi-types

---

packages/iris-grid/src/GotoRow.tsx

fix: Select Distinct Column Throws `null` error

---

.github/workflows/e2e.yml
.github/workflows/unit.yml

ci: Update 0.31 workflows to run on PRs and pushes to release branches

---

packages/jsapi-utils/src/TableUtils.test.ts
packages/jsapi-utils/src/TableUtils.ts

fix: DH-14439 Fix QueryMonitor breaking on null in default search filter

---

packages/dashboard-core-plugins/src/panels/NotebookPanel.tsx

fix: Save or discard a changed notebook does not close modal on first click

---

packages/redux/src/selectors.ts

Updated redux selectors to properly derive return types from generic input types.
fixes #1197

fix: Fixed generic selector types

---

packages/react-hooks/src/index.ts
packages/react-hooks/src/usePromiseFactory.test.ts
packages/react-hooks/src/usePromiseFactory.ts

Enterprise DH-14630
Community #1221 
Custom React hook for using Promise factory functions.

feat: usePromiseFactory hook

---

packages/grid/src/Grid.tsx
packages/grid/src/GridRenderer.test.tsx
packages/grid/src/GridRenderer.ts
packages/grid/src/GridRendererTypes.ts
packages/grid/src/index.ts

refactor: Move GridRenderer types into new file

---

packages/jsapi-components/package.json

fix: Fixed dependency mapping

---

package-lock.json

fix: Fixed bad dependency in package-lock

---

.github/workflows/publish-alpha.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish-packages.yml

Should fix the secret used to publish v0.13 versions

fix: Release action secret name

---

packages/jsapi-components/src/useTableUtils.test.tsx
packages/jsapi-components/src/useTableUtils.ts

feat: useTableUtils hook

---

packages/iris-grid/src/IrisGrid.tsx

Cherry pick of #1286 for fixing #1275

fix: cherry-pick Select distinct throwing for tables with multiple columns (#1286)

---

packages/log/src/LogProxy.ts

Closes #1253 
- sample output logs: [console.txt](https://github.com/deephaven/web-client-ui/files/11466158/console.txt)
- search for "can't handle this - ethan"

feat: add uncaught rejections to support logs

---

packages/dashboard/src/layout/GoldenLayout.scss

style: underlay for maximized panels

---

packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
packages/iris-grid/src/IrisGrid.tsx
packages/iris-grid/src/IrisGridUtils.test.ts
packages/iris-grid/src/IrisGridUtils.ts

- Update dehydration methods to return null instead of undefined
- Add unit tests to catch similar dehydration bugs the future

fix: DH-15032: Fix incorrect warning about updated shared state

---

packages/dashboard-core-plugins/src/panels/ChartPanel.tsx
packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
packages/iris-grid/src/IrisGrid.tsx
packages/iris-grid/src/IrisGridUtils.test.ts
packages/iris-grid/src/IrisGridUtils.ts

- Update dehydration methods to return null instead of undefined
- Add unit tests to catch similar dehydration bugs the future

fix: DH-15032: Fix incorrect warning about updated shared state (#1364)

---

packages/components/src/context-actions/ContextActions.tsx
packages/storage/src/Storage.ts
packages/storage/src/StorageTableViewportUpdater.ts

- JS to TS conversion fixes found from doing Enterprise conversion

build: TypeScript fixes

---

packages/utils/src/index.ts

fix: export TypeUtils

---

packages/iris-grid/src/IrisGridTableModel.ts
packages/iris-grid/src/IrisGridTableModelTemplate.ts

fix: tree and rollup default to non-sortable

---

packages/auth-plugins/src/Login.scss

Fixes #1399
Add missing class prefix of modified login form.

fix: login page looks bad when narrow

---

tests/table-operations.spec.ts

fix: failing table operations e2e test

---

packages/jsapi-bootstrap/src/ApiBootstrap.tsx

- Remove a warning when building with webpack: https://stackoverflow.com/a/73359606

fix: Change dynamic import to string

---

.gitignore
playwright.config.ts

- Set `actionTimeout` to 15 seconds
- Added `docker-compose.override.yml` to gitignore
resolves #1800

test: Set actionTimeout to 15 seconds (#1800)

---

package-lock.json
packages/app-utils/package.json
packages/code-studio/package.json
packages/components/package.json
packages/components/scss/BaseStyleSheet.scss
packages/components/src/__snapshots__/SpectrumUtils.test.ts.snap
packages/components/src/theme/__snapshots__/ThemeProvider.test.tsx.snap
packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
packages/react-hooks/package.json

Upgraded React Spectrum to ^3.41.1
resolves #1832

chore: Upgraded React Spectrum to ^3.41.1

---

packages/components/src/SpectrumComponent.module.scss

I missed 1 Spectrum selector that is needed for DHE ACL Editor
Supports DH-16554

fix: Spectrum actionbar selector

---

tests/table-operations.spec.ts

- Adds #1897 
- Redisable drag test but for webkit only

test: disable drag test

---

packages/code-studio/src/main/AppMainContainer.tsx
packages/components/src/shortcuts/GlobalShortcuts.ts
packages/dashboard/src/PanelEvent.ts
packages/dashboard/src/PanelManager.ts

- Add #1785 
- Add keyboard shortcut (Alt+Shift+A) to reopen last closed tab

feat: reopen closed tabs

---

packages/components/src/HierarchicalCheckboxMenu.tsx

- Fix #1856 
- Fix boolean logic

fix: unable to select deselected leaf

---

tests/table.spec.ts

- Adds #1784 
- Add an event to see if download was triggered

test: ensure table downloaded

---

.github/workflows/e2e.yml
playwright-ci.config.ts

- Adds #1933 
- Shards Playwright E2E tests by browser
- Webkit into 2 shards because it runs slower

ci: shard e2e tests

---

tests/table.spec.ts

- Adds #1966 
- Disables the download check for Webkit

test: disable download for webkit

---

.github/workflows/e2e.yml
.github/workflows/unit.yml

- We were not running tests on feature branches

ci: Enable tests on feature branches

---

packages/iris-grid/src/IrisGridTableModelTemplate.ts
packages/iris-grid/src/IrisGridTestUtils.ts
packages/iris-grid/src/IrisGridTreeTableModel.test.ts
packages/iris-grid/src/IrisGridTreeTableModel.ts

- Related to DH-17076
- Needed a Core patch:
https://github.com/deephaven/deephaven-core/pull/5555
- Tested using both the Groovy snippet from the ticket
- Fixes #2035

fix: DH-17076 LayoutHints on TreeTables were not being applied (#2041)

---

packages/dashboard-core-plugins/src/panels/ConsolePanel.tsx

Resolves https://github.com/deephaven/web-client-ui/issues/2037
**Changes Implemented:** 
- Changed the destructuring in the `ConsolePanel.tsx` `openWidget` method to set `title` to be  the `name` if `title` is undefined

fix: CSV Drag and Drop Console Error

---

package-lock.json
packages/components/package.json
packages/components/src/spectrum/forms.ts

I missed some prop types on #2020

fix: re-export Radio and RadioGroup prop types

---

packages/iris-grid/src/index.ts

This is for https://github.com/deephaven/deephaven-plugins/pull/522

feat: Export iris-grid mouse handlers

---

packages/grid/src/Grid.tsx

fix: Propogation of Scroll Events when Scroll Position is at a Boundary

---

.eslintrc.js

fix: Restrict @adobe/spectrum imports

---

packages/dashboard-core-plugins/src/panels/WidgetPanel.tsx
packages/dashboard-core-plugins/src/panels/index.ts

- Wasn't being published, needed for the DHE refactoring of core plugins
- Specifically: https://github.com/deephaven-ent/iris/pull/2114/files#diff-536d6ac232028a4ebbafc5ca79bb1a22844488a4b628196e43056379f9326a90R17

fix: Publish WidgetPanelProps

---

packages/iris-grid/src/IrisGridProxyModel.ts

Fixes https://deephaven.atlassian.net/browse/DH-17730 in Enterprise. Will need to be cherry picked back to v0.85.
web-client-ui issue is https://github.com/deephaven/web-client-ui/issues/2234

fix: DH-17730: Fix Proxy Model Undefined Formatter

---

packages/golden-layout/src/controls/Tab.ts
packages/golden-layout/src/utils/DragListener.ts

fix: Closing tab with middle mouse on Linux pasting into active editor

---

packages/console/src/ConsoleInput.scss
packages/console/src/notebook/Editor.scss

- Adds #2247 
- Adds a few CSS overrides to Monaco

feat: add monaco docs CSS override

---

packages/console/src/Console.tsx

fix: console scrolls on 1st code block run

---

package-lock.json
packages/jsapi-nodejs/package.json
packages/jsapi-nodejs/src/loaderUtils.ts

- Externalize `esbuild` dependency
- Added a parameter for additional esbuild options
resolves #2284

fix: Externalized esbuild dependency (2284)

---

packages/components/src/XComponent.tsx
packages/components/src/index.ts

- Just stub it out so deephaven.ui v0.22 works in Grizzly
- Prerequisite for DH-18058

fix: Add createXComponent stub for support in Grizzly

---

jest.setup.ts
packages/console/src/Console.tsx
tests/console.spec.ts

This reverts commit 648e8c030bb3f03ca00fc0503874b4947f3f8d54.

revert: Revert "fix: Console history did not stick to bottom on visibility changes (#2320)"

---

packages/components/src/spectrum/collections.ts

Need to export these to implement menu in deephave.ui
https://deephaven.atlassian.net/browse/DH-18089

feat: Export Spectrum Menu and SubmenuTrigger

---

packages/iris-grid/src/format-context-menus/DecimalFormatContextMenu.ts
packages/iris-grid/src/format-context-menus/IntegerFormatContextMenu.ts
packages/jsapi-utils/src/formatters/DecimalColumnFormatter.ts
packages/jsapi-utils/src/formatters/IntegerColumnFormatter.ts

feat: add thousands format for numbers

---

tests/shortcuts.spec.ts

Follow up fix on https://github.com/deephaven/web-client-ui/pull/2336

test: Fix download shortcut test flakiness

---

packages/chart/src/Chart.tsx
packages/chart/src/ChartModel.ts

It appears that decimal and integer format options weren't correctly passing through so the chart was not receiving updates.

fix: fix format options

---

packages/iris-grid/src/IrisGrid.tsx
packages/iris-grid/src/IrisGridUtils.ts
packages/iris-grid/src/sidebar/aggregations/AggregationOperation.ts
packages/iris-grid/src/sidebar/aggregations/AggregationUtils.ts
packages/iris-grid/src/sidebar/aggregations/Aggregations.test.tsx
packages/iris-grid/src/sidebar/aggregations/Aggregations.tsx

https://deephaven.atlassian.net/browse/DH-18856
Cherry pick back to Grizzly.

feat: add median agg for totals table

---

packages/components/src/spectrum/collections.ts

Need to export these to implement menu in deephave.ui https://deephaven.atlassian.net/browse/DH-18089

feat: Export Spectrum Menu and SubmenuTrigger (#2322)

---

packages/iris-grid/src/IrisGrid.tsx
packages/iris-grid/src/IrisGridPartitionSelector.scss
packages/iris-grid/src/IrisGridPartitionSelector.test.tsx
packages/iris-grid/src/IrisGridPartitionSelector.tsx
packages/iris-grid/src/IrisGridPartitionedTableModel.ts
packages/iris-grid/src/IrisGridProxyModel.ts
packages/iris-grid/src/IrisGridTableModel.ts
packages/iris-grid/src/PartitionedGridModel.ts
packages/iris-grid/src/mousehandlers/IrisGridContextMenuHandler.tsx
packages/iris-grid/src/mousehandlers/IrisGridPartitionedTableMouseHandler.ts
packages/iris-grid/src/mousehandlers/index.ts

Cherry pick back this fix https://github.com/deephaven/web-client-ui/pull/2110/files
Need for this PR: https://deephaven.atlassian.net/browse/DH-19324

feat: Partitioned Table UI Enhancements (#2110)

---

packages/iris-grid/src/sidebar/TableCsvExporter.scss
packages/iris-grid/src/sidebar/TableCsvExporter.test.tsx
packages/iris-grid/src/sidebar/TableCsvExporter.tsx

DH-19392: Previously, form controls were nested as children of the Spectrum `Radio` component, which made them not clickable. The fix moves the form controls outside the `Radio` component.

fix: DH-19392: resolve interaction issue caused by nested radio content

---

packages/jsapi-utils/src/TableUtils.ts

DH-18086: Making event details generic on
TableUtils.makeCancelableTableEventPromise

feat: Cherry-pick Made event details generic

---

packages/iris-grid/src/sidebar/TableCsvExporter.scss

style: remove unintended trailing semicolon

---

packages/dashboard-core-plugins/src/linker/Linker.tsx
packages/dashboard-core-plugins/src/linker/LinkerOverlayContent.tsx
packages/dashboard-core-plugins/src/linker/LinkerUtils.ts
packages/iris-grid/src/IrisGrid.tsx

fix: DH-20500: Links without operators not working (#2541)
